-- Generated from pinned D-05 source; read-only metadata assertion.
SELECT
  (SELECT COUNT(*)
   FROM information_schema.table_constraints
   WHERE constraint_schema = 'kinga_staging'
     AND constraint_type = 'FOREIGN KEY'
     AND constraint_name IN (
  'appointments_claim_id_claims_id_fk',
  'assessor_evaluations_claim_id_claims_id_fk',
  'assessor_evaluations_source_report_id_assessor_reports_id_fk',
  'audit_trail_claim_id_claims_id_fk',
  'automation_audit_log_claim_id_claims_id_fk',
  'claim_approvals_claim_id_claims_id_fk',
  'claim_events_claim_id_claims_id_fk',
  'claim_intake_requests_claim_id_claims_id_fk',
  'claim_intelligence_dataset_claim_id_claims_id_fk',
  'claim_involvement_tracking_claim_id_claims_id_fk',
  'cross_claim_signals_claim_id_claims_id_fk',
  'driver_claims_claim_id_claims_id_fk',
  'fast_track_routing_log_claim_id_claims_id_fk',
  'fk_aal_automation_policy',
  'fk_aal_confidence_score',
  'fk_aal_routing_decision',
  'fk_ae_accepted_review',
  'mismatch_annotations_claim_id_claims_id_fk',
  'model_training_queue_claim_id_claims_id_fk',
  'narrative_versions_claim_id_claims_id_fk',
  'policy_claim_links_claim_id_claims_id_fk',
  'risk_register_claim_id_claims_id_fk',
  'routing_history_claim_id_claims_id_fk',
  'third_party_vehicles_claim_id_claims_id_fk',
  'usage_events_claim_id_claims_id_fk'
     )) AS existing_d05_foreign_keys,
  (SELECT COUNT(*)
   FROM (
     SELECT table_name, index_name
     FROM information_schema.statistics
     WHERE table_schema = 'kinga_staging'
       AND (table_name, index_name) IN (
         ('anonymization_audit_log', 'idx_aal_anonymized_at'),
         ('anonymization_audit_log', 'idx_aal_source_record'),
         ('anonymization_audit_log', 'idx_aal_status'),
         ('assessor_evaluations', 'idx_evaluations_assessor_id'),
         ('assessor_evaluations', 'idx_evaluations_claim_id'),
         ('assessor_insurer_relationships', 'idx_preferred'),
         ('assessor_insurer_relationships', 'idx_status'),
         ('assessor_insurer_relationships', 'idx_tenant'),
         ('assessor_insurer_relationships', 'idx_type'),
         ('assessor_insurer_relationships', 'unique_assessor_tenant'),
         ('assessor_subscriptions', 'idx_asub_profile'),
         ('assessor_subscriptions', 'idx_asub_tier'),
         ('assessor_subscriptions', 'idx_asub_user'),
         ('assessors', 'idx_marketplace_status'),
         ('assessors', 'idx_performance'),
         ('assessors', 'idx_primary_tenant'),
         ('assessors', 'idx_rating'),
         ('assessors', 'idx_type'),
         ('assessors', 'professional_license_number'),
         ('assessors', 'user_id'),
         ('asset_registry', 'idx_ar_owner'),
         ('asset_registry', 'idx_ar_tenant'),
         ('asset_registry', 'idx_ar_type'),
         ('asset_registry', 'idx_ar_vehicle_reg'),
         ('audit_trail', 'idx_audit_claim_id'),
         ('audit_trail', 'idx_audit_created_at'),
         ('audit_trail', 'idx_audit_user_id'),
         ('automation_audit_log', 'idx_claim_id'),
         ('automation_audit_log', 'idx_composite_score'),
         ('automation_audit_log', 'idx_decision_made_at'),
         ('automation_audit_log', 'idx_routed_workflow'),
         ('automation_audit_log', 'idx_tenant_id'),
         ('automation_audit_log', 'idx_was_overridden'),
         ('calibration_overrides', 'idx_cal_scenario'),
         ('calibration_overrides', 'idx_cal_status'),
         ('calibration_overrides', 'idx_cal_tenant_jurisdiction'),
         ('claim_approvals', 'idx_ca_acted_at'),
         ('claim_approvals', 'idx_ca_claim_id'),
         ('claim_approvals', 'idx_ca_role_key'),
         ('claim_approvals', 'idx_ca_stage_order'),
         ('claim_approvals', 'idx_ca_tenant_id'),
         ('claim_events', 'idx_ce_claim_id'),
         ('claim_events', 'idx_ce_emitted_at'),
         ('claim_events', 'idx_ce_event_type'),
         ('claim_intake_requests', 'idx_claim_intake_request_claim'),
         ('claim_intake_requests', 'idx_claim_intake_request_tenant_status'),
         ('claim_intelligence_dataset', 'idx_anonymized_at'),
         ('claim_intelligence_dataset', 'idx_cid_captured_at'),
         ('claim_intelligence_dataset', 'idx_cid_schema_version'),
         ('claim_intelligence_dataset', 'idx_cid_tenant_id'),
         ('claim_intelligence_dataset', 'idx_data_scope'),
         ('claim_intelligence_dataset', 'idx_global_sharing'),
         ('claim_involvement_tracking', 'idx_involvement_claim_user'),
         ('claim_involvement_tracking', 'idx_involvement_claim_user_stage'),
         ('claim_review_queue', 'claim_review_queue_historical_claim_id_unique'),
         ('component_benchmarks', 'idx_cb_component_id'),
         ('component_benchmarks', 'idx_cb_component_make'),
         ('component_benchmarks', 'idx_cb_market_currency'),
         ('component_benchmarks', 'idx_cb_vehicle_precision'),
         ('cross_claim_signals', 'idx_ccs_claim_id'),
         ('cross_claim_signals', 'idx_ccs_confidence'),
         ('cross_claim_signals', 'idx_ccs_dismissed'),
         ('cross_claim_signals', 'idx_ccs_signal_type'),
         ('cross_claim_signals', 'idx_ccs_tenant'),
         ('dataset_access_grants', 'idx_dag_data_scope'),
         ('dataset_access_grants', 'idx_dag_expiry_date'),
         ('dataset_access_grants', 'idx_dag_granted_to_user'),
         ('dataset_access_grants', 'idx_dag_tenant_id'),
         ('driver_claims', 'idx_dc_claim_id'),
         ('driver_claims', 'idx_dc_driver_id'),
         ('driver_claims', 'idx_dc_role'),
         ('driver_claims', 'idx_dc_tenant'),
         ('fast_track_config', 'idx_ft_config_claim_type'),
         ('fast_track_config', 'idx_ft_config_effective'),
         ('fast_track_config', 'idx_ft_config_enabled'),
         ('fast_track_config', 'idx_ft_config_hierarchy'),
         ('fast_track_config', 'idx_ft_config_product'),
         ('fast_track_config', 'idx_ft_config_tenant'),
         ('fast_track_routing_log', 'idx_ft_log_claim'),
         ('fast_track_routing_log', 'idx_ft_log_claim_tenant'),
         ('fast_track_routing_log', 'idx_ft_log_config'),
         ('fast_track_routing_log', 'idx_ft_log_decision'),
         ('fast_track_routing_log', 'idx_ft_log_evaluated'),
         ('fast_track_routing_log', 'idx_ft_log_tenant'),
         ('federated_learning_metadata', 'idx_flm_model_type'),
         ('federated_learning_metadata', 'idx_flm_round_number'),
         ('federated_learning_metadata', 'idx_flm_training_started'),
         ('final_approval_records', 'historical_claim_id'),
         ('global_anonymized_dataset', 'anonymous_record_id'),
         ('global_anonymized_dataset', 'idx_gad_accident_type'),
         ('global_anonymized_dataset', 'idx_gad_anonymized_at'),
         ('global_anonymized_dataset', 'idx_gad_capture_month'),
         ('global_anonymized_dataset', 'idx_gad_province'),
         ('global_anonymized_dataset', 'idx_gad_vehicle_make'),
         ('global_search_analytics', 'idx_gsa_query'),
         ('global_search_analytics', 'idx_gsa_searched_at'),
         ('global_search_analytics', 'idx_gsa_tenant_id'),
         ('global_search_history', 'idx_gsh_searched_at'),
         ('global_search_history', 'idx_gsh_tenant_id'),
         ('global_search_history', 'idx_gsh_user_id'),
         ('historical_claims', 'idx_hc_batch'),
         ('historical_claims', 'idx_hc_status'),
         ('historical_claims', 'idx_hc_tenant'),
         ('historical_replay_results', 'idx_historical_replay_results_historical_claim_id'),
         ('historical_replay_results', 'idx_historical_replay_results_policy_version_id'),
         ('historical_replay_results', 'idx_historical_replay_results_replayed_at'),
         ('historical_replay_results', 'idx_historical_replay_results_tenant_id'),
         ('iso_audit_logs', 'idx_iso_audit_logs_tenant_id'),
         ('iso_audit_logs', 'idx_iso_audit_logs_timestamp'),
         ('iso_audit_logs', 'idx_iso_audit_logs_user_id'),
         ('mismatch_annotations', 'idx_ma_action'),
         ('mismatch_annotations', 'idx_ma_claim'),
         ('mismatch_annotations', 'idx_ma_type'),
         ('mismatch_annotations', 'idx_ma_user'),
         ('model_training_queue', 'idx_mtq_created_at'),
         ('model_training_queue', 'idx_mtq_processed'),
         ('model_training_queue', 'idx_mtq_training_priority'),
         ('narrative_versions', 'idx_nv_active'),
         ('narrative_versions', 'idx_nv_assessment'),
         ('narrative_versions', 'idx_nv_claim'),
         ('narrative_versions', 'idx_nv_type'),
         ('personal_vehicles', 'personal_vehicles_user_id'),
         ('physical_measurements', 'idx_pm_captured_at'),
         ('physical_measurements', 'idx_pm_captured_by'),
         ('physical_measurements', 'idx_pm_category'),
         ('physical_measurements', 'idx_pm_inspection'),
         ('physical_measurements', 'idx_pm_tenant'),
         ('pipeline_jobs', 'idx_pj_claim_id'),
         ('pipeline_jobs', 'idx_pj_run_id'),
         ('pipeline_jobs', 'idx_pj_stage_id'),
         ('pipeline_jobs', 'idx_pj_status'),
         ('pipeline_runs', 'idx_pr_claim_id'),
         ('pipeline_runs', 'idx_pr_run_id'),
         ('pipeline_runs', 'idx_pr_started_at'),
         ('pipeline_runs', 'idx_pr_status'),
         ('policy_endorsements', 'policy_endorsements_endorsement_number_unique'),
         ('predictive_risk_scores', 'idx_prs_entity'),
         ('predictive_risk_scores', 'idx_prs_score_type'),
         ('predictive_risk_scores', 'idx_prs_tenant_id'),
         ('predictive_risk_scores', 'idx_prs_valid_from'),
         ('quotation_requests', 'request_number'),
         ('replay_logs', 'idx_rl_changed'),
         ('replay_logs', 'idx_rl_claim'),
         ('replay_logs', 'idx_rl_replayed_at'),
         ('replay_logs', 'idx_rl_tenant'),
         ('risk_register', 'idx_risk_register_claim_id'),
         ('risk_register', 'idx_risk_register_tenant_id'),
         ('role_assignment_audit', 'idx_changed_by'),
         ('role_assignment_audit', 'idx_role_audit_tenant_time'),
         ('role_assignment_audit', 'idx_role_audit_user_time'),
         ('role_assignment_audit', 'idx_tenant_id'),
         ('role_assignment_audit', 'idx_timestamp'),
         ('role_assignment_audit', 'idx_user_id'),
         ('routing_history', 'idx_routing_claim_id'),
         ('routing_history', 'idx_routing_claim_tenant'),
         ('routing_history', 'idx_routing_tenant_id'),
         ('routing_history', 'idx_routing_timestamp'),
         ('routing_threshold_config', 'idx_threshold_active'),
         ('routing_threshold_config', 'idx_threshold_tenant_active'),
         ('routing_threshold_config', 'idx_threshold_tenant_id'),
         ('routing_threshold_config', 'unique_threshold_tenant_version'),
         ('shadow_override_monitor', 'idx_som_activity'),
         ('shadow_override_monitor', 'idx_som_scanned'),
         ('shadow_override_monitor', 'idx_som_tenant'),
         ('shadow_override_monitor', 'idx_som_user'),
         ('super_audit_sessions', 'idx_super_audit_sessions_audited_tenant_id'),
         ('super_audit_sessions', 'idx_super_audit_sessions_session_started_at'),
         ('super_audit_sessions', 'idx_super_audit_sessions_super_admin_user_id'),
         ('supplier_performance_metrics', 'supplier_performance_metrics_supplier_name_unique'),
         ('system_errors', 'idx_se_error_code'),
         ('system_errors', 'idx_se_occurred_at'),
         ('system_errors', 'idx_se_procedure'),
         ('system_errors', 'idx_se_user_id'),
         ('tenant_isolation_violations', 'idx_tiv_occurred_at'),
         ('tenant_isolation_violations', 'idx_tiv_procedure'),
         ('tenant_isolation_violations', 'idx_tiv_user_id'),
         ('tenant_isolation_violations', 'idx_tiv_user_tenant'),
         ('training_data_scores', 'training_data_scores_historical_claim_id_unique'),
         ('training_dataset', 'training_dataset_historical_claim_id_unique'),
         ('usage_events', 'claim_idx'),
         ('usage_events', 'event_type_idx'),
         ('usage_events', 'reference_idx'),
         ('usage_events', 'tenant_idx'),
         ('usage_events', 'timestamp_idx'),
         ('variance_datasets', 'idx_vd_claim'),
         ('variance_datasets', 'idx_vd_tenant'),
         ('variance_datasets', 'idx_vd_type'),
         ('weight_adjustment_log', 'idx_wal_created_at'),
         ('weight_adjustment_log', 'idx_wal_direction'),
         ('weight_adjustment_log', 'idx_wal_type')
       )
     GROUP BY table_name, index_name
   ) AS distinct_d05_indexes) AS existing_d05_explicit_indexes;
