// Dynamic imports - jspdf (707KB) only loaded when user clicks export
type JsPDFType = import('jspdf').jsPDF;

export async function loadPdfLibs() {
  const { jsPDF } = await import('jspdf');
  const { default: autoTable } = await import('jspdf-autotable');
  return { jsPDF, autoTable };
}

/** Fetch the KINGA logo as a base64 data URL for reliable embedding in jsPDF */
export async function loadKingaLogoBase64(): Promise<string> {
  try {
    const url = 'https://files.manuscdn.com/user_upload_by_module/session_file/310419663031527958/dOfoldGKvKSMqKYG.png';
    const resp = await fetch(url);
    const blob = await resp.blob();
    return await new Promise<string>((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch {
    return ''; // graceful degradation — header will still render without logo
  }
}

/**
 * Draw the KINGA branded header on the current page.
 * Must be called AFTER content is written so it doesn't get overwritten.
 * @param doc  jsPDF instance
 * @param logoBase64  base64 data URL of the KINGA logo (may be empty string)
 * @param reportTitle  subtitle shown next to the logo (e.g. "Fraud Detection & Comparison Report")
 * @param pageWidth  page width in mm
 */
function drawKingaHeader(doc: JsPDFType, logoBase64: string, reportTitle: string, pageWidth: number): void {
  // Dark green brand bar across the top
  doc.setFillColor(20, 83, 45); // green-900
  doc.rect(0, 0, pageWidth, 14, 'F');

  // Logo on the left inside the bar
  if (logoBase64) {
    try {
      doc.addImage(logoBase64, 'PNG', 5, 1, 12, 12);
    } catch { /* ignore */ }
  }

  // "KINGA" brand text
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(255, 255, 255);
  doc.text('KINGA', 20, 9);

  // Separator dot
  doc.setFontSize(9);
  doc.setTextColor(134, 239, 172); // green-300
  doc.text('|', 36, 9);

  // Report subtitle
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(209, 250, 229); // green-100
  doc.text(reportTitle, 41, 9);

  // "CONFIDENTIAL" badge on the right
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.setTextColor(134, 239, 172);
  doc.text('CONFIDENTIAL', pageWidth - 30, 9);

  // Reset text colour
  doc.setTextColor(0, 0, 0);
}

/**
 * Draw a diagonal KINGA watermark across the current page.
 * Uses repeated text at 45° angle, very low opacity.
 */
function drawKingaWatermark(doc: JsPDFType, pageWidth: number, pageHeight: number): void {
  doc.saveGraphicsState();
  // Set very faint colour
  doc.setTextColor(20, 83, 45);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(48);
  // jsPDF opacity via GState
  doc.setGState({ opacity: 0.04 });

  // Rotate 45° around centre and draw "KINGA" multiple times
  const cx = pageWidth / 2;
  const cy = pageHeight / 2;
  const step = 55;
  for (let dy = -pageHeight; dy < pageHeight; dy += step) {
    doc.text('KINGA', cx, cy + dy, { angle: 45, align: 'center' });
  }

  doc.setGState({ opacity: 1 });
  doc.restoreGraphicsState();
  doc.setTextColor(0, 0, 0);
}

/**
 * Draw the footer on the current page.
 */
function drawKingaFooter(doc: JsPDFType, pageNum: number, totalPages: number, pageWidth: number, pageHeight: number): void {
  const footerY = pageHeight - 6;
  // Thin separator line
  doc.setDrawColor(200, 200, 200);
  doc.line(10, footerY - 3, pageWidth - 10, footerY - 3);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(120, 120, 120);
  doc.text(`Generated by KINGA  ·  ${new Date().toLocaleDateString('en-ZA', { year: 'numeric', month: 'long', day: 'numeric' })}`, 10, footerY);
  doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - 10, footerY, { align: 'right' });
  doc.setTextColor(0, 0, 0);
}

/**
 * Apply header, diagonal watermark, and footer to every page of the document.
 * Call this ONCE after all content has been written.
 */
export function applyKingaBranding(doc: JsPDFType, logoBase64: string, reportTitle: string): void {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    drawKingaWatermark(doc, pageWidth, pageHeight);
    drawKingaHeader(doc, logoBase64, reportTitle, pageWidth);
    drawKingaFooter(doc, i, pageCount, pageWidth, pageHeight);
  }
}

export interface ClaimData {
  claimNumber: string;
  vehicle: string;
  registration: string;
  incidentDate: string;
  policeReport?: {
    reportNumber: string;
    policeStation: string;
    officerName: string;
    reportDate: string;
    reportedSpeed: string;
    weather: string;
    description: string;
    speedDiscrepancy?: number;
  };
  vehicleValuation?: {
    estimatedValue: number;
    finalValue: number;
    minPrice: number;
    medianPrice: number;
    maxPrice: number;
    mileageAdjustment?: number;
    valuationMethod: string;
    confidenceScore: number;
    totalLossRatio?: number;
    aiReasoning?: string;
  };
  assessorEvaluation?: {
    estimatedCost: number;
    laborCost: number;
    partsCost: number;
    estimatedDuration: number;
    fraudRisk: string;
    notes?: string;
  };
  quotes: Array<{
    panelBeaterName: string;
    totalCost: number;
    laborCost: number;
    partsCost: number;
    estimatedDuration: number;
    notes?: string;
    lineItems?: Array<{
      description: string;
      quantity: number;
      unitPrice: number;
      totalPrice: number;
    }>;
  }>;
  quoteComparison?: {
    discrepancyCount: number;
    averageQuote: number;
    missingItems: Array<{
      description: string;
      presentIn: string[];
      missingIn: string[];
    }>;
  };
  /** Accident circumstances from the claim record */
  accidentCircumstances?: {
    incidentDescription?: string;
    incidentLocation?: string;
    incidentType?: string;
    accidentType?: string;
  };
  /** KINGA Intelligence Summary — derived from existing claim quotes and KINGA assessment record */
  aiIntelligence?: {
    /** Damaged component names parsed from damagedComponentsJson */
    detectedComponents: string[];
    /** Lowest quoted amount in cents */
    lowestQuote: number;
    /** Median quoted amount in cents */
    medianQuote: number;
    /** Highest quoted amount in cents */
    highestQuote: number;
    /** Percentage spread between lowest and highest: ((max-min)/max)*100 */
    spreadPercent: number;
    /** Name of the recommended repairer, if available */
    recommendedRepairer?: string;
    /** Reason for the recommendation, if available */
    recommendationReason?: string;
    /** Fraud risk level: low | medium | high */
    fraudRisk: string;
    /** Repair complexity: low | medium | high */
    repairComplexity: string;
    /** KINGA confidence score 0-100 */
    confidenceScore: number;
    /** KINGA estimated repair cost (whole dollars, not cents) — shown when no quotes available */
    aiEstimatedCost?: number;
  };
  /**
   * Physics analysis — accepts both normalised DB format ({consistencyScore, _raw: {...}}) and
   * legacy flat format ({impactForce, estimatedSpeed, impactAngle, ...}).
   */
  physicsAnalysis?: Record<string, unknown>;
  /**
   * Forensic analysis — accepts both DB format ({paint, bodywork, tires, fluidLeaks, glass}) and
   * legacy format ({paintAnalysis, bodyworkAnalysis, ...}).
   */
  forensicAnalysis?: Record<string, unknown>;
  /** Damage photo URLs for inclusion in the report */
  damagePhotos?: string[];
}

/**
 * Generate PDF report for claim comparison
 */
