/**
 * pipeline-v2/claimsNotificationGenerator.ts
 *
 * Claims Notification Generator
 *
 * Generates clear, professional notifications for claim lifecycle events using
 * an LLM with a structured JSON schema prompt. Improvements over the original spec:
 *
 *   1. Vehicle context is explicitly used in the message (year/make/model).
 *   2. next_action uses a constrained vocabulary enum — no free-form text.
 *   3. Message is capped at 30 words (slightly relaxed from 25 to accommodate
 *      vehicle context without truncation).
 *   4. A rule-based fallback fires if the LLM is unavailable.
 *   5. Caller receives a `notification_type` field mapped to the DB enum.
 *
 * Usage:
 *   const result = await generateClaimNotification({ ... });
 *   // result.title, result.message, result.priority, result.notification_type
 */

import { invokeLLM } from "../_core/llm";

// ─── Types ────────────────────────────────────────────────────────────────────

/** Constrained next-action vocabulary — prevents free-form LLM text */
export type NextAction =
  | "SUBMIT_DOCUMENTS"
  | "CONTACT_ADJUSTER"
  | "AWAIT_REVIEW"
  | "AWAIT_SETTLEMENT"
  | "NO_ACTION_REQUIRED"
  | "CONTACT_FRAUD_TEAM";

export type EventType =
  | "RETURN_FOR_INFO"
  | "REJECT"
  | "ESCALATION"
  | "APPROVE"
  | "STAGE_ADVANCE";

export interface NotificationInput {
  event_type: EventType;
  claim_id: number | string;
  /** Claim reference number (e.g. CLM-2820001) — shown to user */
  claim_reference?: string | null;
  /** Vehicle year, e.g. 2021 */
  vehicle_year?: number | null;
  /** Vehicle make, e.g. Toyota */
  vehicle_make?: string | null;
  /** Vehicle model, e.g. Corolla */
  vehicle_model?: string | null;
  /** Short operational reason (from escalation engine or manual input) */
  reason?: string | null;
  /** Constrained next action — caller provides this; LLM confirms or selects */
  suggested_next_action?: NextAction | null;
  /** Stage name for STAGE_ADVANCE events */
  stage_name?: string | null;
  /** Actor name (who made the decision) */
  actor_name?: string | null;
}

export interface NotificationOutput {
  /** Short notification title (≤8 words) */
  title: string;
  /** Professional message body (≤30 words, includes claim ref and vehicle) */
  message: string;
  /** Priority level */
  priority: "low" | "medium" | "high" | "urgent";
  /** Next action for the recipient */
  next_action: NextAction;
  /** DB notification type enum value */
  notification_type:
    | "claim_assigned"
    | "quote_submitted"
    | "fraud_detected"
    | "status_changed"
    | "assessment_completed"
    | "approval_required"
    | "document_uploaded"
    | "system_alert";
  /** Whether generated by LLM or fallback */
  source: "llm" | "fallback";
}

// ─── Event → DB type mapping ──────────────────────────────────────────────────

const EVENT_TO_DB_TYPE: Record<EventType, NotificationOutput["notification_type"]> = {
  RETURN_FOR_INFO: "approval_required",
  REJECT: "status_changed",
  ESCALATION: "fraud_detected",
  APPROVE: "status_changed",
  STAGE_ADVANCE: "approval_required",
};

const EVENT_TO_PRIORITY: Record<EventType, NotificationOutput["priority"]> = {
  RETURN_FOR_INFO: "medium",
  REJECT: "high",
  ESCALATION: "urgent",
  APPROVE: "low",
  STAGE_ADVANCE: "medium",
};

const EVENT_TO_NEXT_ACTION: Record<EventType, NextAction> = {
  RETURN_FOR_INFO: "SUBMIT_DOCUMENTS",
  REJECT: "CONTACT_ADJUSTER",
  ESCALATION: "CONTACT_FRAUD_TEAM",
  APPROVE: "AWAIT_SETTLEMENT",
  STAGE_ADVANCE: "AWAIT_REVIEW",
};

// ─── Fallback Rule-Based Generator ───────────────────────────────────────────

function buildFallback(input: NotificationInput): NotificationOutput {
  const ref = input.claim_reference ?? `#${input.claim_id}`;
  const vehicle =
    input.vehicle_year && input.vehicle_make && input.vehicle_model
      ? `${input.vehicle_year} ${input.vehicle_make} ${input.vehicle_model}`
      : input.vehicle_make && input.vehicle_model
      ? `${input.vehicle_make} ${input.vehicle_model}`
      : null;
  const vehiclePart = vehicle ? ` for the ${vehicle}` : "";

  const titles: Record<EventType, string> = {
    RETURN_FOR_INFO: "Additional Information Required",
    REJECT: "Claim Declined",
    ESCALATION: "Claim Referred for Investigation",
    APPROVE: "Claim Approved",
    STAGE_ADVANCE: "Claim Advances to Next Stage",
  };

  const messages: Record<EventType, string> = {
    RETURN_FOR_INFO: `Claim ${ref}${vehiclePart} requires additional information. Please submit the missing documents to proceed.`,
    REJECT: `Claim ${ref}${vehiclePart} has been declined${input.reason ? ` due to ${input.reason}` : ""}. Contact your adjuster for further assistance.`,
    ESCALATION: `Claim ${ref}${vehiclePart} has been referred to the specialist review team${input.reason ? ` — ${input.reason}` : ""}.`,
    APPROVE: `Claim ${ref}${vehiclePart} has been approved. Settlement processing will commence shortly.`,
    STAGE_ADVANCE: `Claim ${ref}${vehiclePart} has advanced to the ${input.stage_name ?? "next"} stage. Awaiting review.`,
  };

  return {
    title: titles[input.event_type],
    message: messages[input.event_type],
    priority: EVENT_TO_PRIORITY[input.event_type],
    next_action: input.suggested_next_action ?? EVENT_TO_NEXT_ACTION[input.event_type],
    notification_type: EVENT_TO_DB_TYPE[input.event_type],
    source: "fallback",
  };
}

// ─── LLM System Prompt ────────────────────────────────────────────────────────

const SYSTEM_PROMPT = `You are a Claims Notification Generator for an insurance claims management system.

Your task is to generate clear, professional notifications for claim lifecycle events.

Return ONLY valid JSON matching this exact schema:
{
  "title": "short title (max 8 words)",
  "message": "professional message body (max 30 words)",
  "priority": "low | medium | high | urgent",
  "next_action": "SUBMIT_DOCUMENTS | CONTACT_ADJUSTER | AWAIT_REVIEW | AWAIT_SETTLEMENT | NO_ACTION_REQUIRED | CONTACT_FRAUD_TEAM"
}

Rules:

1. Tone: Professional, clear, and concise. No AI, system, or internal technical language.

2. Message structure (all four elements in ≤30 words):
   - State the claim reference (e.g. "Claim CLM-2820001")
   - Include the vehicle if provided (e.g. "for the 2021 Toyota Corolla")
   - State the outcome clearly
   - Indicate the reason if provided
   - End with the next step if applicable

3. Event handling:
   RETURN_FOR_INFO → Ask the policyholder to provide missing information. next_action = SUBMIT_DOCUMENTS
   REJECT          → State the decline clearly, reference the reason. next_action = CONTACT_ADJUSTER
   ESCALATION      → Indicate referral to specialist team, do not use "fraud". next_action = CONTACT_FRAUD_TEAM
   APPROVE         → Confirm approval and settlement commencement. next_action = AWAIT_SETTLEMENT
   STAGE_ADVANCE   → Confirm advancement to the named stage. next_action = AWAIT_REVIEW

4. Priority rules:
   REJECT or ESCALATION → "high" or "urgent"
   RETURN_FOR_INFO      → "medium"
   APPROVE              → "low"
   STAGE_ADVANCE        → "medium"

5. next_action MUST be one of the six allowed values exactly. Do NOT invent new values.

6. Output ONLY the JSON object. No markdown, no explanation.`;

// ─── Main Generator ───────────────────────────────────────────────────────────

/**
 * Generate a professional notification for a claim event.
 *
 * Uses the LLM for natural language generation; falls back to rule-based
 * templates if the LLM call fails or returns invalid output.
 */
export async function generateClaimNotification(
  input: NotificationInput
): Promise<NotificationOutput> {
  const userMessage = JSON.stringify({
    event_type: input.event_type,
    claim_id: input.claim_id,
    claim_reference: input.claim_reference ?? `CLM-${input.claim_id}`,
    vehicle: {
      year: input.vehicle_year ?? null,
      make: input.vehicle_make ?? null,
      model: input.vehicle_model ?? null,
    },
    reason: input.reason ?? null,
    suggested_next_action: input.suggested_next_action ?? null,
    stage_name: input.stage_name ?? null,
    actor_name: input.actor_name ?? null,
  });

  try {
    const response = await invokeLLM({
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: userMessage },
      ],
      response_format: {
        type: "json_schema",
        json_schema: {
          name: "claim_notification",
          strict: true,
          schema: {
            type: "object",
            properties: {
              title: { type: "string" },
              message: { type: "string" },
              priority: {
                type: "string",
                enum: ["low", "medium", "high", "urgent"],
              },
              next_action: {
                type: "string",
                enum: [
                  "SUBMIT_DOCUMENTS",
                  "CONTACT_ADJUSTER",
                  "AWAIT_REVIEW",
                  "AWAIT_SETTLEMENT",
                  "NO_ACTION_REQUIRED",
                  "CONTACT_FRAUD_TEAM",
                ],
              },
            },
            required: ["title", "message", "priority", "next_action"],
            additionalProperties: false,
          },
        },
      },
    });

    const raw =
      typeof response?.choices?.[0]?.message?.content === "string"
        ? response.choices[0].message.content
        : null;
    if (!raw) throw new Error("Empty LLM response");

    const parsed = JSON.parse(raw) as {
      title: string;
      message: string;
      priority: string;
      next_action: string;
    };

    // Validate enums — reject invalid values and fall back
    const validPriorities = ["low", "medium", "high", "urgent"];
    const validNextActions = [
      "SUBMIT_DOCUMENTS",
      "CONTACT_ADJUSTER",
      "AWAIT_REVIEW",
      "AWAIT_SETTLEMENT",
      "NO_ACTION_REQUIRED",
      "CONTACT_FRAUD_TEAM",
    ];

    if (!validPriorities.includes(parsed.priority)) {
      throw new Error(`Invalid priority: ${parsed.priority}`);
    }
    if (!validNextActions.includes(parsed.next_action)) {
      throw new Error(`Invalid next_action: ${parsed.next_action}`);
    }

    // Enforce word caps
    const titleWords = (parsed.title ?? "").trim().split(/\s+/);
    const messageWords = (parsed.message ?? "").trim().split(/\s+/);
    const safeTitle = titleWords.length > 8 ? titleWords.slice(0, 8).join(" ") : parsed.title;
    const safeMessage =
      messageWords.length > 30 ? messageWords.slice(0, 30).join(" ") : parsed.message;

    return {
      title: safeTitle,
      message: safeMessage,
      priority: parsed.priority as NotificationOutput["priority"],
      next_action: parsed.next_action as NextAction,
      notification_type: EVENT_TO_DB_TYPE[input.event_type],
      source: "llm",
    };
  } catch (err) {
    console.warn(
      `[ClaimsNotificationGenerator] LLM call failed for claim ${input.claim_id}, using fallback:`,
      err instanceof Error ? err.message : String(err)
    );
    return buildFallback(input);
  }
}
