/**
 * pipeline-v2/escalationReasoningEngine.ts
 *
 * Claims Escalation Reasoning Engine
 *
 * Takes the deterministic routing output (route, priority, anomalies, scores)
 * and uses an LLM to generate a concise ≤12-word operational reason plus a
 * structured flags array — in insurance/operational language, not AI language.
 *
 * The deterministic routing logic in claimsEscalationRouter.ts is NOT replaced;
 * this engine adds the human-readable summary layer on top.
 *
 * Falls back to a rule-based short reason if the LLM call fails or times out.
 */

import { invokeLLM } from "../_core/llm";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface EscalationReasoningInput {
  /** Deterministic route already computed */
  route: "AUTO_APPROVE" | "ADJUSTER_REVIEW" | "FRAUD_TEAM";
  /** Final recommendation from decision engine */
  decision_recommendation: "APPROVE" | "REVIEW" | "REJECT";
  /** Overall confidence score (0–100) */
  confidence: number | null;
  /** Anomaly descriptions */
  anomalies: string[];
  /** Fraud score (0–100); null if not computed */
  fraud_score: number | null;
  /** Evidence completeness percentage (0–100) */
  evidence_completeness: number | null;
  /** Number of structural gaps detected */
  structural_gaps_count: number;
  /** Whether the claim is out-of-domain for the AI model */
  out_of_domain: boolean;
  /** Claim reference for logging */
  claim_reference?: string | null;
}

export interface EscalationReasoningOutput {
  /** Confirmed route (mirrors input — LLM cannot override deterministic routing) */
  route: "AUTO_APPROVE" | "ADJUSTER_REVIEW" | "FRAUD_TEAM";
  /** Short operational reason (≤12 words) */
  reason: string;
  /** Structured flags for UI display */
  flags: string[];
  /** Priority level */
  priority: "LOW" | "MEDIUM" | "HIGH";
  /** Whether the reason was generated by LLM or fell back to rule-based */
  source: "llm" | "fallback";
}

// ─── Fallback Rule-Based Reason Generator ────────────────────────────────────

function buildFallbackReason(input: EscalationReasoningInput): EscalationReasoningOutput {
  const flags: string[] = [];

  if (input.fraud_score != null && input.fraud_score >= 60) flags.push("Fraud Risk");
  if (input.structural_gaps_count > 0) flags.push("Structural Gaps");
  if (input.evidence_completeness != null && input.evidence_completeness < 70) flags.push("Low Evidence");
  if (input.out_of_domain) flags.push("Out of Domain");

  // Priority
  let priority: "LOW" | "MEDIUM" | "HIGH" = "LOW";
  if ((input.fraud_score != null && input.fraud_score >= 70) || (input.confidence != null && input.confidence < 50)) {
    priority = "HIGH";
  } else if (flags.length > 0 || input.decision_recommendation === "REVIEW") {
    priority = "MEDIUM";
  }

  // Short reason
  let reason: string;
  if (input.route === "FRAUD_TEAM") {
    reason = input.fraud_score != null && input.fraud_score >= 70
      ? "High fraud risk detected"
      : "Fraud indicators require specialist review";
  } else if (input.route === "AUTO_APPROVE") {
    reason = "All criteria met; approved for settlement";
  } else if (input.decision_recommendation === "REJECT") {
    reason = "Claim declined; senior adjuster review required";
  } else if (input.confidence != null && input.confidence < 50) {
    reason = "Low confidence; manual verification required";
  } else if (input.evidence_completeness != null && input.evidence_completeness < 70) {
    reason = "Incomplete evidence; adjuster verification needed";
  } else if (input.structural_gaps_count > 0) {
    reason = "Structural gaps require adjuster sign-off";
  } else if (input.anomalies.length > 0) {
    reason = `${input.anomalies.length} anomal${input.anomalies.length === 1 ? "y" : "ies"} require adjuster review`;
  } else {
    reason = "Referred for standard adjuster review";
  }

  return { route: input.route, reason, flags, priority, source: "fallback" };
}

// ─── LLM Prompt ──────────────────────────────────────────────────────────────

const SYSTEM_PROMPT = `You are a Claims Escalation Reasoning Engine.

Your task is to generate a short, operationally useful reason explaining why a claim has been routed to a specific queue.

Return ONLY valid JSON matching this exact schema:
{
  "route": "AUTO_APPROVE | ADJUSTER_REVIEW | FRAUD_TEAM",
  "reason": "short explanation (max 12 words)",
  "flags": ["..."],
  "priority": "LOW | MEDIUM | HIGH"
}

Rules:

1. The route field MUST match the route provided in the input exactly. Do NOT change it.

2. Flags — include any that apply:
   - fraud_score >= 60 → "Fraud Risk"
   - structural_gaps_count > 0 → "Structural Gaps"
   - evidence_completeness < 70 → "Low Evidence"
   - out_of_domain = true → "Out of Domain"
   - anomalies present → "Anomalies Detected"

3. Reason Generation:
   - Must be concise and operational (≤12 words)
   - Prioritise the strongest signal
   - Use insurance and operational language ONLY
   - Do NOT use AI or technical language
   - Examples:
     - "High fraud risk detected"
     - "Low confidence with missing evidence"
     - "Cost deviation exceeds threshold"
     - "Structural gaps require adjuster sign-off"
     - "All criteria met; approved for settlement"

4. Priority:
   - HIGH → fraud_score >= 70 OR confidence < 50
   - MEDIUM → moderate issues (fraud 40–69, confidence 50–69, anomalies present)
   - LOW → clean claims with high confidence

5. Output ONLY the JSON object. No markdown, no explanation.`;

// ─── Main Engine ─────────────────────────────────────────────────────────────

/**
 * Generate a concise operational reason and flags for a routed claim.
 *
 * Uses the LLM for natural language generation; falls back to rule-based
 * logic if the LLM call fails or returns invalid JSON.
 *
 * NOTE: The `route` field in the output always mirrors the deterministic
 * routing input — the LLM cannot override routing decisions.
 */
export async function generateEscalationReason(
  input: EscalationReasoningInput
): Promise<EscalationReasoningOutput> {
  const userMessage = JSON.stringify({
    route: input.route,
    decision_recommendation: input.decision_recommendation,
    confidence: input.confidence,
    anomalies: input.anomalies.slice(0, 5), // cap to avoid token bloat
    fraud_score: input.fraud_score,
    evidence_completeness: input.evidence_completeness,
    structural_gaps_count: input.structural_gaps_count,
    out_of_domain: input.out_of_domain,
  });

  try {
    const response = await invokeLLM({
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: userMessage },
      ],
      response_format: {
        type: "json_schema",
        json_schema: {
          name: "escalation_reason",
          strict: true,
          schema: {
            type: "object",
            properties: {
              route: {
                type: "string",
                enum: ["AUTO_APPROVE", "ADJUSTER_REVIEW", "FRAUD_TEAM"],
              },
              reason: { type: "string" },
              flags: {
                type: "array",
                items: { type: "string" },
              },
              priority: {
                type: "string",
                enum: ["LOW", "MEDIUM", "HIGH"],
              },
            },
            required: ["route", "reason", "flags", "priority"],
            additionalProperties: false,
          },
        },
      },
    });

    const raw = typeof response?.choices?.[0]?.message?.content === "string"
      ? response.choices[0].message.content
      : null;
    if (!raw) throw new Error("Empty LLM response");

    const parsed = JSON.parse(raw) as {
      route: string;
      reason: string;
      flags: string[];
      priority: string;
    };

    // Validate and enforce that route cannot be changed by LLM
    const safeRoute = input.route; // always use deterministic route
    const safePriority = (["LOW", "MEDIUM", "HIGH"].includes(parsed.priority)
      ? parsed.priority
      : "MEDIUM") as "LOW" | "MEDIUM" | "HIGH";

    // Truncate reason to 12 words if LLM exceeded the limit
    const words = (parsed.reason ?? "").trim().split(/\s+/);
    const safeReason = words.length > 12 ? words.slice(0, 12).join(" ") : parsed.reason;

    return {
      route: safeRoute,
      reason: safeReason,
      flags: Array.isArray(parsed.flags) ? parsed.flags : [],
      priority: safePriority,
      source: "llm",
    };
  } catch (err) {
    console.warn(
      `[EscalationReasoning] LLM call failed for ${input.claim_reference ?? "unknown"}, using fallback:`,
      err instanceof Error ? err.message : String(err)
    );
    return buildFallbackReason(input);
  }
}

/**
 * Batch version — generates reasons for multiple claims in parallel.
 * Limits concurrency to 5 to avoid overwhelming the LLM API.
 */
export async function generateEscalationReasonBatch(
  items: Array<{ claim_id: string | number; input: EscalationReasoningInput }>
): Promise<Array<{ claim_id: string | number; reasoning: EscalationReasoningOutput }>> {
  const CONCURRENCY = 5;
  const results: Array<{ claim_id: string | number; reasoning: EscalationReasoningOutput }> = [];

  for (let i = 0; i < items.length; i += CONCURRENCY) {
    const batch = items.slice(i, i + CONCURRENCY);
    const batchResults = await Promise.all(
      batch.map(async (item) => ({
        claim_id: item.claim_id,
        reasoning: await generateEscalationReason(item.input),
      }))
    );
    results.push(...batchResults);
  }

  return results;
}
