/**
 * pipeline-v2/narrativeEngine.ts
 *
 * STAGE 39 — EVIDENCE-ANCHORED NARRATIVE ENGINE
 *
 * Every statement generated by this module:
 *   1. References a data source OR a computed value
 *   2. Avoids generic hedging phrases ("appears to be", "likely", "suggests")
 *   3. Follows the [Observation] → [Evidence] → [Conclusion] (OEC) structure
 *
 * Banned phrases (enforced by containsHedge() at runtime):
 *   appears to be, likely, suggests, may indicate, could be, possibly,
 *   probable, seems, might, potentially, consistent with (as a hedge)
 *
 * Replacement patterns:
 *   "Based on delta-V of X km/h..."
 *   "Damage detected on [component] — [count] component(s) in [zone] zone."
 *   "No supporting photo evidence found — [field] is unverified."
 *
 * Per-domain builders:
 *   buildDamageNarrative()       — Stage 6 damage analysis
 *   buildPhysicsNarrative()      — Stage 7 physics reconstruction
 *   buildFraudNarrative()        — Stage 8 fraud analysis
 *   buildCostNarrative()         — Stage 9 cost estimation
 *   buildCoherenceNarrative()    — Stage 35 damage-physics coherence
 *   buildEvidenceNarrative()     — Stage 38 evidence strength
 *
 * All builders return NarrativeResult:
 *   { sentences: OECSentence[], full_text: string, hedge_violations: string[] }
 */

import type {
  Stage6Output,
  Stage7Output,
  Stage8Output,
  Stage9Output,
} from "./types";
import type { DamagePhysicsCoherenceResult } from "./damagePhysicsCoherence";
import type { CostRealismResult } from "./costRealismValidator";
import type { EvidenceBundle } from "./evidenceStrengthScorer";

// ─────────────────────────────────────────────────────────────────────────────
// OEC sentence structure
// ─────────────────────────────────────────────────────────────────────────────

export interface OECSentence {
  /** What was observed (measurement, count, flag) */
  observation: string;
  /** The data source or computed value that supports it */
  evidence: string;
  /** The engineering conclusion drawn */
  conclusion: string;
  /** Full formatted sentence: observation + evidence + conclusion */
  text: string;
}

export interface NarrativeResult {
  /** Structured OEC sentences */
  sentences: OECSentence[];
  /** Concatenated full text for report embedding */
  full_text: string;
  /** Any hedge phrases detected in the output (should be empty) */
  hedge_violations: string[];
}

// ─────────────────────────────────────────────────────────────────────────────
// Hedge detection
// ─────────────────────────────────────────────────────────────────────────────

/** Banned hedging patterns — all lowercase for case-insensitive matching */
export const HEDGE_PATTERNS: string[] = [
  "appears to be",
  "appears to",
  "likely",
  "suggests",
  "may indicate",
  "could be",
  "possibly",
  "probable",
  "seems to",
  "seems like",
  "might be",
  "might indicate",
  "potentially",
  "it is possible",
  "there is a chance",
  "may be",
  "could indicate",
  "would appear",
];

/**
 * Returns the list of hedge phrases found in the given text.
 * Returns an empty array if the text is clean.
 */
export function detectHedges(text: string): string[] {
  const lower = text.toLowerCase();
  return HEDGE_PATTERNS.filter((p) => lower.includes(p));
}

/** Returns true if the text contains any hedge phrase */
export function containsHedge(text: string): boolean {
  return detectHedges(text).length > 0;
}

// ─────────────────────────────────────────────────────────────────────────────
// OEC formatter
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Build a single OEC sentence from its three parts.
 * Joins them as: "[Observation], based on [evidence] — [conclusion]."
 */
export function oec(observation: string, evidence: string, conclusion: string): OECSentence {
  const text = `${observation}, based on ${evidence} — ${conclusion}.`;
  return { observation, evidence, conclusion, text };
}

/**
 * Build a result from an array of OEC sentences.
 * Validates each sentence for hedge violations.
 */
function buildResult(sentences: OECSentence[]): NarrativeResult {
  const full_text = sentences.map((s) => s.text).join(" ");
  const hedge_violations = detectHedges(full_text);
  return { sentences, full_text, hedge_violations };
}

// ─────────────────────────────────────────────────────────────────────────────
// Formatting helpers
// ─────────────────────────────────────────────────────────────────────────────

function fmt(n: number | null | undefined, unit = "", decimals = 1): string {
  if (n === null || n === undefined) return "not recorded";
  return `${n.toFixed(decimals)}${unit ? " " + unit : ""}`;
}

function fmtInt(n: number | null | undefined, unit = ""): string {
  if (n === null || n === undefined) return "not recorded";
  return `${Math.round(n)}${unit ? " " + unit : ""}`;
}

function fmtCents(cents: number | null | undefined): string {
  if (cents === null || cents === undefined) return "not recorded";
  return `R ${(cents / 100).toFixed(2)}`;
}

function fmtList(items: string[]): string {
  if (items.length === 0) return "none";
  if (items.length === 1) return items[0];
  return items.slice(0, -1).join(", ") + " and " + items[items.length - 1];
}

// ─────────────────────────────────────────────────────────────────────────────
// DAMAGE NARRATIVE (Stage 6)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Build an evidence-anchored damage narrative.
 *
 * Covers:
 *   - Primary zone and component count
 *   - Overall severity score
 *   - Structural damage flag
 *   - Photo evidence availability
 *   - Missing description flag
 */
export function buildDamageNarrative(
  damageAnalysis: Stage6Output,
  imageUrls: string[],
  damageDescription: string | null
): NarrativeResult {
  const sentences: OECSentence[] = [];

  // Primary zone
  const zones = [...(damageAnalysis.damageZones ?? [])].sort(
    (a, b) => b.componentCount - a.componentCount
  );
  const primaryZone = zones[0];
  if (primaryZone) {
    const componentNames = (damageAnalysis.damagedParts ?? [])
      .filter((p) => p.location === primaryZone.zone || p.location?.includes(primaryZone.zone))
      .map((p) => p.name)
      .slice(0, 4);
    const componentLabel = componentNames.length > 0
      ? fmtList(componentNames)
      : `${primaryZone.componentCount} component(s)`;
    sentences.push(oec(
      `Damage detected in the ${primaryZone.zone} zone`,
      `${primaryZone.componentCount} component(s) identified at max severity ${primaryZone.maxSeverity} (Stage 6 damage analysis)`,
      `affected components include ${componentLabel}`
    ));
  }

  // All zones summary
  if (zones.length > 1) {
    const zoneLabels = zones.map((z) => `${z.zone} (${z.componentCount})`).join(", ");
    sentences.push(oec(
      `${zones.length} damage zone(s) identified`,
      `zone breakdown: ${zoneLabels}`,
      `multi-zone damage indicates distributed impact energy`
    ));
  }

  // Overall severity
  const score = damageAnalysis.overallSeverityScore;
  const severityLabel =
    score >= 70 ? "severe" : score >= 40 ? "moderate" : score >= 20 ? "minor" : "cosmetic";
  sentences.push(oec(
    `Overall damage severity scored at ${fmtInt(score)}/100 (${severityLabel})`,
    `${damageAnalysis.damagedParts?.length ?? 0} total damaged component(s) across ${zones.length} zone(s)`,
    severityLabel === "severe"
      ? "repair complexity is elevated and total-loss assessment is required"
      : severityLabel === "moderate"
      ? "standard repair assessment applies"
      : "damage is within normal repair parameters"
  ));

  // Structural damage
  if (damageAnalysis.structuralDamageDetected) {
    sentences.push(oec(
      "Structural damage detected",
      "Stage 6 structural flag set to true",
      "repair must include structural assessment; total-loss evaluation is required"
    ));
  }

  // Photo evidence
  if (imageUrls.length === 0) {
    sentences.push(oec(
      "No photo evidence submitted with this claim",
      "damage.imageUrls array is empty",
      "damage assessment relies solely on document descriptions; independent photo verification is required"
    ));
  } else {
    sentences.push(oec(
      `${imageUrls.length} photo(s) submitted`,
      `damage.imageUrls contains ${imageUrls.length} URL(s)`,
      imageUrls.length >= 3
        ? "multiple angles provide sufficient visual coverage for assessment"
        : "limited photo coverage — additional angles are recommended"
    ));
  }

  // Description
  if (!damageDescription || damageDescription.trim().length === 0) {
    sentences.push(oec(
      "No damage description provided",
      "damage.description field is null or empty",
      "narrative assessment is based on extracted component data only"
    ));
  }

  return buildResult(sentences);
}

// ─────────────────────────────────────────────────────────────────────────────
// PHYSICS NARRATIVE (Stage 7)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Build an evidence-anchored physics reconstruction narrative.
 *
 * Covers:
 *   - Impact direction and speed
 *   - Delta-V and deceleration
 *   - Impact force
 *   - Energy dissipation
 *   - Latent damage probabilities
 */
export function buildPhysicsNarrative(physicsAnalysis: Stage7Output): NarrativeResult {
  const sentences: OECSentence[] = [];

  if (!physicsAnalysis.physicsExecuted) {
    sentences.push(oec(
      "Physics reconstruction was not executed",
      "physicsExecuted = false (non-collision incident type)",
      "impact force, delta-V, and energy figures are not available for this claim"
    ));
    return buildResult(sentences);
  }

  // Impact direction and speed
  const dir = physicsAnalysis.impactVector?.direction ?? "unknown";
  const speed = physicsAnalysis.estimatedSpeedKmh;
  sentences.push(oec(
    `Impact direction determined as ${dir} at ${fmt(speed, "km/h", 0)}`,
    `Stage 7 physics reconstruction using vehicle mass, crush depth, and damage zone data`,
    `${dir} impact at ${fmt(speed, "km/h", 0)} classifies as ${physicsAnalysis.accidentSeverity} severity`
  ));

  // Delta-V and deceleration
  const dv = physicsAnalysis.deltaVKmh;
  const decel = physicsAnalysis.decelerationG;
  sentences.push(oec(
    `Velocity change (ΔV) measured at ${fmt(dv, "km/h", 1)} with deceleration of ${fmt(decel, "g", 1)}`,
    `kinetic energy: ${fmtInt(physicsAnalysis.energyDistribution?.kineticEnergyJ)} J, energy dissipated: ${fmtInt(physicsAnalysis.energyDistribution?.energyDissipatedKj)} kJ`,
    dv !== null && dv > 30
      ? "high ΔV indicates significant structural loading — latent damage inspection is required"
      : dv !== null && dv > 15
      ? "moderate ΔV — standard structural inspection applies"
      : "low ΔV — minor structural loading detected"
  ));

  // Impact force
  sentences.push(oec(
    `Impact force calculated at ${fmt(physicsAnalysis.impactForceKn, "kN", 1)}`,
    `Stage 7 impulse-momentum computation using vehicle mass and ΔV`,
    physicsAnalysis.impactForceKn > 100
      ? "force exceeds 100 kN — high-energy impact requiring full structural review"
      : "force within expected range for reported severity"
  ));

  // Damage consistency score
  const dcs = physicsAnalysis.damageConsistencyScore;
  sentences.push(oec(
    `Damage-physics consistency score: ${fmtInt(dcs)}/100`,
    `Stage 7 cross-correlation of damage zones against computed impact vector`,
    dcs >= 80
      ? "damage pattern is physically coherent with the computed impact"
      : dcs >= 60
      ? "minor inconsistencies detected between damage pattern and impact vector"
      : "significant inconsistencies detected — manual review of damage zones required"
  ));

  // Latent damage
  const latent = physicsAnalysis.latentDamageProbability;
  if (latent) {
    const highRisk = Object.entries(latent)
      .filter(([, v]) => v >= 0.3)
      .map(([k]) => k);
    if (highRisk.length > 0) {
      sentences.push(oec(
        `Latent damage risk identified in: ${fmtList(highRisk)}`,
        `Stage 7 latent probability model — threshold ≥ 0.30`,
        "these systems require inspection before repair sign-off"
      ));
    }
  }

  return buildResult(sentences);
}

// ─────────────────────────────────────────────────────────────────────────────
// FRAUD NARRATIVE (Stage 8)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Build an evidence-anchored fraud risk narrative.
 *
 * Covers:
 *   - Fraud risk score and level
 *   - Active indicators with scores
 *   - Quote deviation
 *   - Damage consistency
 *   - Vehicle and claimant history
 */
export function buildFraudNarrative(fraudAnalysis: Stage8Output): NarrativeResult {
  const sentences: OECSentence[] = [];

  const score = fraudAnalysis.fraudRiskScore ?? 0;
  const level = fraudAnalysis.fraudRiskLevel ?? "low";
  sentences.push(oec(
    `Fraud risk score: ${score}/100 (${level})`,
    `Stage 8 fraud engine — ${(fraudAnalysis.indicators ?? []).length} indicator(s) evaluated`,
    score >= 70
      ? "score exceeds escalation threshold — claim requires investigator assignment"
      : score >= 40
      ? "score exceeds manual review threshold — adjuster verification required"
      : "score is within normal parameters — no escalation triggered"
  ));

  // Active indicators
  const activeIndicators = (fraudAnalysis.indicators ?? []).filter((i) => i.score > 0);
  if (activeIndicators.length > 0) {
    for (const ind of activeIndicators) {
      sentences.push(oec(
        `Fraud indicator triggered: ${ind.indicator}`,
        `category: ${ind.category}, score contribution: ${ind.score} points`,
        ind.description
      ));
    }
  } else {
    sentences.push(oec(
      "No fraud indicators triggered",
      "Stage 8 indicator evaluation returned zero active flags",
      "claim proceeds without fraud-related score penalty"
    ));
  }

  // Quote deviation
  const qd = fraudAnalysis.quoteDeviation;
  if (qd !== null && qd !== undefined) {
    sentences.push(oec(
      `Quote deviation: ${fmt(qd, "%", 1)}`,
      `Stage 8 quote comparison against market benchmark`,
      Math.abs(qd) > 30
        ? `deviation of ${fmt(qd, "%", 1)} exceeds ±30% threshold — quote requires independent verification`
        : "quote is within acceptable market range"
    ));
  } else {
    sentences.push(oec(
      "Quote deviation could not be computed",
      "repairQuote.quoteTotalCents is null",
      "cost benchmarking is unavailable — manual quote review is required"
    ));
  }

  // Damage consistency
  const dcs = fraudAnalysis.damageConsistencyScore ?? 0;
  sentences.push(oec(
    `Damage consistency score: ${fmtInt(dcs)}/100`,
    `Stage 8 cross-check of damage zones against reported incident direction`,
    dcs >= 80
      ? "damage pattern is consistent with the reported incident"
      : dcs >= 60
      ? "minor inconsistencies noted — adjuster review recommended"
      : "damage pattern does not align with reported incident — investigation required"
  ));

  // Vehicle history
  const vh = fraudAnalysis.vehicleClaimHistory;
  if (vh?.flagged) {
    sentences.push(oec(
      "Vehicle claim history flagged",
      `Stage 8 vehicle history check: ${vh.notes ?? "no detail provided"}`,
      "prior claim pattern detected — claim history must be reviewed before settlement"
    ));
  }

  // Claimant frequency
  const cf = fraudAnalysis.claimantClaimFrequency;
  if (cf?.flagged) {
    sentences.push(oec(
      "Claimant claim frequency flagged",
      `Stage 8 claimant frequency check: ${cf.notes ?? "no detail provided"}`,
      "above-average claim frequency detected — claimant profile requires adjuster review"
    ));
  }

  return buildResult(sentences);
}

// ─────────────────────────────────────────────────────────────────────────────
// COST NARRATIVE (Stage 9)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Build an evidence-anchored cost estimation narrative.
 *
 * Covers:
 *   - Expected repair cost vs quoted cost
 *   - Labour and parts breakdown
 *   - Quote deviation
 *   - Savings opportunity
 *   - Parts reconciliation flags
 */
export function buildCostNarrative(
  costAnalysis: Stage9Output,
  quotedTotalCents: number | null
): NarrativeResult {
  const sentences: OECSentence[] = [];

  const expected = costAnalysis.expectedRepairCostCents;
  sentences.push(oec(
    `Expected repair cost: ${fmtCents(expected)}`,
    `Stage 9 cost engine — ${(costAnalysis.repairIntelligence ?? []).length} component(s) priced`,
    `cost range: ${fmtCents(costAnalysis.recommendedCostRange?.lowCents)} – ${fmtCents(costAnalysis.recommendedCostRange?.highCents)}`
  ));

  // Labour and parts breakdown
  const labour = costAnalysis.breakdown?.labourCostCents;
  const parts = costAnalysis.breakdown?.partsCostCents;
  if (labour !== null && labour !== undefined && parts !== null && parts !== undefined) {
    const total = (labour + parts) || 1;
    const labourPct = ((labour / total) * 100).toFixed(1);
    const partsPct = ((parts / total) * 100).toFixed(1);
    sentences.push(oec(
      `Labour: ${fmtCents(labour)} (${labourPct}%), parts: ${fmtCents(parts)} (${partsPct}%)`,
      `Stage 9 breakdown — labour rate: ${fmt(costAnalysis.labourRateUsdPerHour, "USD/hr", 0)}`,
      parseFloat(labourPct) < 20 || parseFloat(labourPct) > 60
        ? `labour ratio of ${labourPct}% is outside the 20–60% benchmark — cost realism review applied`
        : `labour ratio of ${labourPct}% is within the 20–60% benchmark`
    ));
  }

  // Quote deviation
  const qd = costAnalysis.quoteDeviationPct;
  if (qd !== null && qd !== undefined) {
    sentences.push(oec(
      `Quote deviation: ${fmt(qd, "%", 1)} vs AI estimate`,
      `quoted total: ${fmtCents(quotedTotalCents)}, AI estimate: ${fmtCents(expected)}`,
      Math.abs(qd) > 30
        ? `deviation of ${fmt(qd, "%", 1)} exceeds ±30% threshold — independent quote verification required`
        : `deviation of ${fmt(qd, "%", 1)} is within acceptable tolerance`
    ));
  } else {
    sentences.push(oec(
      "Quote deviation not computed",
      "repairQuote.quoteTotalCents is null",
      "cost benchmarking is unavailable — manual quote review is required"
    ));
  }

  // Savings opportunity
  const savings = costAnalysis.savingsOpportunityCents;
  if (savings !== null && savings !== undefined && savings > 0) {
    sentences.push(oec(
      `Savings opportunity identified: ${fmtCents(savings)}`,
      `Stage 9 cost optimisation — ${(costAnalysis.partsReconciliation ?? []).filter((p) => p.flag !== null).length} part(s) flagged`,
      "adjuster should negotiate quoted line items before authorising repair"
    ));
  }

  // Parts reconciliation flags
  const flaggedParts = (costAnalysis.partsReconciliation ?? []).filter((p) => p.flag !== null);
  if (flaggedParts.length > 0) {
    const names = flaggedParts.map((p) => `${p.component} (${fmt(p.variancePct, "%", 1)} variance)`);
    sentences.push(oec(
      `${flaggedParts.length} part(s) flagged in reconciliation`,
      `Stage 9 parts reconciliation: ${fmtList(names)}`,
      "flagged parts require price justification from repairer before authorisation"
    ));
  }

  return buildResult(sentences);
}

// ─────────────────────────────────────────────────────────────────────────────
// COHERENCE NARRATIVE (Stage 35)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Build an evidence-anchored damage-physics coherence narrative.
 */
export function buildCoherenceNarrative(
  coherence: DamagePhysicsCoherenceResult
): NarrativeResult {
  const sentences: OECSentence[] = [];

  if (coherence.mismatches.length === 0) {
    sentences.push(oec(
      `All ${coherence.zones_checked} damage zone(s) are coherent with the computed impact direction`,
      `Stage 35 coherence engine — direction: ${coherence.direction_checked}, zones checked: ${coherence.zones_checked}`,
      "no physics-damage mismatch penalty applied"
    ));
    return buildResult(sentences);
  }

  // Mismatches
  for (const m of coherence.mismatches) {
    sentences.push(oec(
      `Physics-damage mismatch: ${m.actual_direction} impact recorded but ${m.zone} damage detected`,
      `Stage 35 coherence engine — severity: ${m.severity}, expected directions: ${m.expected_directions.join(", ")}`,
      m.severity === "high"
        ? "high-severity mismatch — fraud score increased and claim flagged for investigator review"
        : m.severity === "medium"
        ? "medium-severity mismatch — confidence score reduced and adjuster verification required"
        : "low-severity mismatch — confidence score reduced"
    ));
  }

  // Confidence impact
  sentences.push(oec(
    `Confidence score reduced by factor ${coherence.confidence_reduction_factor.toFixed(2)}`,
    `${coherence.mismatches.length} mismatch(es) detected — Stage 35 penalty schedule applied`,
    coherence.fraud_penalty_triggered
      ? "fraud penalty input triggered — claim forwarded to fraud engine for re-scoring"
      : "no fraud penalty triggered — confidence reduction applied only"
  ));

  return buildResult(sentences);
}

// ─────────────────────────────────────────────────────────────────────────────
// EVIDENCE STRENGTH NARRATIVE (Stage 38)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Build an evidence-anchored evidence quality narrative.
 */
export function buildEvidenceNarrative(bundle: EvidenceBundle): NarrativeResult {
  const sentences: OECSentence[] = [];

  sentences.push(oec(
    `Composite evidence strength: ${bundle.composite.evidence_label} (${(bundle.composite.evidence_strength * 100).toFixed(0)}%)`,
    `Stage 38 evidence scorer — damage: ${bundle.damage.evidence_label}, physics: ${bundle.physics.evidence_label}, fraud: ${bundle.fraud.evidence_label}, cost: ${bundle.cost.evidence_label}`,
    bundle.composite.evidence_label === "HIGH"
      ? "evidence quality is sufficient for automated decision processing"
      : bundle.composite.evidence_label === "MEDIUM"
      ? "evidence quality is partial — automated decision is subject to adjuster confirmation"
      : "evidence quality is insufficient for automated processing — manual review is required"
  ));

  if (bundle.composite.estimated) {
    sentences.push(oec(
      "One or more engine outputs are based on estimated or fallback data",
      "Stage 38 estimated flag = true",
      "conclusions drawn from estimated values carry reduced evidential weight"
    ));
  }

  // Flag any LOW engines
  const lowEngines = (["damage", "physics", "fraud", "cost", "reconstruction"] as const)
    .filter((e) => bundle[e].evidence_label === "LOW")
    .map((e) => `${e} (${(bundle[e].evidence_strength * 100).toFixed(0)}%)`);
  if (lowEngines.length > 0) {
    sentences.push(oec(
      `${lowEngines.length} engine(s) returned LOW evidence strength: ${fmtList(lowEngines)}`,
      "Stage 38 per-engine scoring",
      "outputs from these engines should not be used as sole basis for settlement decisions"
    ));
  }

  return buildResult(sentences);
}

// ─────────────────────────────────────────────────────────────────────────────
// COST REALISM NARRATIVE (Stage 36)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Build an evidence-anchored cost realism validation narrative.
 */
export function buildCostRealismNarrative(result: CostRealismResult): NarrativeResult {
  const sentences: OECSentence[] = [];

  if (!result.adjustments_applied) {
    sentences.push(oec(
      "Cost realism validation passed without adjustments",
      `Stage 36 — labour ratio: ${(result.labour_ratio * 100).toFixed(1)}%, parts alignment within tolerance`,
      "quoted cost structure is mechanically and economically realistic"
    ));
    return buildResult(sentences);
  }

  // Labour ratio issues
  const labourIssue = result.issues.find((i) => i.rule === "labour_ratio");
  if (labourIssue) {
    const labourAdj = result.adjustments.find((a) => a.rule === "labour_ratio");
    sentences.push(oec(
      `Labour ratio of ${(result.labour_ratio * 100).toFixed(1)}% is outside the 20–60% benchmark`,
      `Stage 36 labour gate — ${labourIssue.description}`,
      labourAdj
        ? `labour cost adjusted from ${fmtCents(labourAdj.original_value_cents)} to ${fmtCents(labourAdj.adjusted_value_cents)}`
        : "labour cost adjustment applied"
    ));
  }

  // Parts alignment issues
  const partsIssue = result.issues.find((i) => i.rule === "parts_alignment");
  if (partsIssue) {
    const partsAdj = result.adjustments.find((a) => a.rule === "parts_alignment");
    sentences.push(oec(
      "Parts cost deviates from component-count estimate",
      `Stage 36 parts gate — ${partsIssue.description}`,
      partsAdj
        ? `parts cost adjusted from ${fmtCents(partsAdj.original_value_cents)} to ${fmtCents(partsAdj.adjusted_value_cents)}`
        : "parts cost adjustment applied"
    ));
  }

  // Severity mismatch
  if (!result.severity_cost_consistent && result.severity_used) {
    sentences.push(oec(
      `Cost-severity mismatch detected for ${result.severity_used} severity`,
      `Stage 36 severity gate — total: ${fmtCents(result.validated_breakdown.total_cents)}`,
      "confidence score reduced; cost preserved for adjuster review"
    ));
  }

  return buildResult(sentences);
}
