CREATE TABLE `decision_snapshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`claim_id` varchar(50) NOT NULL,
	`tenant_id` varchar(50) NOT NULL,
	`snapshot_version` int NOT NULL DEFAULT 1,
	`created_at` bigint NOT NULL,
	`created_by_user_id` varchar(50),
	`verdict_decision` varchar(50) NOT NULL,
	`verdict_primary_reason` text NOT NULL,
	`verdict_confidence` int NOT NULL,
	`cost_ai_estimate` int NOT NULL,
	`cost_quoted` int NOT NULL DEFAULT 0,
	`cost_deviation_percent` int NOT NULL DEFAULT 0,
	`cost_fair_range_min` int NOT NULL,
	`cost_fair_range_max` int NOT NULL,
	`cost_verdict` varchar(20) NOT NULL,
	`fraud_score` int NOT NULL,
	`fraud_level` varchar(20) NOT NULL,
	`fraud_contributions_json` text NOT NULL,
	`physics_delta_v` int NOT NULL DEFAULT 0,
	`physics_velocity_range` varchar(50) NOT NULL DEFAULT '',
	`physics_energy_kj` int NOT NULL DEFAULT 0,
	`physics_force_kn` int NOT NULL DEFAULT 0,
	`physics_estimated` tinyint NOT NULL DEFAULT 0,
	`damage_zones_json` text NOT NULL,
	`damage_severity` varchar(30) NOT NULL,
	`damage_consistency_score` int NOT NULL DEFAULT 0,
	`enforcement_trace_json` text NOT NULL,
	`confidence_breakdown_json` text NOT NULL,
	`missing_fields_json` text NOT NULL,
	`estimated_fields_json` text NOT NULL,
	`extraction_confidence` int NOT NULL DEFAULT 0,
	`snapshot_json` text,
	`lifecycle_state` varchar(20) NOT NULL DEFAULT 'DRAFT',
	`is_final_snapshot` tinyint NOT NULL DEFAULT 0,
	CONSTRAINT `decision_snapshots_id` PRIMARY KEY(`id`)
);