CREATE TABLE `physics_validation_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`claim_id` varchar(50) NOT NULL,
	`assessment_id` int,
	`predicted_speed_kmh` decimal(6,2),
	`predicted_speed_low_kmh` decimal(6,2),
	`predicted_speed_high_kmh` decimal(6,2),
	`predicted_crush_depth_mm` decimal(7,2),
	`predicted_repair_cost_local` decimal(12,2),
	`predicted_delta_v_kmh` decimal(6,2),
	`uncertainty_grade` varchar(1),
	`integrity_score` int,
	`actual_speed_kmh` decimal(6,2),
	`actual_repair_cost_local` decimal(12,2),
	`actual_damage_zone` varchar(50),
	`actual_settlement_amount` decimal(12,2),
	`adjuster_override_reason` text,
	`speed_deviation_pct` decimal(7,3),
	`cost_deviation_pct` decimal(7,3),
	`speed_within_ci` tinyint,
	`calibration_feedback_json` json,
	`validation_status` varchar(30) NOT NULL DEFAULT 'pending',
	`validated_at` timestamp,
	`created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
	`updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `physics_validation_records_id` PRIMARY KEY(`id`)
);