CREATE TABLE `quote_line_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`quote_id` int NOT NULL,
	`item_number` int,
	`description` varchar(500) NOT NULL,
	`part_number` varchar(100),
	`category` enum('parts','labor','paint','diagnostic','sundries','other') NOT NULL,
	`quantity` decimal(10,2) NOT NULL,
	`unit_price` decimal(10,2) NOT NULL,
	`line_total` decimal(10,2) NOT NULL,
	`currency` varchar(10) NOT NULL DEFAULT 'USD',
	`vat_rate` decimal(5,2) DEFAULT '15.00',
	`vat_amount` decimal(10,2),
	`total_with_vat` decimal(10,2),
	`is_repair` tinyint DEFAULT 0,
	`is_replacement` tinyint DEFAULT 1,
	`betterment_amount` decimal(10,2),
	`net_cost` decimal(10,2),
	`is_price_inflated` tinyint DEFAULT 0,
	`is_unrelated_damage` tinyint DEFAULT 0,
	`is_missing_in_other_quotes` tinyint DEFAULT 0,
	`notes` text,
	`ai_review` varchar(50),
	`part_origin` enum('oem','aftermarket','reconditioned','used','unknown') DEFAULT 'unknown',
	`repairer_name` varchar(255),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `quote_line_items_id` PRIMARY KEY(`id`)
);