CREATE TABLE `service_quotes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`request_id` int NOT NULL,
	`provider_id` int NOT NULL,
	`tenant_id` varchar(64),
	`quoted_amount` int NOT NULL,
	`labor_cost` int,
	`parts_cost` int,
	`additional_costs` int,
	`estimated_duration` int,
	`availability_date` timestamp,
	`completion_date` timestamp,
	`quote_line_items` text,
	`parts_required` text,
	`provider_name` varchar(255) NOT NULL,
	`provider_location` varchar(255),
	`provider_rating` decimal(3,2),
	`provider_completed_jobs` int,
	`ai_cost_score` int,
	`cost_deviation_percent` decimal(5,2),
	`recommendation_score` int,
	`status` enum('pending','accepted','rejected','expired') DEFAULT 'pending',
	`valid_until` timestamp,
	`submitted_at` timestamp NOT NULL DEFAULT (now()),
	`accepted_at` timestamp,
	CONSTRAINT `service_quotes_id` PRIMARY KEY(`id`)
);