CREATE TABLE `fleet_audit_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenant_id` varchar(64),
	`entity_type` enum('fleet','vehicle','maintenance','service_request','quote','document') NOT NULL,
	`entity_id` int NOT NULL,
	`action` enum('create','update','delete','view','export') NOT NULL,
	`user_id` int NOT NULL,
	`user_name` varchar(255),
	`changes_before` text,
	`changes_after` text,
	`ip_address` varchar(45),
	`user_agent` text,
	`timestamp` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `fleet_audit_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fleet_documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fleet_id` int,
	`vehicle_id` int,
	`tenant_id` varchar(64),
	`document_type` enum('registration_book','ownership_certificate','inspection_report','insurance_policy','service_history','photo','valuation_report','other') NOT NULL,
	`document_name` varchar(255) NOT NULL,
	`s3_key` varchar(500) NOT NULL,
	`s3_url` text NOT NULL,
	`file_size` int,
	`mime_type` varchar(100),
	`verification_status` enum('pending','verified','rejected') DEFAULT 'pending',
	`verified_by` int,
	`verified_at` timestamp,
	`rejection_reason` text,
	`uploaded_by` int NOT NULL,
	`uploaded_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `fleet_documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fleet_risk_scores` (
	`id` int AUTO_INCREMENT NOT NULL,
	`vehicle_id` int NOT NULL,
	`fleet_id` int,
	`tenant_id` varchar(64),
	`overall_risk_score` int NOT NULL,
	`maintenance_risk` int,
	`claims_risk` int,
	`vehicle_age_risk` int,
	`usage_risk` int,
	`repair_cost_risk` int,
	`risk_factors` text,
	`premium_impact` enum('decrease','neutral','increase'),
	`recommended_premium_adjustment` decimal(5,2),
	`calculated_at` timestamp NOT NULL DEFAULT (now()),
	`next_review_date` timestamp,
	CONSTRAINT `fleet_risk_scores_id` PRIMARY KEY(`id`),
	CONSTRAINT `fleet_risk_scores_vehicle_id_unique` UNIQUE(`vehicle_id`)
);
--> statement-breakpoint
CREATE TABLE `fleets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`owner_id` int NOT NULL,
	`tenant_id` varchar(64),
	`fleet_name` varchar(255) NOT NULL,
	`fleet_type` enum('mining','logistics','corporate','rental','public_transport','agriculture','construction') NOT NULL,
	`total_vehicles` int DEFAULT 0,
	`active_vehicles` int DEFAULT 0,
	`description` text,
	`primary_location` varchar(255),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fleets_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `maintenance_alerts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`vehicle_id` int NOT NULL,
	`schedule_id` int,
	`tenant_id` varchar(64),
	`alert_type` enum('upcoming_maintenance','overdue_maintenance','inspection_due','safety_alert','compliance_alert') NOT NULL,
	`severity` enum('low','medium','high','critical') NOT NULL,
	`title` varchar(255) NOT NULL,
	`message` text NOT NULL,
	`due_date` timestamp,
	`due_mileage` int,
	`status` enum('pending','acknowledged','resolved','dismissed') DEFAULT 'pending',
	`acknowledged_by` int,
	`acknowledged_at` timestamp,
	`resolved_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `maintenance_alerts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `maintenance_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`vehicle_id` int NOT NULL,
	`schedule_id` int,
	`tenant_id` varchar(64),
	`service_date` timestamp NOT NULL,
	`service_mileage` int,
	`service_type` varchar(255) NOT NULL,
	`service_provider` varchar(255),
	`service_location` varchar(255),
	`labor_cost` int,
	`parts_cost` int,
	`total_cost` int,
	`service_items` text,
	`parts_replaced` text,
	`invoice_url` text,
	`service_report_url` text,
	`is_compliant` tinyint DEFAULT 1,
	`was_overdue` tinyint DEFAULT 0,
	`days_overdue` int,
	`performed_by` int,
	`recorded_by` int NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `maintenance_records_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `maintenance_schedules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`vehicle_id` int NOT NULL,
	`tenant_id` varchar(64),
	`maintenance_type` enum('oil_change','tire_rotation','brake_inspection','engine_service','transmission_service','annual_inspection','safety_inspection','filter_replacement','battery_check','coolant_flush','custom') NOT NULL,
	`description` text,
	`interval_type` enum('mileage','time','both') NOT NULL,
	`mileage_interval` int,
	`time_interval` int,
	`last_service_date` timestamp,
	`last_service_mileage` int,
	`next_due_date` timestamp,
	`next_due_mileage` int,
	`alert_days_before` int DEFAULT 7,
	`alert_mileage_before` int DEFAULT 500,
	`is_active` tinyint DEFAULT 1,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `maintenance_schedules_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `service_providers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`provider_name` varchar(255) NOT NULL,
	`provider_type` enum('panel_beater','mechanic','dealership','specialist') NOT NULL,
	`contact_person` varchar(255),
	`email` varchar(320),
	`phone` varchar(20),
	`address` text,
	`city` varchar(100),
	`region` varchar(100),
	`specializations` text,
	`certifications` text,
	`average_rating` decimal(3,2),
	`total_jobs_completed` int DEFAULT 0,
	`average_completion_time` decimal(6,2),
	`average_cost_deviation` decimal(5,2),
	`on_time_completion_rate` decimal(5,2),
	`is_active` tinyint DEFAULT 1,
	`is_verified` tinyint DEFAULT 0,
	`verified_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `service_providers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `service_quotes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`request_id` int NOT NULL,
	`provider_id` int NOT NULL,
	`tenant_id` varchar(64),
	`quoted_amount` int NOT NULL,
	`labor_cost` int,
	`parts_cost` int,
	`additional_costs` int,
	`estimated_duration` int,
	`availability_date` timestamp,
	`completion_date` timestamp,
	`quote_line_items` text,
	`parts_required` text,
	`provider_name` varchar(255) NOT NULL,
	`provider_location` varchar(255),
	`provider_rating` decimal(3,2),
	`provider_completed_jobs` int,
	`ai_cost_score` int,
	`cost_deviation_percent` decimal(5,2),
	`recommendation_score` int,
	`status` enum('pending','accepted','rejected','expired') DEFAULT 'pending',
	`valid_until` timestamp,
	`submitted_at` timestamp NOT NULL DEFAULT (now()),
	`accepted_at` timestamp,
	CONSTRAINT `service_quotes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `service_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`vehicle_id` int NOT NULL,
	`fleet_id` int,
	`owner_id` int NOT NULL,
	`tenant_id` varchar(64),
	`request_type` enum('maintenance','repair','inspection','emergency') NOT NULL,
	`service_category` enum('engine','transmission','brakes','suspension','electrical','bodywork','tires','hvac','general') NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text NOT NULL,
	`urgency` enum('low','medium','high','critical') DEFAULT 'medium',
	`current_mileage` int,
	`problem_images` text,
	`diagnostic_codes` text,
	`status` enum('open','quotes_received','quote_accepted','in_progress','completed','cancelled') DEFAULT 'open',
	`quotes_received` int DEFAULT 0,
	`selected_quote_id` int,
	`selected_provider_id` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`completed_at` timestamp,
	CONSTRAINT `service_requests_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `vehicle_mileage_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`vehicle_id` int NOT NULL,
	`tenant_id` varchar(64),
	`mileage` int NOT NULL,
	`recorded_date` timestamp NOT NULL,
	`recorded_by` int NOT NULL,
	`record_type` enum('manual','service','inspection','claim','automated') DEFAULT 'manual',
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `vehicle_mileage_logs_id` PRIMARY KEY(`id`)
);
