CREATE TABLE `claim_review_queue` (
	`id` int AUTO_INCREMENT NOT NULL,
	`historical_claim_id` int NOT NULL,
	`tenant_id` varchar(64),
	`review_status` enum('pending_review','in_review','approved','rejected','needs_more_info') DEFAULT 'pending_review',
	`review_priority` enum('low','medium','high') DEFAULT 'medium',
	`routed_reason` varchar(255),
	`automated_validation_level` varchar(50),
	`assigned_to` int,
	`assigned_at` timestamp,
	`reviewed_by` int,
	`reviewed_at` timestamp,
	`review_decision` enum('approve','reject','request_more_info'),
	`review_notes` text,
	`include_in_training_dataset` tinyint DEFAULT 0,
	`include_in_reference_dataset` tinyint DEFAULT 1,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `claim_review_queue_id` PRIMARY KEY(`id`),
	CONSTRAINT `claim_review_queue_historical_claim_id_unique` UNIQUE(`historical_claim_id`)
);
--> statement-breakpoint
CREATE TABLE `model_training_audit_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenant_id` varchar(64),
	`model_version_id` int NOT NULL,
	`event_type` enum('training_started','training_completed','training_failed','validation_started','validation_completed','deployment_requested','deployment_approved','deployment_rejected','model_deprecated','dataset_added','dataset_removed') NOT NULL,
	`event_description` text,
	`event_metadata` text,
	`performed_by` int,
	`performed_at` timestamp NOT NULL DEFAULT (now()),
	`ip_address` varchar(45),
	CONSTRAINT `model_training_audit_log_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `model_version_registry` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenant_id` varchar(64),
	`model_name` varchar(255) NOT NULL,
	`model_version` varchar(50) NOT NULL,
	`model_type` varchar(100),
	`algorithm_used` varchar(100),
	`training_dataset_version` varchar(50),
	`training_claim_count` int,
	`training_started_at` timestamp,
	`training_completed_at` timestamp,
	`training_duration` int,
	`accuracy_score` decimal(5,2),
	`precision_score` decimal(5,2),
	`recall_score` decimal(5,2),
	`f1_score` decimal(5,2),
	`bias_drift_validation` varchar(50),
	`fraud_detection_stability` varchar(50),
	`performance_benchmark` text,
	`deployment_status` enum('training','validation','staging','production','deprecated','archived') DEFAULT 'training',
	`deployed_at` timestamp,
	`deployed_by` int,
	`approval_status` enum('pending_validation','pending_approval','approved','rejected') DEFAULT 'pending_validation',
	`approved_by` int,
	`approved_at` timestamp,
	`approval_notes` text,
	`model_artifact_url` text,
	`model_config_url` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `model_version_registry_id` PRIMARY KEY(`id`),
	CONSTRAINT `model_version_registry_model_version_unique` UNIQUE(`model_version`)
);
--> statement-breakpoint
CREATE TABLE `reference_dataset` (
	`id` int AUTO_INCREMENT NOT NULL,
	`historical_claim_id` int NOT NULL,
	`tenant_id` varchar(64),
	`dataset_version` varchar(50) NOT NULL,
	`included_at` timestamp NOT NULL DEFAULT (now()),
	`used_for_benchmarking` tinyint DEFAULT 0,
	`used_for_analytics` tinyint DEFAULT 0,
	`last_accessed_at` timestamp,
	`reference_purpose` text,
	CONSTRAINT `reference_dataset_id` PRIMARY KEY(`id`),
	CONSTRAINT `reference_dataset_historical_claim_id_unique` UNIQUE(`historical_claim_id`)
);
--> statement-breakpoint
CREATE TABLE `training_data_scores` (
	`id` int AUTO_INCREMENT NOT NULL,
	`historical_claim_id` int NOT NULL,
	`tenant_id` varchar(64),
	`training_confidence_score` decimal(5,2) NOT NULL,
	`training_confidence_category` enum('HIGH','MEDIUM','LOW') NOT NULL,
	`assessor_report_score` decimal(5,2) DEFAULT '0.00',
	`supporting_photos_score` decimal(5,2) DEFAULT '0.00',
	`panel_beater_quotes_score` decimal(5,2) DEFAULT '0.00',
	`evidence_completeness_score` decimal(5,2) DEFAULT '0.00',
	`handwritten_adjustments_score` decimal(5,2) DEFAULT '0.00',
	`fraud_markers_score` decimal(5,2) DEFAULT '0.00',
	`dispute_history_score` decimal(5,2) DEFAULT '0.00',
	`competing_quotes_score` decimal(5,2) DEFAULT '0.00',
	`scoring_algorithm_version` varchar(20),
	`scoring_notes` text,
	`anomaly_detected` tinyint DEFAULT 0,
	`anomaly_reason` text,
	`bias_risk_detected` tinyint DEFAULT 0,
	`bias_risk_reason` text,
	`scored_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `training_data_scores_id` PRIMARY KEY(`id`),
	CONSTRAINT `training_data_scores_historical_claim_id_unique` UNIQUE(`historical_claim_id`)
);
--> statement-breakpoint
CREATE TABLE `training_dataset` (
	`id` int AUTO_INCREMENT NOT NULL,
	`historical_claim_id` int NOT NULL,
	`tenant_id` varchar(64),
	`dataset_version` varchar(50) NOT NULL,
	`included_at` timestamp NOT NULL DEFAULT (now()),
	`included_by` int NOT NULL,
	`inclusion_reason` text,
	`used_in_model_versions` text,
	`last_used_for_training` timestamp,
	`is_active` tinyint DEFAULT 1,
	`deactivated_at` timestamp,
	`deactivation_reason` text,
	CONSTRAINT `training_dataset_id` PRIMARY KEY(`id`),
	CONSTRAINT `training_dataset_historical_claim_id_unique` UNIQUE(`historical_claim_id`)
);
