CREATE TABLE `agency_documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenant_id` varchar(255),
	`quotation_request_id` int,
	`policy_id` int,
	`document_type` enum('id_document','drivers_license','vehicle_registration','proof_of_address','bank_statement','vehicle_photos','previous_policy','claims_history','other') NOT NULL,
	`title` varchar(255) NOT NULL,
	`file_name` varchar(255) NOT NULL,
	`file_url` text NOT NULL,
	`file_size` int,
	`mime_type` varchar(100),
	`uploaded_by` int NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `agency_documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `quotation_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`request_number` varchar(50) NOT NULL,
	`tenant_id` varchar(255),
	`user_id` int,
	`full_name` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50),
	`id_number` varchar(20),
	`insurance_type` enum('comprehensive','third_party','third_party_fire_theft','fleet','commercial') NOT NULL,
	`vehicle_make` varchar(100) NOT NULL,
	`vehicle_model` varchar(100) NOT NULL,
	`vehicle_year` int NOT NULL,
	`vehicle_registration` varchar(50),
	`vehicle_vin` varchar(50),
	`vehicle_value` int,
	`vehicle_usage` enum('private','business','both') DEFAULT 'private',
	`driver_age` int,
	`driver_license_years` int,
	`claims_history` int DEFAULT 0,
	`excess_amount` int,
	`additional_cover` text,
	`documents` text,
	`quoted_premium` int,
	`quoted_annual_premium` int,
	`quoted_excess` int,
	`quote_valid_until` timestamp,
	`quote_notes` text,
	`status` enum('pending','under_review','quoted','accepted','rejected','expired') NOT NULL DEFAULT 'pending',
	`assigned_agent_id` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `quotation_requests_id` PRIMARY KEY(`id`),
	CONSTRAINT `quotation_requests_request_number_unique` UNIQUE(`request_number`)
);
