CREATE TABLE `fleet_vehicles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`vin` varchar(17),
	`registration_number` varchar(50) NOT NULL,
	`make` varchar(100) NOT NULL,
	`model` varchar(100) NOT NULL,
	`year` int NOT NULL,
	`color` varchar(50),
	`engine_number` varchar(100),
	`chassis_number` varchar(100),
	`current_valuation` int,
	`valuation_date` timestamp,
	`valuation_source` varchar(100),
	`maintenance_score` int,
	`risk_score` int,
	`claims_history_count` int DEFAULT 0,
	`owner_id` int NOT NULL,
	`vehicle_images` text,
	`registration_book_url` varchar(500),
	`registration_book_s3_key` varchar(500),
	`tenant_id` varchar(255),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`fleet_id` int,
	`engine_capacity` int,
	`vehicle_mass` int,
	`fuel_type` enum('petrol','diesel','electric','hybrid'),
	`transmission_type` enum('manual','automatic'),
	`usage_type` enum('private','commercial','logistics','mining','agriculture','public_transport'),
	`primary_use` text,
	`average_monthly_mileage` int,
	`current_insurer` varchar(255),
	`policy_number` varchar(100),
	`policy_start_date` timestamp,
	`policy_end_date` timestamp,
	`coverage_type` enum('comprehensive','third_party','third_party_fire_theft'),
	`purchase_price` int,
	`purchase_date` timestamp,
	`replacement_value` int,
	`status` enum('active','inactive','sold','written_off','under_repair') DEFAULT 'active',
	`last_inspection_date` timestamp,
	`next_inspection_due` timestamp,
	`maintenance_compliance_score` int,
	`vehicle_origin` enum('Local_Assembly','Ex_Japanese','Ex_European','Ex_American','Ex_Chinese','Unknown') DEFAULT 'Unknown',
	`imported_from` varchar(100),
	`import_year` int,
	CONSTRAINT `fleet_vehicles_id` PRIMARY KEY(`id`)
);