CREATE TABLE `panel_beaters` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` text NOT NULL,
	`business_name` text NOT NULL,
	`email` varchar(320),
	`phone` varchar(20),
	`address` text,
	`city` varchar(100),
	`approved` tinyint NOT NULL DEFAULT 1,
	`panel_beater_status` enum('pending','approved','suspended','rejected') NOT NULL DEFAULT 'approved',
	`user_id` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`tenant_id` varchar(255),
	`total_repairs` int NOT NULL DEFAULT 0,
	`avg_quality_score` decimal(5,2),
	`avg_cost_ratio` decimal(6,3),
	`avg_repair_duration_days` decimal(6,1),
	`repeat_damage_rate_pct` decimal(5,2),
	`warranty_repair_count` int NOT NULL DEFAULT 0,
	`fraud_flag_count` int NOT NULL DEFAULT 0,
	`performance_tier` varchar(20),
	`last_repair_date` varchar(20),
	`performance_updated_at` timestamp,
	CONSTRAINT `panel_beaters_id` PRIMARY KEY(`id`)
);