CREATE TABLE `agency_insurance_service_requests` (
  `id` int NOT NULL AUTO_INCREMENT,
  `request_number` varchar(50) NOT NULL,
  `agency_tenant_id` varchar(64) NOT NULL,
  `agency_client_id` int NOT NULL,
  `vehicle_registry_id` int NULL,
  `cover_type` enum('comprehensive','third_party','third_party_fire_theft','commercial','other') NOT NULL,
  `status` enum('draft','awaiting_client_acknowledgement','ready_for_insurer_review','under_insurer_review','closed','withdrawn') NOT NULL DEFAULT 'draft',
  `client_instruction` text NOT NULL,
  `vehicle_risk_notes` text NULL,
  `vehicle_registration` varchar(50) NULL,
  `vehicle_make` varchar(100) NULL,
  `vehicle_model` varchar(100) NULL,
  `vehicle_year` int NULL,
  `vehicle_vin` varchar(50) NULL,
  `vehicle_mileage_km` int NULL,
  `client_proposed_value_cents` int NULL,
  `kinga_market_valuation_cents` int NULL,
  `valuation_date` timestamp NULL,
  `valuation_provenance_json` json NULL,
  `variance_percent` decimal(7,2) NULL,
  `client_acknowledgement_json` json NULL,
  `created_by` int NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_agency_insurance_service_request_number` (`request_number`),
  KEY `idx_agency_insurance_service_request_tenant_status` (`agency_tenant_id`,`status`),
  KEY `idx_agency_insurance_service_request_client` (`agency_client_id`),
  KEY `idx_agency_insurance_service_request_vehicle` (`vehicle_registry_id`)
);

CREATE TABLE `agency_insurance_service_request_insurers` (
  `id` int NOT NULL AUTO_INCREMENT,
  `service_request_id` int NOT NULL,
  `agency_tenant_id` varchar(64) NOT NULL,
  `insurer_tenant_id` varchar(64) NOT NULL,
  `status` enum('invited','viewed','responded','withdrawn') NOT NULL DEFAULT 'invited',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_agency_service_request_insurer` (`service_request_id`,`insurer_tenant_id`),
  KEY `idx_agency_service_request_insurer_tenant` (`insurer_tenant_id`,`status`)
);

CREATE TABLE `agency_insurance_valuation_deviations` (
  `id` int NOT NULL AUTO_INCREMENT,
  `service_request_id` int NOT NULL,
  `agency_tenant_id` varchar(64) NOT NULL,
  `client_proposed_value_cents` int NOT NULL,
  `kinga_market_valuation_cents` int NOT NULL,
  `variance_percent` decimal(7,2) NOT NULL,
  `acknowledgement_json` json NOT NULL,
  `recorded_by` int NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_agency_insurance_valuation_deviation_request` (`service_request_id`),
  KEY `idx_agency_insurance_valuation_deviation_tenant` (`agency_tenant_id`)
);

CREATE TABLE `vehicle_condition_snapshots` (
  `id` int NOT NULL AUTO_INCREMENT,
  `vehicle_registry_id` int NOT NULL,
  `insurance_service_request_id` int NOT NULL,
  `vehicle_market_valuation_id` int NULL,
  `snapshot_version` int NOT NULL,
  `snapshot_date` timestamp NOT NULL,
  `exterior_condition` varchar(50) NOT NULL,
  `interior_condition` varchar(50) NOT NULL,
  `mechanical_condition` varchar(50) NOT NULL,
  `existing_damage_notes` text NULL,
  `tyre_condition` varchar(50) NULL,
  `glass_condition` varchar(50) NULL,
  `odometer_km` int NULL,
  `modifications_json` json NULL,
  `photographs_json` json NULL,
  `evidence_sources_json` json NOT NULL,
  `observations` text NULL,
  `assessor_notes` text NULL,
  `captured_by` int NOT NULL,
  `tenant_id` varchar(64) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_vehicle_condition_snapshot_version` (`insurance_service_request_id`,`snapshot_version`),
  KEY `idx_vehicle_condition_snapshot_vehicle_date` (`vehicle_registry_id`,`snapshot_date`),
  KEY `idx_vehicle_condition_snapshot_tenant_vehicle` (`tenant_id`,`vehicle_registry_id`)
);

CREATE TABLE `agency_assisted_claimant_identities` (
  `id` int NOT NULL AUTO_INCREMENT,
  `agency_tenant_id` varchar(64) NOT NULL,
  `agency_client_id` int NOT NULL,
  `insurer_tenant_id` varchar(64) NOT NULL,
  `restricted_claimant_user_id` int NOT NULL,
  `verified_claimant_user_id` int NULL,
  `status` enum('restricted','linked_to_verified_claimant') NOT NULL DEFAULT 'restricted',
  `created_by` int NOT NULL,
  `linked_by` int NULL,
  `linked_at` timestamp NULL,
  `link_confirmation_statement` text NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_agency_assisted_claimant_identity` (`agency_tenant_id`,`agency_client_id`,`insurer_tenant_id`),
  KEY `idx_agency_assisted_claimant_insurer` (`insurer_tenant_id`,`status`)
);
