CREATE TABLE IF NOT EXISTS claim_evidence_findings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tenant_id VARCHAR(255) NOT NULL,
  claim_id INT NOT NULL,
  assessment_id INT NULL,
  evidence_domain ENUM('monetary','damage','fraud','vehicle_history','decision') NOT NULL,
  evidence_status ENUM('verified','reconstructed','documented_revision','scope_difference','extraction_defect','evidence_gap','pricing_variance_review_signal','unresolved') NOT NULL,
  severity ENUM('info','review','blocking') NOT NULL DEFAULT 'info',
  finding_code VARCHAR(100) NOT NULL,
  title VARCHAR(500) NOT NULL,
  summary TEXT NULL,
  source_document_id INT NULL,
  source_page INT NULL,
  source_location VARCHAR(512) NULL,
  source_type ENUM('document','quote_line','image','system_record','benchmark','reconstruction') NOT NULL,
  quote_id INT NULL,
  quote_line_item_id INT NULL,
  subject_key VARCHAR(255) NULL,
  observed_value_cents BIGINT UNSIGNED NULL,
  comparison_value_cents BIGINT UNSIGNED NULL,
  currency VARCHAR(10) NULL,
  tax_basis ENUM('included','excluded','separately_stated','not_stated','not_applicable') NULL,
  scope_fingerprint VARCHAR(128) NULL,
  evidence_json JSON NULL,
  reviewed_by_user_id INT NULL,
  reviewed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY claim_evidence_findings_tenant_claim_idx (tenant_id, claim_id),
  KEY claim_evidence_findings_quote_idx (quote_id, quote_line_item_id),
  KEY claim_evidence_findings_status_idx (evidence_status, severity)
);

CREATE TABLE IF NOT EXISTS quote_evidence_ledger (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tenant_id VARCHAR(255) NOT NULL,
  claim_id INT NOT NULL,
  quote_id INT NULL,
  quote_line_item_id INT NULL,
  source_document_id INT NOT NULL,
  source_page INT NULL,
  source_location VARCHAR(512) NULL,
  source_row_label VARCHAR(500) NULL,
  source_text TEXT NULL,
  description VARCHAR(500) NOT NULL,
  canonical_component VARCHAR(255) NULL,
  financial_role ENUM('quote_total','subtotal','vat','parts','labour','paint','sundries','component','discount','fee','other') NOT NULL,
  amount_cents BIGINT UNSIGNED NOT NULL,
  currency VARCHAR(10) NOT NULL,
  tax_basis ENUM('included','excluded','separately_stated','not_stated','not_applicable') NOT NULL,
  scope_fingerprint VARCHAR(128) NULL,
  revision_status ENUM('original','revised','superseded','unknown') NOT NULL DEFAULT 'original',
  extraction_method ENUM('document_direct','ocr','vision','human_verified','system_reconstruction') NOT NULL,
  extraction_confidence DECIMAL(5,4) NULL,
  evidence_status ENUM('verified','reconstructed','documented_revision','scope_difference','extraction_defect','evidence_gap','pricing_variance_review_signal','unresolved') NOT NULL,
  verification_note TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY quote_evidence_ledger_tenant_claim_idx (tenant_id, claim_id),
  KEY quote_evidence_ledger_quote_idx (quote_id, quote_line_item_id),
  KEY quote_evidence_ledger_source_idx (source_document_id, source_page),
  KEY quote_evidence_ledger_scope_status_idx (scope_fingerprint, evidence_status)
);
