CREATE TABLE IF NOT EXISTS quote_evidence_gaps (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tenant_id VARCHAR(255) NOT NULL,
  claim_id INT NOT NULL,
  quote_id INT NULL,
  quote_line_item_id INT NULL,
  source_document_id INT NOT NULL,
  source_page INT NULL,
  source_location VARCHAR(512) NULL,
  source_crop_ref VARCHAR(1024) NULL,
  source_text TEXT NULL,
  observable_characters TEXT NULL,
  ambiguity_description TEXT NOT NULL,
  component_confidence DECIMAL(5,4) NULL,
  quantity_confidence DECIMAL(5,4) NULL,
  unit_price_confidence DECIMAL(5,4) NULL,
  extended_amount_confidence DECIMAL(5,4) NULL,
  transcription_method ENUM('document_direct','ocr','vision','human_verified') NOT NULL,
  candidate_readings_json JSON NULL,
  arithmetic_residual_cents BIGINT NULL,
  currency VARCHAR(10) NULL,
  impact_json JSON NULL,
  resolution_status ENUM('open','human_verification_requested','human_verified','superseded','not_resolvable_from_source') NOT NULL DEFAULT 'open',
  review_fields_json JSON NULL,
  reviewed_by_user_id INT NULL,
  reviewed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY quote_evidence_gaps_tenant_claim_idx (tenant_id, claim_id),
  KEY quote_evidence_gaps_quote_idx (quote_id, quote_line_item_id),
  KEY quote_evidence_gaps_source_idx (source_document_id, source_page),
  KEY quote_evidence_gaps_resolution_idx (resolution_status)
);
