// @ts-nocheck
/**
 * Enterprise-Grade Final Claim Report PDF Generator
 * 
 * Generates board-ready PDF reports for completed claims with:
 * - Professional header with insurer logo
 * - Executive summary with financial comparison
 * - Risk analysis with fraud assessment
 * - Workflow audit summary with timeline
 * - Branded footer with KINGA platform branding
 * 
 * Designed for deterministic, reproducible output suitable for board review.
 */

import { writeFile, unlink } from "fs/promises";
import path from "path";
import puppeteer from "puppeteer-core";

export interface FinalClaimReportData {
  // Claim Information
  claimId: number;
  claimNumber: string;
  policyHolder: string;
  policyNumber: string;
  vehicleMake: string;
  vehicleModel: string;
  vehicleYear: number;
  vehicleRegistration: string;
  incidentDate: Date;
  
  // Financial Summary
  finalApprovedAmount: number; // in cents
  aiEstimatedCost: number; // in cents
  assessorEstimatedCost: number; // in cents
  selectedPanelBeater: {
    name: string;
    quotedAmount: number; // in cents
  };
  
  // Risk Analysis
  aiConfidenceScore: number; // 0-100
  fraudRiskLevel: "low" | "medium" | "high";
  fraudRiskScore: number; // 0-100
  discrepancyExplanation: string;
  
  // Executive Override (if applicable)
  executiveOverride?: {
    overriddenBy: string;
    overriddenByRole: string;
    justification: string;
    overriddenAt: Date;
    originalDecision: string;
    newDecision: string;
  };
  
  // Workflow Audit
  workflowTimeline: Array<{
    stage: string;
    startedAt: Date;
    completedAt: Date;
    durationMinutes: number;
    handledBy: string;
  }>;
  totalProcessingTimeMinutes: number;
  segregationCompliant: boolean;
  segregationViolations: string[];
  
  // Currency
  currencyCode?: string; // e.g. "USD", "ZIG", "ZAR" — defaults to "USD"

  // Insurer Branding
  insurerLogo?: string; // URL or base64 data URL
  insurerName: string;
  
  // Report Metadata
  generatedAt: Date;
  reportVersion: string;
}

/**
 * Generate enterprise-grade final claim report PDF
 */
export async function generateFinalClaimReportPDF(
  data: FinalClaimReportData
): Promise<Buffer> {
  const htmlContent = generateFinalReportHTML(data);
  
  const tempHtmlPath = path.join("/tmp", `final-claim-report-${data.claimNumber}-${Date.now()}.html`);
  
  try {
    await writeFile(tempHtmlPath, htmlContent, "utf-8");
    
    let browser;
    try {
      browser = await puppeteer.launch({
        executablePath: '/usr/bin/chromium-browser',
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage', '--disable-gpu'],
      });
      
      const page = await browser.newPage();
      await page.goto(`file://${tempHtmlPath}`, { waitUntil: 'networkidle0', timeout: 30000 });
      
      const pdfBuffer = Buffer.from(await page.pdf({
        format: 'A4',
        printBackground: true,
        margin: { top: '20mm', bottom: '20mm', left: '15mm', right: '15mm' },
        displayHeaderFooter: true,
        headerTemplate: '<div></div>', // Empty header
        footerTemplate: `
          <div style="width: 100%; font-size: 9px; color: #6b7280; text-align: center; padding: 0 15mm;">
            <span>Generated by KINGA Intelligence Platform | Version ${data.reportVersion} | ${new Date(data.generatedAt).toLocaleString('en-US', { timeZone: 'UTC', hour12: false })} UTC</span>
            <span style="float: right;">Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
          </div>
        `,
      }));
      
      await unlink(tempHtmlPath).catch(() => {});
      
      return pdfBuffer;
    } finally {
      if (browser) await browser.close();
    }
  } catch (error) {
    try {
      await unlink(tempHtmlPath).catch(() => {});
    } catch {}
    throw error;
  }
}

/**
 * Generate HTML content for the final claim report
 */
function generateFinalReportHTML(data: FinalClaimReportData): string {
  const currencyCode = data.currencyCode ?? 'USD';
  const currencySymbol = currencyCode === 'ZAR' ? 'R' : currencyCode === 'ZIG' ? 'ZIG ' : 'US$';
  const formatCurrency = (cents: number) => {
    return `${currencySymbol}${(cents / 100).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  };
  
  const formatDate = (date: Date) => {
    return new Date(date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  };
  
  const formatDateTime = (date: Date) => {
    return new Date(date).toLocaleString('en-US', { 
      year: 'numeric', 
      month: 'short', 
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };
  
  const calculateVariance = (amount1: number, amount2: number) => {
    if (amount2 === 0) return 0;
    return ((amount1 - amount2) / amount2) * 100;
  };
  
  const aiVsAssessorVariance = calculateVariance(data.assessorEstimatedCost, data.aiEstimatedCost);
  const approvedVsAiVariance = calculateVariance(data.finalApprovedAmount, data.aiEstimatedCost);
  const approvedVsAssessorVariance = calculateVariance(data.finalApprovedAmount, data.assessorEstimatedCost);
  
  const getFraudRiskColor = (level: string) => {
    switch (level) {
      case "low": return "#10b981";
      case "medium": return "#f59e0b";
      case "high": return "#ef4444";
      default: return "#6b7280";
    }
  };
  
  const getVarianceColor = (variance: number) => {
    const absVariance = Math.abs(variance);
    if (absVariance < 10) return "#10b981"; // Green
    if (absVariance < 20) return "#f59e0b"; // Amber
    return "#ef4444"; // Red
  };
  
  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Final Claim Report - ${data.claimNumber}</title>
  <style>
    @page {
      size: A4;
      margin: 20mm 15mm;
    }
    
    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }
    
    body {
      font-family: 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;
      font-size: 10pt;
      line-height: 1.5;
      color: #1f2937;
      background: white;
    }
    
    .container {
      max-width: 100%;
    }
    
    /* Header Section */
    .report-header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      padding-bottom: 20px;
      border-bottom: 3px solid #2563eb;
      margin-bottom: 30px;
    }
    
    .header-left {
      flex: 1;
    }
    
    .header-right {
      text-align: right;
      flex-shrink: 0;
    }
    
    .insurer-logo {
      max-width: 150px;
      max-height: 60px;
      object-fit: contain;
    }
    
    .report-title {
      font-size: 20pt;
      font-weight: 700;
      color: #1e40af;
      margin-bottom: 8px;
    }
    
    .report-subtitle {
      font-size: 11pt;
      color: #6b7280;
      margin-bottom: 15px;
    }
    
    .header-meta {
      display: grid;
      grid-template-columns: auto 1fr;
      gap: 8px 15px;
      font-size: 9pt;
    }
    
    .header-meta-label {
      font-weight: 600;
      color: #374151;
    }
    
    .header-meta-value {
      color: #1f2937;
    }
    
    .confidence-badge {
      display: inline-block;
      padding: 6px 12px;
      background: linear-gradient(135deg, #3b82f6 0%, #2563eb 100%);
      color: white;
      border-radius: 6px;
      font-weight: 700;
      font-size: 14pt;
      margin-top: 10px;
    }
    
    /* Section Styles */
    .section {
      margin-bottom: 30px;
      page-break-inside: avoid;
    }
    
    .section-title {
      font-size: 14pt;
      font-weight: 700;
      color: #1e40af;
      border-bottom: 2px solid #93c5fd;
      padding-bottom: 8px;
      margin-bottom: 15px;
    }
    
    .section-subtitle {
      font-size: 11pt;
      font-weight: 600;
      color: #374151;
      margin-top: 15px;
      margin-bottom: 10px;
    }
    
    /* Executive Summary */
    .financial-grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 15px;
      margin-bottom: 20px;
    }
    
    .financial-card {
      background: linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 100%);
      border-left: 4px solid #3b82f6;
      padding: 15px;
      border-radius: 6px;
    }
    
    .financial-card-label {
      font-size: 9pt;
      color: #6b7280;
      margin-bottom: 5px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    
    .financial-card-amount {
      font-size: 18pt;
      font-weight: 700;
      color: #1e40af;
    }
    
    .financial-card-sublabel {
      font-size: 8pt;
      color: #6b7280;
      margin-top: 5px;
    }
    
    /* Variance Table */
    .variance-table {
      width: 100%;
      border-collapse: collapse;
      margin: 15px 0;
    }
    
    .variance-table th {
      background: #f3f4f6;
      padding: 10px;
      text-align: left;
      font-weight: 600;
      color: #374151;
      border: 1px solid #d1d5db;
      font-size: 9pt;
    }
    
    .variance-table td {
      padding: 10px;
      border: 1px solid #d1d5db;
      font-size: 9pt;
    }
    
    .variance-table tr:nth-child(even) {
      background: #f9fafb;
    }
    
    .variance-badge {
      display: inline-block;
      padding: 4px 10px;
      border-radius: 4px;
      font-weight: 600;
      font-size: 8pt;
      color: white;
    }
    
    /* Risk Analysis */
    .risk-grid {
      display: grid;
      grid-template-columns: 1fr 2fr;
      gap: 20px;
      margin-bottom: 20px;
    }
    
    .risk-gauge {
      text-align: center;
      padding: 20px;
      background: #f9fafb;
      border-radius: 8px;
      border: 2px solid #e5e7eb;
    }
    
    .risk-gauge-label {
      font-size: 9pt;
      color: #6b7280;
      margin-bottom: 10px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    
    .risk-gauge-score {
      font-size: 36pt;
      font-weight: 700;
      line-height: 1;
      margin-bottom: 5px;
    }
    
    .risk-gauge-level {
      font-size: 10pt;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 1px;
    }
    
    .risk-meter {
      height: 20px;
      background: #e5e7eb;
      border-radius: 10px;
      overflow: hidden;
      margin: 15px 0;
    }
    
    .risk-meter-fill {
      height: 100%;
      transition: width 0.3s ease;
    }
    
    .risk-explanation {
      background: #fef3c7;
      border-left: 4px solid #f59e0b;
      padding: 15px;
      border-radius: 6px;
      font-size: 9pt;
      line-height: 1.6;
    }
    
    /* Override Alert */
    .override-alert {
      background: linear-gradient(135deg, #fef3c7 0%, #fde68a 100%);
      border: 2px solid #f59e0b;
      border-radius: 8px;
      padding: 15px;
      margin: 20px 0;
    }
    
    .override-alert-title {
      font-size: 11pt;
      font-weight: 700;
      color: #92400e;
      margin-bottom: 10px;
      display: flex;
      align-items: center;
      gap: 8px;
    }
    
    .override-alert-content {
      font-size: 9pt;
      color: #78350f;
      line-height: 1.6;
    }
    
    .override-meta {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 10px;
      margin-top: 10px;
      padding-top: 10px;
      border-top: 1px solid #f59e0b;
    }
    
    .override-meta-item {
      font-size: 8pt;
    }
    
    .override-meta-label {
      font-weight: 600;
      color: #92400e;
    }
    
    /* Workflow Timeline */
    .timeline-table {
      width: 100%;
      border-collapse: collapse;
      margin: 15px 0;
    }
    
    .timeline-table th {
      background: #1e40af;
      color: white;
      padding: 10px;
      text-align: left;
      font-weight: 600;
      border: 1px solid #1e3a8a;
      font-size: 9pt;
    }
    
    .timeline-table td {
      padding: 10px;
      border: 1px solid #d1d5db;
      font-size: 9pt;
    }
    
    .timeline-table tr:nth-child(even) {
      background: #f9fafb;
    }
    
    .timeline-summary {
      background: #eff6ff;
      border-left: 4px solid #3b82f6;
      padding: 15px;
      border-radius: 6px;
      margin-top: 15px;
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 15px;
    }
    
    .timeline-summary-item {
      font-size: 9pt;
    }
    
    .timeline-summary-label {
      font-weight: 600;
      color: #374151;
      margin-bottom: 5px;
    }
    
    .timeline-summary-value {
      font-size: 14pt;
      font-weight: 700;
      color: #1e40af;
    }
    
    .compliance-badge {
      display: inline-block;
      padding: 6px 12px;
      border-radius: 6px;
      font-weight: 600;
      font-size: 9pt;
      margin-top: 5px;
    }
    
    .compliance-pass {
      background: #d1fae5;
      color: #065f46;
    }
    
    .compliance-fail {
      background: #fee2e2;
      color: #991b1b;
    }
    
    .violation-list {
      margin-top: 10px;
      padding-left: 20px;
      font-size: 9pt;
      color: #991b1b;
    }
    
    /* Page Break Control */
    .page-break {
      page-break-before: always;
    }
    
    .no-break {
      page-break-inside: avoid;
    }
  </style>
</head>
<body>
  <div class="container">
    <!-- Header Section -->
    <div class="report-header no-break">
      <div class="header-left">
        <div class="report-title">Final Claim Report</div>
        <div class="report-subtitle">Board Review Document</div>
        
        <div class="header-meta">
          <span class="header-meta-label">Claim ID:</span>
          <span class="header-meta-value">${data.claimNumber}</span>
          
          <span class="header-meta-label">Policy Holder:</span>
          <span class="header-meta-value">${data.policyHolder}</span>
          
          <span class="header-meta-label">Policy Number:</span>
          <span class="header-meta-value">${data.policyNumber}</span>
          
          <span class="header-meta-label">Vehicle:</span>
          <span class="header-meta-value">${data.vehicleMake} ${data.vehicleModel} (${data.vehicleYear})</span>
          
          <span class="header-meta-label">Registration:</span>
          <span class="header-meta-value">${data.vehicleRegistration}</span>
          
          <span class="header-meta-label">Incident Date:</span>
          <span class="header-meta-value">${formatDate(data.incidentDate)}</span>
          
          <span class="header-meta-label">Report Date:</span>
          <span class="header-meta-value">${formatDate(data.generatedAt)}</span>
        </div>
      </div>
      
      <div class="header-right">
        ${data.insurerLogo ? `
          <img src="${data.insurerLogo}" alt="${data.insurerName}" class="insurer-logo" />
        ` : `
          <div style="font-size: 16pt; font-weight: 700; color: #1e40af;">${data.insurerName}</div>
        `}
        
        <div class="confidence-badge">
          AI Confidence: ${data.aiConfidenceScore}%
        </div>
      </div>
    </div>
    
    <!-- Executive Summary Section -->
    <div class="section no-break">
      <h2 class="section-title">Executive Summary</h2>
      
      <div class="financial-grid">
        <div class="financial-card">
          <div class="financial-card-label">Final Approved Amount</div>
          <div class="financial-card-amount">${formatCurrency(data.finalApprovedAmount)}</div>
          <div class="financial-card-sublabel">Claim Settlement Value</div>
        </div>
        
        <div class="financial-card">
          <div class="financial-card-label">AI Estimate</div>
          <div class="financial-card-amount">${formatCurrency(data.aiEstimatedCost)}</div>
          <div class="financial-card-sublabel">Automated Assessment</div>
        </div>
        
        <div class="financial-card">
          <div class="financial-card-label">Assessor Estimate</div>
          <div class="financial-card-amount">${formatCurrency(data.assessorEstimatedCost)}</div>
          <div class="financial-card-sublabel">Professional Evaluation</div>
        </div>
        
        <div class="financial-card">
          <div class="financial-card-label">Selected Panel Beater</div>
          <div class="financial-card-amount">${formatCurrency(data.selectedPanelBeater.quotedAmount)}</div>
          <div class="financial-card-sublabel">${data.selectedPanelBeater.name}</div>
        </div>
      </div>
      
      <h3 class="section-subtitle">Variance Analysis</h3>
      <table class="variance-table">
        <thead>
          <tr>
            <th>Comparison</th>
            <th>Amount 1</th>
            <th>Amount 2</th>
            <th>Variance</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><strong>Assessor vs AI</strong></td>
            <td>${formatCurrency(data.assessorEstimatedCost)}</td>
            <td>${formatCurrency(data.aiEstimatedCost)}</td>
            <td>${aiVsAssessorVariance >= 0 ? '+' : ''}${aiVsAssessorVariance.toFixed(1)}%</td>
            <td>
              <span class="variance-badge" style="background-color: ${getVarianceColor(aiVsAssessorVariance)};">
                ${Math.abs(aiVsAssessorVariance) < 10 ? 'Aligned' : Math.abs(aiVsAssessorVariance) < 20 ? 'Moderate' : 'Significant'}
              </span>
            </td>
          </tr>
          <tr>
            <td><strong>Approved vs AI</strong></td>
            <td>${formatCurrency(data.finalApprovedAmount)}</td>
            <td>${formatCurrency(data.aiEstimatedCost)}</td>
            <td>${approvedVsAiVariance >= 0 ? '+' : ''}${approvedVsAiVariance.toFixed(1)}%</td>
            <td>
              <span class="variance-badge" style="background-color: ${getVarianceColor(approvedVsAiVariance)};">
                ${Math.abs(approvedVsAiVariance) < 10 ? 'Aligned' : Math.abs(approvedVsAiVariance) < 20 ? 'Moderate' : 'Significant'}
              </span>
            </td>
          </tr>
          <tr>
            <td><strong>Approved vs Assessor</strong></td>
            <td>${formatCurrency(data.finalApprovedAmount)}</td>
            <td>${formatCurrency(data.assessorEstimatedCost)}</td>
            <td>${approvedVsAssessorVariance >= 0 ? '+' : ''}${approvedVsAssessorVariance.toFixed(1)}%</td>
            <td>
              <span class="variance-badge" style="background-color: ${getVarianceColor(approvedVsAssessorVariance)};">
                ${Math.abs(approvedVsAssessorVariance) < 10 ? 'Aligned' : Math.abs(approvedVsAssessorVariance) < 20 ? 'Moderate' : 'Significant'}
              </span>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    
    <!-- Risk Analysis Section -->
    <div class="section">
      <h2 class="section-title">Risk Analysis</h2>
      
      <div class="risk-grid">
        <div class="risk-gauge">
          <div class="risk-gauge-label">Fraud Risk Score</div>
          <div class="risk-gauge-score" style="color: ${getFraudRiskColor(data.fraudRiskLevel)};">
            ${data.fraudRiskScore}
          </div>
          <div class="risk-gauge-level" style="color: ${getFraudRiskColor(data.fraudRiskLevel)};">
            ${data.fraudRiskLevel.toUpperCase()}
          </div>
          <div class="risk-meter">
            <div class="risk-meter-fill" style="width: ${data.fraudRiskScore}%; background-color: ${getFraudRiskColor(data.fraudRiskLevel)};"></div>
          </div>
        </div>
        
        <div>
          <h3 class="section-subtitle">Discrepancy Explanation</h3>
          <div class="risk-explanation">
            ${data.discrepancyExplanation}
          </div>
        </div>
      </div>
      
      ${data.executiveOverride ? `
      <div class="override-alert">
        <div class="override-alert-title">
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/>
          </svg>
          Executive Override Applied
        </div>
        <div class="override-alert-content">
          <p><strong>Justification:</strong> ${data.executiveOverride.justification}</p>
          
          <div class="override-meta">
            <div class="override-meta-item">
              <span class="override-meta-label">Overridden By:</span><br/>
              ${data.executiveOverride.overriddenBy} (${data.executiveOverride.overriddenByRole})
            </div>
            <div class="override-meta-item">
              <span class="override-meta-label">Override Date:</span><br/>
              ${formatDateTime(data.executiveOverride.overriddenAt)}
            </div>
            <div class="override-meta-item">
              <span class="override-meta-label">Original Decision:</span><br/>
              ${data.executiveOverride.originalDecision}
            </div>
            <div class="override-meta-item">
              <span class="override-meta-label">New Decision:</span><br/>
              ${data.executiveOverride.newDecision}
            </div>
          </div>
        </div>
      </div>
      ` : ''}
    </div>
    
    <!-- Workflow Audit Summary Section -->
    <div class="section page-break">
      <h2 class="section-title">Workflow Audit Summary</h2>
      
      <h3 class="section-subtitle">Processing Timeline</h3>
      <table class="timeline-table">
        <thead>
          <tr>
            <th>Stage</th>
            <th>Started</th>
            <th>Completed</th>
            <th>Duration</th>
            <th>Handled By</th>
          </tr>
        </thead>
        <tbody>
          ${data.workflowTimeline.map(stage => `
            <tr>
              <td><strong>${stage.stage}</strong></td>
              <td>${formatDateTime(stage.startedAt)}</td>
              <td>${formatDateTime(stage.completedAt)}</td>
              <td>${stage.durationMinutes} min</td>
              <td>${stage.handledBy}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
      
      <div class="timeline-summary">
        <div class="timeline-summary-item">
          <div class="timeline-summary-label">Total Processing Time</div>
          <div class="timeline-summary-value">
            ${Math.floor(data.totalProcessingTimeMinutes / 60)}h ${data.totalProcessingTimeMinutes % 60}m
          </div>
        </div>
        
        <div class="timeline-summary-item">
          <div class="timeline-summary-label">Segregation of Duties Compliance</div>
          <div class="timeline-summary-value">
            <span class="compliance-badge ${data.segregationCompliant ? 'compliance-pass' : 'compliance-fail'}">
              ${data.segregationCompliant ? '✓ COMPLIANT' : '✗ VIOLATIONS DETECTED'}
            </span>
          </div>
          ${!data.segregationCompliant && data.segregationViolations.length > 0 ? `
            <ul class="violation-list">
              ${data.segregationViolations.map(v => `<li>${v}</li>`).join('')}
            </ul>
          ` : ''}
        </div>
      </div>
    </div>
  </div>
</body>
</html>
  `;
}

/**
 * Helper function to format duration in human-readable format
 */
function formatDuration(minutes: number): string {
  if (minutes < 60) {
    return `${minutes} minutes`;
  }
  const hours = Math.floor(minutes / 60);
  const mins = minutes % 60;
  return mins > 0 ? `${hours}h ${mins}m` : `${hours}h`;
}
