// @ts-nocheck
/**
 * Governance Export Utility
 * 
 * Generates PDF and CSV exports for governance dashboard data
 * Includes comprehensive governance metrics, charts, and audit trails
 */

import PDFDocument from "pdfkit";
import { format } from "date-fns";

interface GovernanceExportData {
  reportMetadata: {
    generatedAt: string;
    tenantId: string;
    generatedBy: string;
    period: string;
  };
  summary: {
    totalOverrides: number;
    overrideRate: number;
    segregationViolations: number;
    roleChanges: number;
    governanceRiskScore: number;
  };
  overridesByUser: Array<{
    userId: string;
    userName: string;
    overrideCount: number;
    totalClaims: number;
    overrideRate: number;
  }>;
  overridesByValue: Array<{
    band: string;
    overrideCount: number;
    totalClaims: number;
    overrideRate: number;
  }>;
  segregationViolations: Array<{
    type: string;
    count: number;
  }>;
  roleChanges: Array<{
    userId: string;
    adminName: string;
    roleChangesPerformed: number;
    mostCommonChange: string;
  }>;
}

/**
 * Generate governance report PDF
 */
export async function generateGovernancePDF(data: GovernanceExportData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: "A4", margin: 50 });
      const chunks: Buffer[] = [];

      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      // Header
      doc
        .fontSize(24)
        .font("Helvetica-Bold")
        .text("Governance Report", { align: "center" })
        .moveDown(0.5);

      doc
        .fontSize(10)
        .font("Helvetica")
        .text(`Generated: ${format(new Date(data.reportMetadata.generatedAt), "PPpp")}`, {
          align: "center",
        })
        .text(`Period: ${data.reportMetadata.period}`, { align: "center" })
        .text(`Generated by: ${data.reportMetadata.generatedBy}`, { align: "center" })
        .moveDown(1.5);

      // Executive Summary
      doc
        .fontSize(16)
        .font("Helvetica-Bold")
        .text("Executive Summary")
        .moveDown(0.5);

      doc.fontSize(10).font("Helvetica");

      const summaryData = [
        ["Total Overrides", data.summary.totalOverrides.toString()],
        ["Override Rate", `${data.summary.overrideRate.toFixed(1)}%`],
        ["Segregation Violations", data.summary.segregationViolations.toString()],
        ["Role Changes", data.summary.roleChanges.toString()],
        ["Governance Risk Score", `${data.summary.governanceRiskScore}/100`],
      ];

      summaryData.forEach(([label, value]) => {
        doc.text(`${label}: `, { continued: true }).font("Helvetica-Bold").text(value);
        doc.font("Helvetica");
      });

      doc.moveDown(1.5);

      // Override Analysis
      doc
        .fontSize(14)
        .font("Helvetica-Bold")
        .text("Override Analysis")
        .moveDown(0.5);

      doc.fontSize(10).font("Helvetica");

      if (data.overridesByUser.length > 0) {
        doc.text("Override Rate by User:", { underline: true }).moveDown(0.3);

        data.overridesByUser.forEach((user) => {
          doc.text(
            `• ${user.userName}: ${user.overrideCount} overrides (${user.overrideRate.toFixed(1)}% of ${user.totalClaims} claims)`
          );
        });

        doc.moveDown(1);
      }

      if (data.overridesByValue.length > 0) {
        doc.text("Override Rate by Claim Value:", { underline: true }).moveDown(0.3);

        data.overridesByValue.forEach((band) => {
          doc.text(
            `• ${band.band}: ${band.overrideCount} overrides (${band.overrideRate.toFixed(1)}% of ${band.totalClaims} claims)`
          );
        });

        doc.moveDown(1.5);
      }

      // Segregation Monitoring
      doc.addPage();
      doc
        .fontSize(14)
        .font("Helvetica-Bold")
        .text("Segregation Monitoring")
        .moveDown(0.5);

      doc.fontSize(10).font("Helvetica");

      if (data.segregationViolations.length > 0) {
        doc.text("Violations Prevented:", { underline: true }).moveDown(0.3);

        data.segregationViolations.forEach((violation) => {
          doc.text(`• ${violation.type}: ${violation.count} attempts blocked`);
        });

        doc.moveDown(1.5);
      }

      // Role Change Oversight
      doc
        .fontSize(14)
        .font("Helvetica-Bold")
        .text("Role Change Oversight")
        .moveDown(0.5);

      doc.fontSize(10).font("Helvetica");

      if (data.roleChanges.length > 0) {
        doc.text("Role Changes by Actor:", { underline: true }).moveDown(0.3);

        data.roleChanges.forEach((change) => {
          doc.text(
            `• ${change.adminName}: ${change.roleChangesPerformed} changes (most common: ${change.mostCommonChange})`
          );
        });

        doc.moveDown(1.5);
      }

      // Footer
      doc
        .fontSize(8)
        .font("Helvetica")
        .text("This report is confidential and intended for authorized personnel only.", {
          align: "center",
        });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

/**
 * Generate governance data CSV
 */
export function generateGovernanceCSV(data: GovernanceExportData): string {
  const lines: string[] = [];

  // Header
  lines.push("KINGA Governance Report - CSV Export");
  lines.push(`Generated: ${format(new Date(data.reportMetadata.generatedAt), "PPpp")}`);
  lines.push(`Period: ${data.reportMetadata.period}`);
  lines.push(`Generated by: ${data.reportMetadata.generatedBy}`);
  lines.push("");

  // Summary
  lines.push("EXECUTIVE SUMMARY");
  lines.push("Metric,Value");
  lines.push(`Total Overrides,${data.summary.totalOverrides}`);
  lines.push(`Override Rate,${data.summary.overrideRate.toFixed(1)}%`);
  lines.push(`Segregation Violations,${data.summary.segregationViolations}`);
  lines.push(`Role Changes,${data.summary.roleChanges}`);
  lines.push(`Governance Risk Score,${data.summary.governanceRiskScore}/100`);
  lines.push("");

  // Override by User
  if (data.overridesByUser.length > 0) {
    lines.push("OVERRIDE RATE BY USER");
    lines.push("User ID,User Name,Override Count,Total Claims,Override Rate (%)");
    data.overridesByUser.forEach((user) => {
      lines.push(
        `${user.userId},${user.userName},${user.overrideCount},${user.totalClaims},${user.overrideRate.toFixed(1)}`
      );
    });
    lines.push("");
  }

  // Override by Value Band
  if (data.overridesByValue.length > 0) {
    lines.push("OVERRIDE RATE BY CLAIM VALUE BAND");
    lines.push("Value Band,Override Count,Total Claims,Override Rate (%)");
    data.overridesByValue.forEach((band) => {
      lines.push(
        `"${band.band}",${band.overrideCount},${band.totalClaims},${band.overrideRate.toFixed(1)}`
      );
    });
    lines.push("");
  }

  // Segregation Violations
  if (data.segregationViolations.length > 0) {
    lines.push("SEGREGATION VIOLATIONS PREVENTED");
    lines.push("Violation Type,Count");
    data.segregationViolations.forEach((violation) => {
      lines.push(`"${violation.type}",${violation.count}`);
    });
    lines.push("");
  }

  // Role Changes
  if (data.roleChanges.length > 0) {
    lines.push("ROLE CHANGES BY ACTOR");
    lines.push("User ID,Admin Name,Changes Performed,Most Common Change");
    data.roleChanges.forEach((change) => {
      lines.push(
        `${change.userId},${change.adminName},${change.roleChangesPerformed},"${change.mostCommonChange}"`
      );
    });
    lines.push("");
  }

  return lines.join("\n");
}
