/**
 * Report Email Service
 * 
 * Automated email delivery for generated intelligence reports.
 * Sends PDF reports to stakeholders with role-based access controls.
 */

import { notifyOwner } from "./_core/notification";

export interface ReportEmailOptions {
  recipientEmail: string;
  recipientName: string;
  claimNumber: string;
  reportType: "insurer" | "assessor" | "regulatory";
  pdfUrl: string;
  interactiveReportUrl?: string;
  generatedBy: string;
  tenantId: string;
}

/**
 * Send report email notification
 */
export async function sendReportEmail(options: ReportEmailOptions): Promise<boolean> {
  const {
    recipientEmail,
    recipientName,
    claimNumber,
    reportType,
    pdfUrl,
    interactiveReportUrl,
    generatedBy,
  } = options;

  // Format report type for display
  const reportTypeDisplay = {
    insurer: "Insurer Intelligence Report",
    assessor: "Assessor Evaluation Report",
    regulatory: "Regulatory Compliance Report",
  }[reportType];

  // Construct email content
  const emailContent = `
**New Insurance Claim Report Generated**

Dear ${recipientName},

A new ${reportTypeDisplay} has been generated for claim ${claimNumber}.

**Report Details:**
- Claim Number: ${claimNumber}
- Report Type: ${reportTypeDisplay}
- Generated By: ${generatedBy}
- Generated At: ${new Date().toLocaleString()}

**Access Your Report:**

📄 **PDF Report (Immutable Snapshot):**
${pdfUrl}

${interactiveReportUrl ? `🔍 **Interactive Report (Living Intelligence):**
${interactiveReportUrl}

The interactive report provides drill-down analytics, AI vs assessor comparisons, fraud risk exploration, and real-time data updates.` : ''}

**Report Features:**
- Executive summary with key findings
- AI-powered damage assessment analysis
- Cost comparison and variance analysis
- Fraud risk evaluation with ML scoring
- Physics-based accident validation
- Complete workflow audit trail
- Visual evidence and damage mapping

This report is confidential and intended solely for authorized personnel. Please do not forward or share without proper authorization.

If you have any questions about this report, please contact your claims manager.

---
KINGA AutoVerify AI - Intelligent Claims Management
  `.trim();

  // Send notification to owner (as a proxy for email delivery)
  // In production, this would integrate with an email service like SendGrid, AWS SES, etc.
  const success = await notifyOwner({
    title: `Report Generated: ${claimNumber} - ${reportTypeDisplay}`,
    content: emailContent,
  });

  return success;
}

/**
 * Send report to multiple stakeholders
 */
export async function sendReportToStakeholders(
  reportOptions: Omit<ReportEmailOptions, "recipientEmail" | "recipientName">,
  stakeholders: Array<{ email: string; name: string; role: string }>
): Promise<{ sent: number; failed: number }> {
  let sent = 0;
  let failed = 0;

  for (const stakeholder of stakeholders) {
    try {
      const success = await sendReportEmail({
        ...reportOptions,
        recipientEmail: stakeholder.email,
        recipientName: stakeholder.name,
      });

      if (success) {
        sent++;
      } else {
        failed++;
      }
    } catch (error) {
      console.error(`Failed to send report to ${stakeholder.email}:`, error);
      failed++;
    }
  }

  return { sent, failed };
}

/**
 * Get stakeholders for a report based on report type
 */
export async function getReportStakeholders(
  claimId: number,
  reportType: "insurer" | "assessor" | "regulatory",
  tenantId: string
): Promise<Array<{ email: string; name: string; role: string }>> {
  const { getDb } = await import("./db");
  const { claims, users } = await import("../drizzle/schema");
  const { eq, and } = await import("drizzle-orm");

  const db = await getDb();
  if (!db) throw new Error("Database unavailable");

  // Get claim details
  const [claim] = await db
    .select()
    .from(claims)
    .where(and(eq(claims.id, claimId), eq(claims.tenantId, tenantId)));

  if (!claim) {
    throw new Error("Claim not found");
  }

  const stakeholders: Array<{ email: string; name: string; role: string }> = [];

  // Add claimant
  const [claimant] = await db
    .select()
    .from(users)
    .where(eq(users.id, claim.claimantId));

  if (claimant?.email) {
    stakeholders.push({
      email: claimant.email,
      name: claimant.name || "Claimant",
      role: "claimant",
    });
  }

  // Add assigned assessor if exists
  if (claim.assignedAssessorId) {
    const [assessor] = await db
      .select()
      .from(users)
      .where(eq(users.id, claim.assignedAssessorId));

    if (assessor?.email) {
      stakeholders.push({
        email: assessor.email,
        name: assessor.name || "Assessor",
        role: "assessor",
      });
    }
  }

  // For insurer and regulatory reports, add executives and claims managers
  if (reportType === "insurer" || reportType === "regulatory") {
    const executives = await db
      .select()
      .from(users)
      .where(
        and(
          eq(users.tenantId, tenantId),
          eq(users.role, "insurer")
        )
      );

    for (const exec of executives) {
      if (exec.email && (exec.insurerRole === "executive" || exec.insurerRole === "claims_manager")) {
        stakeholders.push({
          email: exec.email,
          name: exec.name || "Executive",
          role: exec.insurerRole || "executive",
        });
      }
    }
  }

  return stakeholders;
}
