/**
 * Analytics Export Service
 * 
 * Generates PDF and CSV reports for fast-track analytics metrics.
 * Supports date range filtering and includes all 5 key performance metrics.
 */

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import {
  calculateFastTrackRate,
  calculateAutoApprovalRate,
  calculateProcessingTime,
  calculateExecutiveOverrides,
  calculateRiskDistribution,
} from "../fast-track-analytics";

/**
 * Date range for analytics reports
 */
export interface DateRange {
  startDate: Date;
  endDate: Date;
}

/**
 * Report metadata
 */
export interface ReportMetadata {
  tenantId: string;
  tenantName?: string;
  dateRange: DateRange;
  generatedAt: Date;
  generatedBy: string; // User name or ID
}

/**
 * Complete analytics data for export
 */
export interface AnalyticsReportData {
  metadata: ReportMetadata;
  fastTrackRate: {
    fastTrackCount: number;
    totalClaims: number;
    percentage: number;
  };
  autoApprovalRate: {
    autoApprovedCount: number;
    totalFastTrack: number;
    percentage: number;
  };
  processingTime: {
    fastTrackAvgHours: number;
    standardAvgHours: number;
    timeSavingsHours: number;
  };
  executiveOverride: {
    overrideCount: number;
    totalFastTrack: number;
    percentage: number;
  };
  riskDistribution: {
    LOW: number;
    MEDIUM: number;
    HIGH: number;
  };
}

/**
 * Gather all analytics data for export
 */
export async function gatherAnalyticsData(
  tenantId: string,
  dateRange: DateRange,
  metadata: Omit<ReportMetadata, "dateRange">
): Promise<AnalyticsReportData> {
  const [fastTrackRateData, autoApprovalData, processingTimeData, executiveOverrideData, riskDistData] =
    await Promise.all([
      calculateFastTrackRate(tenantId, dateRange),
      calculateAutoApprovalRate(tenantId, dateRange),
      calculateProcessingTime(tenantId, dateRange),
      calculateExecutiveOverrides(tenantId, dateRange),
      calculateRiskDistribution(tenantId, dateRange),
    ]);

  // Transform data to match expected format
  const fastTrackRate = {
    fastTrackCount: fastTrackRateData.fastTrackedClaims,
    totalClaims: fastTrackRateData.totalClaims,
    percentage: fastTrackRateData.fastTrackRate,
  };

  const autoApprovalRate = {
    autoApprovedCount: autoApprovalData.autoApproved,
    totalFastTrack: autoApprovalData.totalFastTracked,
    percentage: autoApprovalData.autoApprovalRate,
  };

  const processingTime = {
    fastTrackAvgHours: processingTimeData.fastTrackAvgHours,
    standardAvgHours: processingTimeData.normalAvgHours,
    timeSavingsHours: processingTimeData.timeSavingsHours,
  };

  const executiveOverride = {
    overrideCount: executiveOverrideData.overrideCount,
    totalFastTrack: executiveOverrideData.totalAutoApprovals,
    percentage: executiveOverrideData.overrideRate,
  };

  const riskDistribution = {
    LOW: riskDistData.lowRisk,
    MEDIUM: riskDistData.mediumRisk,
    HIGH: riskDistData.highRisk,
  };

  return {
    metadata: { ...metadata, dateRange },
    fastTrackRate,
    autoApprovalRate,
    processingTime,
    executiveOverride,
    riskDistribution,
  };
}

/**
 * Generate PDF report from analytics data
 */
export async function generatePDFReport(data: AnalyticsReportData): Promise<Buffer> {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("Fast-Track Analytics Report", pageWidth / 2, 20, { align: "center" });
  
  // Metadata
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const startDate = data.metadata.dateRange.startDate.toLocaleDateString();
  const endDate = data.metadata.dateRange.endDate.toLocaleDateString();
  const generatedAt = data.metadata.generatedAt.toLocaleString();
  
  doc.text(`Report Period: ${startDate} - ${endDate}`, 14, 35);
  doc.text(`Generated: ${generatedAt}`, 14, 40);
  doc.text(`Generated By: ${data.metadata.generatedBy}`, 14, 45);
  if (data.metadata.tenantName) {
    doc.text(`Organization: ${data.metadata.tenantName}`, 14, 50);
  }
  
  let yPosition = 60;
  
  // Fast-Track Rate Section
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("1. Fast-Track Eligibility Rate", 14, yPosition);
  yPosition += 8;
  
  autoTable(doc, {
    startY: yPosition,
    head: [["Metric", "Value"]],
    body: [
      ["Total Claims", data.fastTrackRate.totalClaims.toString()],
      ["Fast-Track Eligible", data.fastTrackRate.fastTrackCount.toString()],
      ["Eligibility Rate", `${data.fastTrackRate.percentage.toFixed(2)}%`],
    ],
    theme: "striped",
    headStyles: { fillColor: [41, 128, 185] },
  });
  
  yPosition = (doc as any).lastAutoTable.finalY + 10;
  
  // Auto-Approval Rate Section
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("2. Auto-Approval Rate", 14, yPosition);
  yPosition += 8;
  
  autoTable(doc, {
    startY: yPosition,
    head: [["Metric", "Value"]],
    body: [
      ["Total Fast-Track Claims", data.autoApprovalRate.totalFastTrack.toString()],
      ["Auto-Approved", data.autoApprovalRate.autoApprovedCount.toString()],
      ["Auto-Approval Rate", `${data.autoApprovalRate.percentage.toFixed(2)}%`],
    ],
    theme: "striped",
    headStyles: { fillColor: [41, 128, 185] },
  });
  
  yPosition = (doc as any).lastAutoTable.finalY + 10;
  
  // Processing Time Section
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("3. Processing Time Comparison", 14, yPosition);
  yPosition += 8;
  
  autoTable(doc, {
    startY: yPosition,
    head: [["Metric", "Value"]],
    body: [
      ["Fast-Track Avg (hours)", data.processingTime.fastTrackAvgHours.toFixed(2)],
      ["Standard Avg (hours)", data.processingTime.standardAvgHours.toFixed(2)],
      ["Time Savings (hours)", data.processingTime.timeSavingsHours.toFixed(2)],
    ],
    theme: "striped",
    headStyles: { fillColor: [41, 128, 185] },
  });
  
  yPosition = (doc as any).lastAutoTable.finalY + 10;
  
  // Executive Override Section
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("4. Executive Override Frequency", 14, yPosition);
  yPosition += 8;
  
  autoTable(doc, {
    startY: yPosition,
    head: [["Metric", "Value"]],
    body: [
      ["Total Fast-Track Claims", data.executiveOverride.totalFastTrack.toString()],
      ["Executive Overrides", data.executiveOverride.overrideCount.toString()],
      ["Override Rate", `${data.executiveOverride.percentage.toFixed(2)}%`],
    ],
    theme: "striped",
    headStyles: { fillColor: [41, 128, 185] },
  });
  
  yPosition = (doc as any).lastAutoTable.finalY + 10;
  
  // Risk Distribution Section
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("5. Risk Distribution", 14, yPosition);
  yPosition += 8;
  
  const totalRisk = data.riskDistribution.LOW + data.riskDistribution.MEDIUM + data.riskDistribution.HIGH;
  
  autoTable(doc, {
    startY: yPosition,
    head: [["Risk Level", "Count", "Percentage"]],
    body: [
      [
        "LOW",
        data.riskDistribution.LOW.toString(),
        totalRisk > 0 ? `${((data.riskDistribution.LOW / totalRisk) * 100).toFixed(2)}%` : "0%",
      ],
      [
        "MEDIUM",
        data.riskDistribution.MEDIUM.toString(),
        totalRisk > 0 ? `${((data.riskDistribution.MEDIUM / totalRisk) * 100).toFixed(2)}%` : "0%",
      ],
      [
        "HIGH",
        data.riskDistribution.HIGH.toString(),
        totalRisk > 0 ? `${((data.riskDistribution.HIGH / totalRisk) * 100).toFixed(2)}%` : "0%",
      ],
    ],
    theme: "striped",
    headStyles: { fillColor: [41, 128, 185] },
  });
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.text(
      `Page ${i} of ${pageCount} | KINGA AutoVerify AI - Fast-Track Analytics`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }
  
  return Buffer.from(doc.output("arraybuffer"));
}

/**
 * Generate CSV report from analytics data
 */
export async function generateCSVReport(data: AnalyticsReportData): Promise<string> {
  const lines: string[] = [];
  
  // Header
  lines.push("KINGA AutoVerify AI - Fast-Track Analytics Report");
  lines.push("");
  
  // Metadata
  const startDate = data.metadata.dateRange.startDate.toLocaleDateString();
  const endDate = data.metadata.dateRange.endDate.toLocaleDateString();
  const generatedAt = data.metadata.generatedAt.toLocaleString();
  
  lines.push(`Report Period:,${startDate} - ${endDate}`);
  lines.push(`Generated:,${generatedAt}`);
  lines.push(`Generated By:,${data.metadata.generatedBy}`);
  if (data.metadata.tenantName) {
    lines.push(`Organization:,${data.metadata.tenantName}`);
  }
  lines.push("");
  
  // Fast-Track Rate
  lines.push("1. Fast-Track Eligibility Rate");
  lines.push("Metric,Value");
  lines.push(`Total Claims,${data.fastTrackRate.totalClaims}`);
  lines.push(`Fast-Track Eligible,${data.fastTrackRate.fastTrackCount}`);
  lines.push(`Eligibility Rate,${data.fastTrackRate.percentage.toFixed(2)}%`);
  lines.push("");
  
  // Auto-Approval Rate
  lines.push("2. Auto-Approval Rate");
  lines.push("Metric,Value");
  lines.push(`Total Fast-Track Claims,${data.autoApprovalRate.totalFastTrack}`);
  lines.push(`Auto-Approved,${data.autoApprovalRate.autoApprovedCount}`);
  lines.push(`Auto-Approval Rate,${data.autoApprovalRate.percentage.toFixed(2)}%`);
  lines.push("");
  
  // Processing Time
  lines.push("3. Processing Time Comparison");
  lines.push("Metric,Value");
  lines.push(`Fast-Track Avg (hours),${data.processingTime.fastTrackAvgHours.toFixed(2)}`);
  lines.push(`Standard Avg (hours),${data.processingTime.standardAvgHours.toFixed(2)}`);
  lines.push(`Time Savings (hours),${data.processingTime.timeSavingsHours.toFixed(2)}`);
  lines.push("");
  
  // Executive Override
  lines.push("4. Executive Override Frequency");
  lines.push("Metric,Value");
  lines.push(`Total Fast-Track Claims,${data.executiveOverride.totalFastTrack}`);
  lines.push(`Executive Overrides,${data.executiveOverride.overrideCount}`);
  lines.push(`Override Rate,${data.executiveOverride.percentage.toFixed(2)}%`);
  lines.push("");
  
  // Risk Distribution
  lines.push("5. Risk Distribution");
  lines.push("Risk Level,Count,Percentage");
  const totalRisk = data.riskDistribution.LOW + data.riskDistribution.MEDIUM + data.riskDistribution.HIGH;
  lines.push(
    `LOW,${data.riskDistribution.LOW},${
      totalRisk > 0 ? ((data.riskDistribution.LOW / totalRisk) * 100).toFixed(2) : "0"
    }%`
  );
  lines.push(
    `MEDIUM,${data.riskDistribution.MEDIUM},${
      totalRisk > 0 ? ((data.riskDistribution.MEDIUM / totalRisk) * 100).toFixed(2) : "0"
    }%`
  );
  lines.push(
    `HIGH,${data.riskDistribution.HIGH},${
      totalRisk > 0 ? ((data.riskDistribution.HIGH / totalRisk) * 100).toFixed(2) : "0"
    }%`
  );
  
  return lines.join("\n");
}
