CREATE TABLE `claim_assignments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`claim_id` int NOT NULL,
	`tenant_id` varchar(255) NOT NULL,
	`assignment_role` enum('assessor','claims_assessor','claims_manager') NOT NULL,
	`assigned_to_user_id` int NOT NULL,
	`assigned_by_user_id` int,
	`assignment_source` enum('manual','workflow','reassignment','system','legacy_import') NOT NULL DEFAULT 'manual',
	`status` enum('assigned','accepted','declined','reassigned','completed','cancelled') NOT NULL DEFAULT 'assigned',
	`parent_assignment_id` int,
	`in_app_notification_created` tinyint NOT NULL DEFAULT 0,
	`email_notification_requested` tinyint NOT NULL DEFAULT 0,
	`email_notification_sent_at` timestamp,
	`email_notification_reference` varchar(255),
	`decision_reason` text,
	`assigned_at` timestamp NOT NULL DEFAULT (now()),
	`accepted_at` timestamp,
	`declined_at` timestamp,
	`reassigned_at` timestamp,
	`completed_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `claim_assignments_id` PRIMARY KEY(`id`)
);