CREATE TABLE `claims` (
	`id` int AUTO_INCREMENT NOT NULL,
	`claimant_id` int,
	`claim_number` varchar(50) NOT NULL,
	`kinga_ref` varchar(40),
	`tenant_id` varchar(255),
	`vehicle_make` varchar(100),
	`vehicle_model` varchar(100),
	`vehicle_year` int,
	`vehicle_registration` varchar(50),
	`incident_date` timestamp,
	`incident_description` text,
	`normalised_description` text,
	`reported_cause_label` varchar(100),
	`key_facts_json` text,
	`incident_location` text,
	`damage_photos` text,
	`policy_number` varchar(100),
	`policy_verified` tinyint,
	`status` enum('submitted','triage','assessment_pending','assessment_in_progress','quotes_pending','comparison','repair_assigned','repair_in_progress','completed','rejected','intake_pending','assessment_complete','closed','document_validating','document_ready','analysis_running','analysis_complete','document_failed','recovery_attempted','human_review_required') NOT NULL DEFAULT 'submitted',
	`workflow_state` enum('created','intake_queue','intake_verified','assigned','under_assessment','internal_review','technical_approval','financial_decision','payment_authorized','closed','disputed','ai_assessment_pending','ai_assessment_completed','manual_review'),
	`assigned_assessor_id` int,
	`assigned_panel_beater_id` int,
	`selected_panel_beater_ids` text,
	`panel_beater_choice_1` varchar(36),
	`panel_beater_choice_2` varchar(36),
	`panel_beater_choice_3` varchar(36),
	`ai_assessment_triggered` tinyint DEFAULT 0,
	`ai_assessment_completed` tinyint DEFAULT 0,
	`ai_assessment_started_at` timestamp,
	`ai_assessment_completed_at` timestamp,
	`fraud_risk_score` int,
	`fraud_flags` text,
	`complexity_score` enum('simple','moderate','complex','exceptional'),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`external_assessment_url` text,
	`fraud_risk_level` enum('low','medium','moderate','high'),
	`requires_gm_consultation` tinyint DEFAULT 0,
	`technically_approved_by` int,
	`technically_approved_at` timestamp,
	`financially_approved_by` int,
	`financially_approved_at` timestamp,
	`approved_amount` int,
	`closed_by` int,
	`closed_at` timestamp,
	`lodged_by` enum('self','broker','agent','company_rep','family_member','legal_rep','other') DEFAULT 'self',
	`lodger_name` varchar(255),
	`lodger_phone` varchar(50),
	`lodger_email` varchar(320),
	`lodger_company` varchar(255),
	`lodger_reference` varchar(100),
	`lodger_relationship` varchar(255),
	`claimant_id_number` varchar(20),
	`claimant_phone` varchar(50),
	`claimant_email` varchar(320),
	`claimant_address` text,
	`vehicle_vin` varchar(50),
	`vehicle_color` varchar(50),
	`vehicle_mileage` varchar(50),
	`vehicle_engine_number` varchar(100),
	`vehicle_gvm` varchar(20),
	`vehicle_tare_weight` varchar(20),
	`vehicle_engine_capacity` varchar(20),
	`vehicle_fuel_type` varchar(20),
	`vehicle_first_registration_date` varchar(20),
	`vehicle_owner_name` varchar(255),
	`vehicle_licence_expiry_date` varchar(20),
	`incident_time` varchar(10),
	`incident_type` enum('collision','theft','hail','fire','vandalism','flood','hijacking','other'),
	`third_party_name` varchar(255),
	`third_party_vehicle` varchar(255),
	`third_party_registration` varchar(50),
	`third_party_insurer` varchar(255),
	`police_report_number` varchar(100),
	`police_station` varchar(255),
	`witness_name` varchar(255),
	`witness_phone` varchar(50),
	`supporting_documents` text,
	`metadata` json,
	`assigned_processor_id` varchar(255),
	`priority` enum('low','medium','high') DEFAULT 'medium',
	`early_fraud_suspicion` tinyint NOT NULL DEFAULT 0,
	`estimated_claim_value` decimal(12,2),
	`final_approved_amount` decimal(12,2),
	`confidence_score` int,
	`routing_decision` varchar(50),
	`policy_version_id` int,
	`source_document_id` int,
	`claim_source` varchar(50),
	`is_simulated` tinyint NOT NULL DEFAULT 0,
	`vehicle_market_value` int,
	`document_processing_status` varchar(30) NOT NULL DEFAULT 'pending',
	`currency_code` varchar(10) DEFAULT 'USD',
	`vehicle_registry_id` int,
	`driver_registry_id` int,
	`third_party_driver_registry_id` int,
	`ai_detected_incident_type` enum('collision','theft','hail','fire','vandalism','flood','hijacking','other'),
	`incident_type_overridden` tinyint NOT NULL DEFAULT 0,
	`incident_type_override_reason` text,
	`incident_type_overridden_by` int,
	`incident_type_overridden_at` timestamp,
	`incident_type_revalidation_json` text,
	`product_type` varchar(100),
	`product_type_source` varchar(50),
	`estimated_cost` int,
	`estimated_speed_kmh` decimal(6,1),
	`claimant_stated_speed_kmh` decimal(6,1),
	`claimant_speed_needs_verification` tinyint DEFAULT 0,
	`data_completeness_score` decimal(5,2),
	`insurer_name` varchar(255),
	`excess_amount_cents` int,
	`claim_reference` varchar(100),
	`pipeline_current_stage` varchar(100),
	`pipeline_run_uuid` varchar(64),
	`pipeline_heartbeat_at` timestamp,
	`fleet_account_id` int,
	`claimant_type` enum('individual','company') NOT NULL DEFAULT 'individual',
	`claimant_company_name` varchar(255),
	`claimant_company_reg` varchar(100),
	`claimant_department` varchar(255),
	`fleet_vehicle_ref` varchar(100),
	`fleet_driver_id` int,
	`recovery_retry_count` int NOT NULL DEFAULT 0,
	`rejection_reason` text,
	`rejection_category` varchar(50),
	`rejected_by` int,
	`rejected_at` timestamp,
	CONSTRAINT `claims_id` PRIMARY KEY(`id`),
	CONSTRAINT `idx_claims_source_document_id` UNIQUE(`source_document_id`)
);