CREATE TABLE `drivers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`full_name` varchar(255) NOT NULL,
	`license_number` varchar(50),
	`license_issue_date` varchar(20),
	`license_expiry_date` varchar(20),
	`date_of_birth` varchar(20),
	`phone` varchar(30),
	`email` varchar(320),
	`national_id_number` varchar(50),
	`license_country` varchar(5),
	`total_claims_count` int NOT NULL DEFAULT 0,
	`at_fault_claims_count` int NOT NULL DEFAULT 0,
	`driver_risk_score` int NOT NULL DEFAULT 0,
	`is_repeat_claimer` tinyint NOT NULL DEFAULT 0,
	`is_staged_accident_suspect` tinyint NOT NULL DEFAULT 0,
	`claim_ids_json` text,
	`last_fraud_risk_score` int NOT NULL DEFAULT 0,
	`data_source` enum('ocr','manual','import','unknown') NOT NULL DEFAULT 'unknown',
	`ocr_confidence_score` int,
	`tenant_id` varchar(255),
	`first_seen_at` timestamp NOT NULL DEFAULT (now()),
	`last_seen_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `drivers_id` PRIMARY KEY(`id`),
	CONSTRAINT `idx_drivers_license_number` UNIQUE(`license_number`)
);