CREATE TABLE `inspections` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenant_id` varchar(255) NOT NULL,
	`inspection_ref` varchar(50) NOT NULL,
	`inspection_type` enum('vehicle','engineering','risk_survey','fleet','property','equipment','industrial') NOT NULL,
	`status` enum('scheduled','assigned','in_progress','evidence_capture','measurements_complete','observations_complete','ai_analysis','engineer_review','physics_reconciliation','report_generation','complete','cancelled') NOT NULL DEFAULT 'scheduled',
	`asset_registry_id` int,
	`asset_ref` varchar(100),
	`asset_type` varchar(50) NOT NULL,
	`vehicle_registration` varchar(50),
	`claim_id` int,
	`project_id` int,
	`assigned_engineer_id` int,
	`assigned_at` timestamp,
	`scheduled_date` timestamp,
	`location_address` text,
	`location_lat` decimal(10,7),
	`location_lng` decimal(10,7),
	`completed_at` timestamp,
	`duration_minutes` int,
	`ai_analysis_json` json,
	`ai_analysis_at` timestamp,
	`ai_analysis_approved` tinyint NOT NULL DEFAULT 0,
	`physics_reconciled` tinyint NOT NULL DEFAULT 0,
	`physics_reconciled_at` timestamp,
	`reconciliation_notes` text,
	`report_key` varchar(100),
	`report_id` int,
	`created_by` int NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `inspections_id` PRIMARY KEY(`id`),
	CONSTRAINT `idx_inspections_ref` UNIQUE(`inspection_ref`)
);