CREATE TABLE `insurance_policies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`policy_number` varchar(100) NOT NULL,
	`quote_id` int,
	`customer_id` int NOT NULL,
	`vehicle_id` int NOT NULL,
	`carrier_id` int NOT NULL,
	`product_id` int NOT NULL,
	`premium_amount` int NOT NULL,
	`premium_frequency` enum('monthly','annual') NOT NULL DEFAULT 'monthly',
	`excess_amount` int,
	`coverage_start_date` timestamp NOT NULL,
	`coverage_end_date` timestamp NOT NULL,
	`coverage_limits` text,
	`status` enum('pending','active','endorsed','cancelled','expired','renewed') NOT NULL DEFAULT 'pending',
	`cancellation_reason` text,
	`cancellation_date` timestamp,
	`cancelled_by` int,
	`renewal_reminder_sent` tinyint DEFAULT 0,
	`renewal_reminder_date` timestamp,
	`renewed_to_policy_id` int,
	`tenant_id` varchar(255),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `insurance_policies_id` PRIMARY KEY(`id`)
);