CREATE TABLE `insurance_quotes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`quote_number` varchar(50) NOT NULL,
	`customer_id` int NOT NULL,
	`vehicle_id` int NOT NULL,
	`carrier_id` int NOT NULL,
	`product_id` int NOT NULL,
	`premium_amount` int NOT NULL,
	`premium_frequency` enum('monthly','annual') NOT NULL DEFAULT 'monthly',
	`excess_amount` int,
	`coverage_limits` text,
	`driver_details` text,
	`risk_profile` text,
	`quote_valid_until` timestamp NOT NULL,
	`status` enum('pending','payment_pending','payment_submitted','payment_verified','accepted','rejected','expired') NOT NULL DEFAULT 'pending',
	`kinga_insights` text,
	`tenant_id` varchar(255),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`payment_method` enum('cash','bank_transfer','ecocash','onemoney','rtgs','zipit'),
	`payment_reference_number` varchar(100),
	`payment_proof_s3_key` varchar(500),
	`payment_proof_s3_url` varchar(500),
	`payment_amount` int,
	`payment_date` timestamp,
	`payment_submitted_at` timestamp,
	`payment_verified_at` timestamp,
	`payment_verified_by` int,
	`payment_rejection_reason` text,
	CONSTRAINT `insurance_quotes_id` PRIMARY KEY(`id`)
);