CREATE TABLE `vehicle_condition_assessment` (
	`id` int AUTO_INCREMENT NOT NULL,
	`claim_id` int NOT NULL,
	`assessor_id` int NOT NULL,
	`speedo_reading` int,
	`speedo_unit` enum('km','miles') DEFAULT 'km',
	`brakes_condition` enum('good','fair','poor'),
	`brakes_notes` text,
	`steering_condition` enum('good','fair','poor'),
	`steering_notes` text,
	`tires_condition` enum('good','fair','poor'),
	`tire_tread_depth_mm` int,
	`tires_notes` text,
	`suspension_condition` enum('good','fair','poor'),
	`suspension_notes` text,
	`bodywork_condition` enum('good','fair','poor'),
	`bodywork_notes` text,
	`paintwork_condition` enum('good','fair','poor'),
	`paintwork_notes` text,
	`upholstery_condition` enum('good','fair','poor'),
	`upholstery_notes` text,
	`general_mechanical` enum('good','fair','poor'),
	`mechanical_notes` text,
	`radio_present` tinyint DEFAULT 1,
	`radio_model` varchar(100),
	`token_number` varchar(100),
	`overall_condition` enum('excellent','good','fair','poor'),
	`maintenance_level` enum('well_maintained','average','poorly_maintained'),
	`has_contributory_negligence` tinyint DEFAULT 0,
	`negligence_description` text,
	`condition_photos` text,
	`assessment_date` timestamp NOT NULL DEFAULT (now()),
	`assessor_signature` varchar(500),
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `vehicle_condition_assessment_id` PRIMARY KEY(`id`)
);