CREATE TABLE `vehicle_condition_snapshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`vehicle_registry_id` int NOT NULL,
	`insurance_service_request_id` int NOT NULL,
	`vehicle_market_valuation_id` int,
	`snapshot_version` int NOT NULL,
	`snapshot_date` timestamp NOT NULL,
	`exterior_condition` varchar(50) NOT NULL,
	`interior_condition` varchar(50) NOT NULL,
	`mechanical_condition` varchar(50) NOT NULL,
	`existing_damage_notes` text,
	`tyre_condition` varchar(50),
	`glass_condition` varchar(50),
	`odometer_km` int,
	`modifications_json` json,
	`photographs_json` json,
	`evidence_sources_json` json NOT NULL,
	`observations` text,
	`assessor_notes` text,
	`captured_by` int NOT NULL,
	`tenant_id` varchar(64) NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `vehicle_condition_snapshots_id` PRIMARY KEY(`id`),
	CONSTRAINT `uq_vehicle_condition_snapshot_version` UNIQUE(`insurance_service_request_id`,`snapshot_version`)
);