CREATE TABLE `vehicle_damage_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`vehicle_id` int NOT NULL,
	`claim_id` int,
	`vehicle_registration` varchar(50),
	`damage_zone` enum('front','rear','left','right','roof','undercarriage','multiple','unknown') NOT NULL DEFAULT 'unknown',
	`damaged_components_json` longtext,
	`affected_zones_json` text,
	`impact_direction` varchar(50),
	`impact_force_kn` decimal(8,2),
	`estimated_speed_kmh` decimal(6,1),
	`severity` enum('minor','moderate','severe','total_loss','unknown') NOT NULL DEFAULT 'unknown',
	`has_structural_damage` tinyint NOT NULL DEFAULT 0,
	`airbags_deployed` tinyint NOT NULL DEFAULT 0,
	`repair_cost_estimate_cents` int NOT NULL DEFAULT 0,
	`actual_repair_cost_cents` int,
	`repairer_id` int,
	`repairer_name` varchar(255),
	`repair_date` varchar(20),
	`fraud_risk_score` int NOT NULL DEFAULT 0,
	`is_repeat_zone` tinyint NOT NULL DEFAULT 0,
	`tenant_id` varchar(255),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `vehicle_damage_history_id` PRIMARY KEY(`id`)
);