CREATE TABLE `vehicle_market_valuations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`claim_id` int,
	`vehicle_make` varchar(100) NOT NULL,
	`vehicle_model` varchar(100) NOT NULL,
	`vehicle_year` int NOT NULL,
	`vehicle_registration` varchar(50),
	`mileage` int,
	`condition` enum('excellent','good','fair','poor'),
	`estimated_market_value` int NOT NULL,
	`valuation_method` enum('facebook_marketplace','classifieds','autotrader_sa','historical_claims','manual_assessor','ai_estimation','hybrid') NOT NULL,
	`facebook_prices` text,
	`classifieds_prices` text,
	`autotrader_sa_prices` text,
	`sa_base_price` int,
	`import_duty_percent` decimal(5,2),
	`import_duty_amount` int,
	`transport_cost` int,
	`total_import_cost` int,
	`confidence_score` int,
	`data_points_count` int,
	`price_range` text,
	`condition_adjustment` int,
	`mileage_adjustment` int,
	`market_trend_adjustment` int,
	`final_adjusted_value` int,
	`is_total_loss` tinyint DEFAULT 0,
	`total_loss_threshold` decimal(5,2) DEFAULT '60.00',
	`repair_cost_to_value_ratio` decimal(5,2),
	`assessor_override` tinyint DEFAULT 0,
	`assessor_value` int,
	`assessor_justification` text,
	`valuation_date` timestamp NOT NULL DEFAULT (now()),
	`valid_until` timestamp,
	`valued_by` int,
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `vehicle_market_valuations_id` PRIMARY KEY(`id`)
);