CREATE TABLE `vehicle_passport_snapshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`vehicle_registry_id` int NOT NULL,
	`registration_number` varchar(50) NOT NULL,
	`tenant_id` varchar(255),
	`snapshot_version` int NOT NULL DEFAULT 1,
	`total_claims` int NOT NULL DEFAULT 0,
	`completed_claims` int NOT NULL DEFAULT 0,
	`open_claims` int NOT NULL DEFAULT 0,
	`total_settlement_cents` int NOT NULL DEFAULT 0,
	`avg_settlement_cents` int NOT NULL DEFAULT 0,
	`total_fraud_signals` int NOT NULL DEFAULT 0,
	`repeat_damage_signals` int NOT NULL DEFAULT 0,
	`total_damage_events` int NOT NULL DEFAULT 0,
	`repeat_zone_count` int NOT NULL DEFAULT 0,
	`distinct_damage_zones` int NOT NULL DEFAULT 0,
	`total_inspections` int NOT NULL DEFAULT 0,
	`last_claim_date` timestamp,
	`last_inspection_date` timestamp,
	`last_fraud_signal_date` timestamp,
	`intelligence_json` json,
	`generated_at` timestamp NOT NULL DEFAULT (now()),
	`generated_by` varchar(100) NOT NULL DEFAULT 'system',
	CONSTRAINT `vehicle_passport_snapshots_id` PRIMARY KEY(`id`)
);