CREATE TABLE `vehicle_registry` (
	`id` int AUTO_INCREMENT NOT NULL,
	`vin` varchar(17),
	`registration_number` varchar(30),
	`make` varchar(100),
	`model` varchar(100),
	`year` int,
	`color` varchar(50),
	`engine_number` varchar(100),
	`vehicle_type` enum('sedan','suv','pickup','van','hatchback','coupe','bus','truck','motorcycle','other'),
	`engine_capacity` varchar(20),
	`fuel_type` enum('petrol','diesel','electric','hybrid','lpg','other'),
	`powertrain_type` enum('ICE','HEV','BEV','other'),
	`vehicle_mass_kg` int,
	`vehicle_mass_source` enum('explicit','inferred_model','inferred_class','not_available') DEFAULT 'not_available',
	`current_owner_name` varchar(255),
	`first_registration_date` varchar(20),
	`licence_expiry_date` varchar(20),
	`total_claims_count` int NOT NULL DEFAULT 0,
	`total_repair_cost_cents` int NOT NULL DEFAULT 0,
	`last_claim_date` timestamp,
	`claim_ids_json` text,
	`damage_zone_counts_json` text,
	`has_suspicious_damage_pattern` tinyint NOT NULL DEFAULT 0,
	`is_repeat_claimer` tinyint NOT NULL DEFAULT 0,
	`is_salvage_title` tinyint NOT NULL DEFAULT 0,
	`is_stolen` tinyint NOT NULL DEFAULT 0,
	`is_written_off` tinyint NOT NULL DEFAULT 0,
	`vehicle_risk_score` int NOT NULL DEFAULT 0,
	`tenant_id` varchar(255),
	`first_seen_at` timestamp NOT NULL DEFAULT (now()),
	`last_seen_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `vehicle_registry_id` PRIMARY KEY(`id`),
	CONSTRAINT `vehicle_registry_vin_unique` UNIQUE(`vin`),
	CONSTRAINT `idx_vehicle_registry_vin` UNIQUE(`vin`)
);