CREATE TABLE `ai_assessments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`claim_id` int NOT NULL,
	`estimated_cost` int,
	`damage_description` longtext,
	`detected_damage_types` longtext,
	`confidence_score` int,
	`fraud_indicators` longtext,
	`fraud_risk_level` enum('low','medium','moderate','high','critical','elevated'),
	`fraud_score` int,
	`recommendation` varchar(50),
	`fraud_score_breakdown_json` longtext,
	`model_version` varchar(50),
	`processing_time` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`total_loss_indicated` tinyint DEFAULT 0,
	`structural_damage_severity` enum('none','minor','moderate','severe','catastrophic') DEFAULT 'none',
	`estimated_vehicle_value` int,
	`repair_to_value_ratio` int,
	`total_loss_reasoning` longtext,
	`damaged_components_json` longtext,
	`physics_analysis` longtext,
	`graph_urls` longtext,
	`tenant_id` varchar(255),
	`is_reanalysis` tinyint NOT NULL DEFAULT 0,
	`triggered_by` int,
	`triggered_role` varchar(50),
	`previous_assessment_id` int,
	`reanalysis_reason` longtext,
	`version_number` int NOT NULL DEFAULT 1,
	`physics_deviation_score` int,
	`forensic_analysis` longtext,
	`estimated_parts_cost` int,
	`estimated_labor_cost` int,
	`currency_code` varchar(10) DEFAULT 'USD',
	`inferred_hidden_damages_json` longtext,
	`repair_intelligence_json` longtext,
	`parts_reconciliation_json` longtext,
	`cost_intelligence_json` longtext,
	`damage_photos_json` longtext,
	`confidence_score_breakdown_json` longtext,
	`pipeline_run_summary` longtext,
	`enriched_photos_json` longtext,
	`unresolved_parts_json` longtext,
	`photo_inconsistencies_json` longtext,
	`consistency_check_json` longtext,
	`coherence_result_json` longtext,
	`cost_realism_json` longtext,
	`causal_chain_json` longtext,
	`evidence_bundle_json` longtext,
	`realism_bundle_json` longtext,
	`benchmark_bundle_json` longtext,
	`consensus_result_json` longtext,
	`causal_verdict_json` longtext,
	`constraint_overrides_json` longtext,
	`validated_outcome_json` longtext,
	`case_signature_json` longtext,
	`decision_authority_json` longtext,
	`contradiction_gate_json` longtext,
	`report_readiness_json` longtext,
	`explanation_json` longtext,
	`escalation_route_json` longtext,
	`decision_trace_json` longtext,
	`stage2_raw_ocr_text` longtext,
	`claim_record_json` longtext,
	`narrative_analysis_json` longtext,
	`direction_contradiction_flag_json` longtext,
	`cross_validation_json` longtext,
	`image_analysis_total_count` int DEFAULT 0,
	`image_analysis_success_count` int DEFAULT 0,
	`image_analysis_failed_count` int DEFAULT 0,
	`image_analysis_success_rate` int,
	`fcdi_score` int,
	`forensic_execution_ledger_json` longtext,
	`assumption_registry_json` longtext,
	`economic_context_json` longtext,
	`ife_result_json` longtext,
	`doe_result_json` longtext,
	`fel_version_snapshot_json` longtext,
	`claim_quality_json` longtext,
	`forensic_audit_validation_json` longtext,
	`shared_with_roles_json` longtext,
	`human_override` tinyint DEFAULT 0,
	`human_override_user_id` int,
	`human_override_reason` text,
	`human_override_at` bigint,
	`ocr_fallback_used` tinyint DEFAULT 0,
	`pipeline_degraded_stages_json` text,
	`photo_classification_json` longtext,
	`claim_truth_json` longtext,
	`claim_truth_object_json` longtext,
	`physics_truth_json` longtext,
	`report_signals_json` longtext,
	`evidence_registry_json` longtext,
	`system_intervention_count` int,
	`intervention_summary_json` text,
	`decision_readiness_json` longtext,
	`degradation_reasons_json` text,
	`field_validation_json` longtext,
	`gate_decision_json` longtext,
	`cgi_result_json` longtext,
	`interpretation_result_json` longtext,
	CONSTRAINT `ai_assessments_id` PRIMARY KEY(`id`)
);