CREATE TABLE `automation_policies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenant_id` varchar(255) NOT NULL,
	`policy_name` varchar(255) NOT NULL,
	`min_automation_confidence` int NOT NULL DEFAULT 85,
	`min_hybrid_confidence` int NOT NULL DEFAULT 60,
	`eligible_claim_types` json NOT NULL,
	`excluded_claim_types` json NOT NULL,
	`max_ai_only_approval_amount` bigint NOT NULL DEFAULT 5000000,
	`max_hybrid_approval_amount` bigint NOT NULL DEFAULT 20000000,
	`max_fraud_score_for_automation` int NOT NULL DEFAULT 30,
	`eligible_vehicle_categories` json NOT NULL,
	`excluded_vehicle_makes` json NOT NULL,
	`min_vehicle_year` int NOT NULL DEFAULT 2010,
	`max_vehicle_age` int NOT NULL DEFAULT 15,
	`require_manager_approval_above` bigint NOT NULL DEFAULT 10000000,
	`allow_policy_override` tinyint NOT NULL DEFAULT 1,
	`created_at` timestamp DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`created_by_user_id` int,
	`is_active` tinyint NOT NULL DEFAULT 1,
	`version` int NOT NULL DEFAULT 1,
	`effective_from` timestamp NOT NULL DEFAULT (now()),
	`effective_until` timestamp,
	`superseded_by_policy_id` int,
	`fraud_sensitivity_multiplier` decimal(3,2) NOT NULL DEFAULT '1.00',
	`demand_letter_response_days` int NOT NULL DEFAULT 21,
	CONSTRAINT `automation_policies_id` PRIMARY KEY(`id`)
);