CREATE TABLE `cost_components` (
	`id` int AUTO_INCREMENT NOT NULL,
	`historical_claim_id` int NOT NULL,
	`source_type` enum('panel_beater_quote','assessor_report','ai_estimate','final_approved') NOT NULL,
	`document_id` int,
	`labor_cost` decimal(12,2) DEFAULT '0.00',
	`parts_cost` decimal(12,2) DEFAULT '0.00',
	`paint_cost` decimal(12,2) DEFAULT '0.00',
	`materials_cost` decimal(12,2) DEFAULT '0.00',
	`sublet_cost` decimal(12,2) DEFAULT '0.00',
	`sundries` decimal(12,2) DEFAULT '0.00',
	`vat_amount` decimal(12,2) DEFAULT '0.00',
	`total_excl_vat` decimal(12,2) DEFAULT '0.00',
	`total_incl_vat` decimal(12,2) DEFAULT '0.00',
	`total_labor_hours` decimal(8,2),
	`average_labor_rate` decimal(10,2),
	`total_parts_count` int,
	`oem_parts_count` int,
	`aftermarket_parts_count` int,
	`repair_vs_replace_ratio` decimal(5,2),
	`total_betterment` decimal(12,2) DEFAULT '0.00',
	`extraction_confidence` decimal(5,4),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `cost_components_id` PRIMARY KEY(`id`)
);