CREATE TABLE `cost_learning_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`claim_id` int,
	`tenant_id` varchar(255),
	`vehicle_descriptor` varchar(255) NOT NULL,
	`vehicle_make` varchar(100),
	`vehicle_model` varchar(100),
	`vehicle_year` int,
	`vehicle_variant` varchar(100),
	`vehicle_body_type` varchar(60),
	`collision_direction` varchar(50) NOT NULL,
	`market_region` varchar(10) NOT NULL DEFAULT 'DEFAULT',
	`case_signature` varchar(100) NOT NULL,
	`component_count` int NOT NULL DEFAULT 0,
	`structural_component_count` int NOT NULL DEFAULT 0,
	`currency` varchar(10) NOT NULL DEFAULT 'USD',
	`final_cost_usd_cents` int,
	`cost_is_agreed` tinyint NOT NULL DEFAULT 0,
	`quote_coverage_ratio_pct` int NOT NULL DEFAULT 0,
	`high_cost_drivers_json` text NOT NULL DEFAULT (JSON_ARRAY()),
	`component_weighting_json` text NOT NULL DEFAULT (JSON_OBJECT()),
	`component_detail_json` text NOT NULL DEFAULT (JSON_ARRAY()),
	`quality_flags_json` text NOT NULL DEFAULT (JSON_ARRAY()),
	`recorded_at` timestamp NOT NULL DEFAULT (now()),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `cost_learning_records_id` PRIMARY KEY(`id`)
);