CREATE TABLE `ingestion_documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenant_id` varchar(64) NOT NULL,
	`batch_id` int NOT NULL,
	`document_id` varchar(36) NOT NULL,
	`original_filename` varchar(500) NOT NULL,
	`file_size_bytes` int NOT NULL,
	`mime_type` varchar(100) NOT NULL,
	`s3_bucket` varchar(255) NOT NULL,
	`s3_key` varchar(1024) NOT NULL,
	`s3_url` varchar(2048) NOT NULL,
	`sha256_hash` varchar(64) NOT NULL,
	`hash_verified` tinyint NOT NULL DEFAULT 0,
	`document_type` enum('claim_form','police_report','damage_image','repair_quote','assessor_report','supporting_evidence','unknown'),
	`classification_confidence` decimal(5,4),
	`classification_method` enum('ai_model','rule_based','manual_override'),
	`extraction_status` enum('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
	`extraction_started_at` timestamp,
	`extraction_completed_at` timestamp,
	`validation_status` enum('pending','in_review','approved','rejected') NOT NULL DEFAULT 'pending',
	`validated_by_user_id` int,
	`validated_at` timestamp,
	`page_count` int,
	`language_detected` varchar(10),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`p_hash` varchar(64),
	`historical_claim_id` int,
	CONSTRAINT `ingestion_documents_id` PRIMARY KEY(`id`)
);