CREATE TABLE `panel_beater_quotes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`claim_id` int NOT NULL,
	`panel_beater_id` int NOT NULL,
	`quoted_amount` int NOT NULL,
	`labor_cost` int,
	`parts_cost` int,
	`estimated_duration` int,
	`labor_hours` int,
	`itemized_breakdown` text,
	`notes` text,
	`modified` tinyint DEFAULT 0,
	`original_quoted_amount` int,
	`modification_reason` text,
	`modified_by_assessor_id` int,
	`panel_beater_agreed` tinyint,
	`quote_type` enum('original','strip_requote','assessor_adjusted','supplementary','revised') NOT NULL DEFAULT 'original',
	`parent_quote_id` int,
	`status` enum('draft','submitted','modified','accepted','rejected') NOT NULL DEFAULT 'draft',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`components_json` text,
	`parts_quality` enum('aftermarket','oem','genuine','used') DEFAULT 'aftermarket',
	`warranty_months` int DEFAULT 12,
	`tenant_id` varchar(255),
	`currency_code` varchar(10) DEFAULT 'USD',
	`quote_audit_json` text,
	`quote_congruency_score` decimal(5,2),
	CONSTRAINT `panel_beater_quotes_id` PRIMARY KEY(`id`)
);