CREATE TABLE `supplier_quote_line_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`quote_id` int NOT NULL,
	`part_name` varchar(255) NOT NULL,
	`part_number` varchar(100),
	`part_description` text,
	`part_category` varchar(100),
	`vehicle_make` varchar(100),
	`vehicle_model` varchar(100),
	`vehicle_year_from` int,
	`vehicle_year_to` int,
	`price` decimal(10,2) NOT NULL,
	`currency` varchar(3) NOT NULL,
	`part_type` enum('OEM','OEM_Equivalent','Aftermarket','Used','Unknown') DEFAULT 'Unknown',
	`quantity` int DEFAULT 1,
	`approved` tinyint DEFAULT 0,
	`rejection_reason` text,
	`extracted_at` timestamp NOT NULL DEFAULT (now()),
	`line_number` int,
	`shipping_cost` decimal(10,2),
	`customs_duty` decimal(10,2),
	`clearing_fees` decimal(10,2),
	`forex_charges` decimal(10,2),
	`lead_time_days` int,
	CONSTRAINT `supplier_quote_line_items_id` PRIMARY KEY(`id`)
);