/**
 * Escalation Queue Admin Page
 *
 * Three-queue view for managing claims routed by the Claims Escalation Router.
 * Each claim now shows an LLM-generated operational reason (≤12 words) and
 * structured flags produced by the Claims Escalation Reasoning Engine.
 *
 * Queues:
 *   1. AUTO_APPROVE   — low-risk claims cleared for fast-track settlement
 *   2. ADJUSTER_REVIEW — standard claims requiring manual adjuster sign-off
 *   3. FRAUD_TEAM      — high-risk / fraud-flagged claims for specialist review
 *
 * Also shows the multi-layer approval workflow queue.
 */

import { useState } from "react";
import { trpc } from "@/lib/trpc";
import DashboardLayout from "@/components/DashboardLayout";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  CheckCircle2,
  AlertTriangle,
  ShieldAlert,
  Clock,
  Loader2,
  ExternalLink,
  Users,
  RefreshCw,
  Zap,
} from "lucide-react";
import { useLocation } from "wouter";

// ─── Config ───────────────────────────────────────────────────────────────────

const QUEUE_CONFIG = {
  AUTO_APPROVE: {
    label: "Auto-Approve",
    description: "Low-risk claims that meet all criteria for fast-track settlement",
    color: "bg-green-100 text-green-700 border-green-300",
    headerColor: "bg-green-50 border-green-200",
    icon: CheckCircle2,
    iconColor: "text-green-600",
  },
  ADJUSTER_REVIEW: {
    label: "Adjuster Review",
    description: "Standard claims requiring manual assessment by an adjuster",
    color: "bg-blue-100 text-blue-700 border-blue-300",
    headerColor: "bg-blue-50 border-blue-200",
    icon: Users,
    iconColor: "text-blue-600",
  },
  FRAUD_TEAM: {
    label: "Fraud Team",
    description: "High-risk or fraud-flagged claims requiring specialist investigation",
    color: "bg-red-100 text-red-700 border-red-300",
    headerColor: "bg-red-50 border-red-200",
    icon: ShieldAlert,
    iconColor: "text-red-600",
  },
} as const;

const PRIORITY_CONFIG: Record<string, { label: string; color: string }> = {
  HIGH: { label: "High", color: "bg-red-100 text-red-700 border-red-300" },
  MEDIUM: { label: "Medium", color: "bg-yellow-100 text-yellow-700 border-yellow-300" },
  LOW: { label: "Low", color: "bg-gray-100 text-gray-600 border-gray-300" },
};

const FLAG_COLORS: Record<string, string> = {
  "Fraud Risk": "bg-red-100 text-red-700 border-red-300",
  "Structural Gaps": "bg-orange-100 text-orange-700 border-orange-300",
  "Low Evidence": "bg-yellow-100 text-yellow-700 border-yellow-300",
  "Out of Domain": "bg-purple-100 text-purple-700 border-purple-300",
  "Anomalies Detected": "bg-blue-100 text-blue-700 border-blue-300",
};

// ─── Claim Detail Row ─────────────────────────────────────────────────────────

type ClaimDetail = {
  claim_id: number | string;
  route: string;
  priority: string;
  reason: string;
  flags: string[];
  confidence: number | null;
  fraud_detected: boolean;
  routed_at: string;
  reasoning_source: string;
};

function ClaimDetailRow({
  item,
  queue,
}: {
  item: ClaimDetail;
  queue: "AUTO_APPROVE" | "ADJUSTER_REVIEW" | "FRAUD_TEAM";
}) {
  const [, navigate] = useLocation();
  const cfg = QUEUE_CONFIG[queue];
  const priorityCfg = PRIORITY_CONFIG[item.priority] ?? PRIORITY_CONFIG.MEDIUM;

  return (
    <Card className="hover:shadow-sm transition-shadow">
      <CardContent className="py-3 px-4">
        <div className="flex items-start justify-between gap-3">
          <div className="space-y-1.5 flex-1 min-w-0">
            {/* Header row */}
            <div className="flex items-center gap-2 flex-wrap">
              <span className="text-sm font-semibold">Claim #{item.claim_id}</span>
              <Badge className={`${priorityCfg.color} border text-xs`}>
                {priorityCfg.label} Priority
              </Badge>
              {item.confidence != null && (
                <Badge className={`${cfg.color} border text-xs`}>
                  {Math.round(item.confidence)}% confidence
                </Badge>
              )}
              {item.reasoning_source === "llm" && (
                <span title="Reason generated by AI Reasoning Engine">
                  <Zap className="h-3 w-3 text-yellow-500 inline" />
                </span>
              )}
            </div>

            {/* Operational reason */}
            <p className="text-sm text-foreground font-medium leading-snug">
              {item.reason}
            </p>

            {/* Flags */}
            {item.flags.length > 0 && (
              <div className="flex flex-wrap gap-1">
                {item.flags.map((flag) => (
                  <Badge
                    key={flag}
                    className={`${FLAG_COLORS[flag] ?? "bg-muted text-muted-foreground"} border text-xs`}
                  >
                    {flag}
                  </Badge>
                ))}
              </div>
            )}

            {/* Timestamp */}
            <p className="text-xs text-muted-foreground">
              Routed: {new Date(item.routed_at).toLocaleString()}
            </p>
          </div>

          <Button
            variant="outline"
            size="sm"
            className="shrink-0"
            onClick={() => navigate(`/insurer-portal/comparison/${item.claim_id}`)}
          >
            <ExternalLink className="h-3 w-3 mr-1" /> View
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}

// ─── Escalation Queue Tab ─────────────────────────────────────────────────────

function EscalationQueueTab({
  queue,
}: {
  queue: "AUTO_APPROVE" | "ADJUSTER_REVIEW" | "FRAUD_TEAM";
}) {
  const cfg = QUEUE_CONFIG[queue];
  const Icon = cfg.icon;

  const { data: summary, isLoading, refetch, isFetching } = trpc.decision.getEscalationSummary.useQuery(
    undefined,
    { refetchOnWindowFocus: false }
  );

  const claimsInQueue: ClaimDetail[] = (summary as any)?.claim_details?.filter(
    (c: ClaimDetail) => c.route === queue
  ) ?? [];

  const routeCount = {
    AUTO_APPROVE: (summary as any)?.auto_approve_count ?? 0,
    ADJUSTER_REVIEW: (summary as any)?.adjuster_review_count ?? 0,
    FRAUD_TEAM: (summary as any)?.fraud_team_count ?? 0,
  }[queue];

  return (
    <div className="space-y-4">
      {/* Queue header card */}
      <Card className={`border ${cfg.headerColor}`}>
        <CardContent className="pt-4 pb-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <Icon className={`h-5 w-5 ${cfg.iconColor}`} />
              <div>
                <p className="font-medium">{cfg.label}</p>
                <p className="text-xs text-muted-foreground">{cfg.description}</p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-2xl font-bold">{routeCount}</span>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => refetch()}
                disabled={isFetching}
              >
                <RefreshCw className={`h-3.5 w-3.5 ${isFetching ? "animate-spin" : ""}`} />
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Loading state */}
      {isLoading && (
        <div className="flex items-center justify-center py-8">
          <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
          <span className="ml-2 text-sm text-muted-foreground">Loading claims with reasoning…</span>
        </div>
      )}

      {/* Empty state */}
      {!isLoading && claimsInQueue.length === 0 && (
        <Card className="border-dashed">
          <CardContent className="py-10 text-center">
            <Icon className={`h-8 w-8 mx-auto mb-2 ${cfg.iconColor} opacity-40`} />
            <p className="text-sm text-muted-foreground">No claims in this queue</p>
            <p className="text-xs text-muted-foreground mt-1">
              Claims will appear here once they are routed by the escalation engine
            </p>
          </CardContent>
        </Card>
      )}

      {/* Claim list with per-claim reasoning */}
      {claimsInQueue.length > 0 && (
        <div className="space-y-2">
          <p className="text-xs text-muted-foreground">
            Showing {claimsInQueue.length} of {routeCount} claim{routeCount !== 1 ? "s" : ""} —
            reasons generated by the Escalation Reasoning Engine
          </p>
          {claimsInQueue.map((item) => (
            <ClaimDetailRow key={String(item.claim_id)} item={item} queue={queue} />
          ))}
        </div>
      )}
    </div>
  );
}

// ─── Approval Queue Tab ────────────────────────────────────────────────────────

function ApprovalQueueTab() {
  const [, navigate] = useLocation();

  const { data: queueData, isLoading } = trpc.approval.getApprovalQueue.useQuery(
    { limit: 100 },
    { refetchOnWindowFocus: false }
  );

  const { data: summary } = trpc.approval.getWorkflowSummary.useQuery(
    undefined,
    { refetchOnWindowFocus: false }
  );

  return (
    <div className="space-y-4">
      {/* Summary stats */}
      {summary && (
        <div className="grid grid-cols-4 gap-3">
          {[
            { label: "Total Decisions", value: summary.total_decisions, color: "text-foreground" },
            { label: "Approved", value: summary.approved_count, color: "text-green-600" },
            { label: "Rejected", value: summary.rejected_count, color: "text-red-600" },
            { label: "Returned", value: summary.returned_count, color: "text-yellow-600" },
          ].map((stat) => (
            <Card key={stat.label}>
              <CardContent className="pt-3 pb-2">
                <p className={`text-xl font-bold ${stat.color}`}>{stat.value}</p>
                <p className="text-xs text-muted-foreground">{stat.label}</p>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {/* Claims pending approval */}
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-sm">Claims Pending Approval</CardTitle>
          <CardDescription className="text-xs">
            Claims awaiting the next stage in the multi-layer approval workflow
          </CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading && (
            <div className="flex items-center justify-center py-6">
              <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
            </div>
          )}

          {!isLoading && queueData && queueData.total_pending === 0 && (
            <div className="text-center py-6">
              <CheckCircle2 className="h-8 w-8 text-green-500 mx-auto mb-2" />
              <p className="text-sm text-muted-foreground">No claims pending approval</p>
            </div>
          )}

          {!isLoading && queueData && queueData.total_pending > 0 && (
            <div className="space-y-2">
              <p className="text-xs text-muted-foreground mb-2">
                {queueData.total_pending} claim{queueData.total_pending !== 1 ? "s" : ""} pending
              </p>
              {queueData.pending_claim_ids.map((claimId) => (
                <div
                  key={claimId}
                  className="flex items-center justify-between p-2 rounded border hover:bg-muted/30 transition-colors"
                >
                  <div className="flex items-center gap-2">
                    <Clock className="h-4 w-4 text-blue-500" />
                    <span className="text-sm font-medium">Claim #{claimId}</span>
                  </div>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => navigate(`/insurer-portal/comparison/${claimId}`)}
                  >
                    <ExternalLink className="h-3 w-3 mr-1" /> Review
                  </Button>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Role breakdown */}
      {summary && summary.role_breakdown && Object.keys(summary.role_breakdown).length > 0 && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm">Decisions by Role</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              {Object.entries(summary.role_breakdown as Record<string, number>).map(([role, count]) => (
                <div key={role} className="flex items-center justify-between">
                  <span className="text-sm text-muted-foreground capitalize">
                    {role.replace(/_/g, " ")}
                  </span>
                  <Badge variant="secondary">{count}</Badge>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}

// ─── Summary KPI Row ──────────────────────────────────────────────────────────

function SummaryKPIRow() {
  const { data: summary, isLoading } = trpc.decision.getEscalationSummary.useQuery(
    undefined,
    { refetchOnWindowFocus: false }
  );

  if (isLoading) {
    return (
      <div className="grid grid-cols-3 gap-4">
        {[0, 1, 2].map((i) => (
          <Card key={i}>
            <CardContent className="py-6 flex items-center justify-center">
              <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
            </CardContent>
          </Card>
        ))}
      </div>
    );
  }

  if (!summary) return null;

  const items = [
    { queue: "AUTO_APPROVE" as const, count: summary.auto_approve_count, rate: summary.auto_approve_rate_pct },
    { queue: "ADJUSTER_REVIEW" as const, count: summary.adjuster_review_count, rate: summary.adjuster_review_rate_pct },
    { queue: "FRAUD_TEAM" as const, count: summary.fraud_team_count, rate: summary.fraud_team_rate_pct },
  ];

  return (
    <div className="grid grid-cols-3 gap-4">
      {items.map(({ queue, count, rate }) => {
        const cfg = QUEUE_CONFIG[queue];
        const Icon = cfg.icon;
        return (
          <Card key={queue} className={`border ${cfg.headerColor}`}>
            <CardContent className="pt-4 pb-3">
              <div className="flex items-center gap-3">
                <div className={`w-10 h-10 rounded-full ${cfg.headerColor} flex items-center justify-center`}>
                  <Icon className={`h-5 w-5 ${cfg.iconColor}`} />
                </div>
                <div>
                  <p className="text-2xl font-bold">{count}</p>
                  <p className="text-xs text-muted-foreground">{cfg.label} · {rate}%</p>
                </div>
              </div>
            </CardContent>
          </Card>
        );
      })}
    </div>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function EscalationQueue() {
  const [activeTab, setActiveTab] = useState<string>("auto_approve");

  return (
    <DashboardLayout>
      <div className="space-y-6 p-6">
        {/* Header */}
        <div>
          <h1 className="text-xl font-semibold">Escalation Queue</h1>
          <p className="text-sm text-muted-foreground mt-0.5">
            Claims routed by the AI Escalation Engine — each with an operational reason and risk flags
          </p>
        </div>

        {/* KPI summary */}
        <SummaryKPIRow />

        {/* Queue tabs */}
        <Tabs value={activeTab} onValueChange={setActiveTab}>
          <TabsList className="grid w-full grid-cols-4">
            <TabsTrigger value="auto_approve">Auto-Approve</TabsTrigger>
            <TabsTrigger value="adjuster_review">Adjuster Review</TabsTrigger>
            <TabsTrigger value="fraud_team">
              <AlertTriangle className="h-3.5 w-3.5 mr-1" />
              Fraud Team
            </TabsTrigger>
            <TabsTrigger value="approval_queue">Approval Queue</TabsTrigger>
          </TabsList>

          <TabsContent value="auto_approve" className="mt-4">
            <EscalationQueueTab queue="AUTO_APPROVE" />
          </TabsContent>

          <TabsContent value="adjuster_review" className="mt-4">
            <EscalationQueueTab queue="ADJUSTER_REVIEW" />
          </TabsContent>

          <TabsContent value="fraud_team" className="mt-4">
            <EscalationQueueTab queue="FRAUD_TEAM" />
          </TabsContent>

          <TabsContent value="approval_queue" className="mt-4">
            <ApprovalQueueTab />
          </TabsContent>
        </Tabs>
      </div>
    </DashboardLayout>
  );
}
