CREATE TABLE `assessor_evaluations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`claim_id` int NOT NULL,
	`assessor_id` int NOT NULL,
	`inspection_date` timestamp,
	`inspection_photos` text,
	`status` enum('pending','in_progress','completed','submitted') NOT NULL DEFAULT 'pending',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`estimated_repair_cost` int,
	`labor_cost` int,
	`parts_cost` int,
	`estimated_duration` int,
	`damage_assessment` text,
	`recommendations` text,
	`fraud_risk_level` enum('low','medium','moderate','high'),
	`tenant_id` varchar(255),
	`source_report_id` int,
	`source_report_version` int,
	`accepted_review_id` int,
	`disagrees_with_ai` tinyint DEFAULT 0,
	`ai_disagreement_reason` text,
	CONSTRAINT `assessor_evaluations_id` PRIMARY KEY(`id`)
);