CREATE TABLE `assessors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`professional_license_number` varchar(100) NOT NULL,
	`license_expiry_date` timestamp NOT NULL,
	`assessor_type` enum('insurer_owned','marketplace','hybrid') NOT NULL,
	`primary_tenant_id` varchar(64),
	`marketplace_enabled` tinyint NOT NULL DEFAULT 0,
	`marketplace_status` enum('pending_approval','active','suspended','inactive') DEFAULT 'pending_approval',
	`marketplace_onboarded_at` timestamp,
	`marketplace_bio` text,
	`marketplace_hourly_rate` decimal(10,2),
	`marketplace_availability` enum('full_time','part_time','weekends_only','on_demand') DEFAULT 'on_demand',
	`specializations` text,
	`certifications` text,
	`certification_level` enum('junior','senior','expert','master') NOT NULL,
	`years_of_experience` int,
	`service_regions` text,
	`max_travel_distance_km` int DEFAULT 50,
	`active_status` tinyint NOT NULL DEFAULT 1,
	`performance_score` decimal(5,2),
	`total_assessments_completed` int DEFAULT 0,
	`average_accuracy_score` decimal(5,2),
	`average_turnaround_hours` decimal(8,2),
	`average_rating` decimal(3,2),
	`total_ratings_count` int DEFAULT 0,
	`total_marketplace_earnings` decimal(12,2) DEFAULT '0.00',
	`pending_payout` decimal(12,2) DEFAULT '0.00',
	`last_payout_date` timestamp,
	`background_check_status` enum('pending','passed','failed') DEFAULT 'pending',
	`background_check_date` timestamp,
	`insurance_verified` tinyint DEFAULT 0,
	`insurance_expiry_date` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `assessors_id` PRIMARY KEY(`id`)
);