CREATE TABLE `asset_registry` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenant_id` varchar(255) NOT NULL,
	`asset_ref` varchar(100) NOT NULL,
	`asset_type` enum('vehicle','equipment','building','transformer','fire_system','solar_plant','wind_turbine','substation','industrial') NOT NULL,
	`asset_name` varchar(255) NOT NULL,
	`asset_description` text,
	`serial_number` varchar(100),
	`manufacturer` varchar(100),
	`model` varchar(100),
	`year_manufactured` int,
	`location_address` text,
	`location_lat` decimal(10,7),
	`location_lng` decimal(10,7),
	`owner_id` int,
	`owner_name` varchar(255),
	`vehicle_registration` varchar(50),
	`last_inspection_id` int,
	`last_inspected_at` timestamp,
	`inspection_count` int NOT NULL DEFAULT 0,
	`risk_rating` enum('low','medium','high','critical'),
	`metadata_json` json,
	`created_by` int NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `asset_registry_id` PRIMARY KEY(`id`),
	CONSTRAINT `idx_ar_ref` UNIQUE(`asset_ref`)
);