CREATE TABLE `automation_audit_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`claim_id` int,
	`tenant_id` varchar(255) NOT NULL,
	`confidence_score_id` int NOT NULL,
	`composite_confidence_score` decimal(5,2) NOT NULL,
	`routing_decision_id` int NOT NULL,
	`routed_workflow` enum('ai_only','hybrid','manual') NOT NULL,
	`routing_reason` text NOT NULL,
	`automation_policy_id` int NOT NULL,
	`policy_snapshot` json NOT NULL,
	`ai_estimated_cost` bigint NOT NULL,
	`assessor_adjusted_cost` bigint,
	`final_approved_cost` bigint,
	`cost_variance_ai_vs_final` decimal(5,2),
	`decision_made_at` timestamp NOT NULL,
	`claim_approved_at` timestamp,
	`claim_rejected_at` timestamp,
	`was_overridden` tinyint NOT NULL DEFAULT 0,
	`override_reason` text,
	`overridden_by_user_id` int,
	`created_at` timestamp DEFAULT (now()),
	CONSTRAINT `automation_audit_log_id` PRIMARY KEY(`id`)
);