CREATE TABLE `final_approval_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`historical_claim_id` int NOT NULL,
	`tenant_id` varchar(64) NOT NULL,
	`final_decision` enum('approved_repair','approved_total_loss','cash_settlement','rejected','withdrawn') NOT NULL,
	`final_approved_amount` decimal(12,2) NOT NULL,
	`final_labor_cost` decimal(12,2),
	`final_parts_cost` decimal(12,2),
	`final_paint_cost` decimal(12,2),
	`final_sublet_cost` decimal(12,2),
	`final_betterment` decimal(12,2),
	`approved_by_name` varchar(255),
	`approved_by_role` varchar(100),
	`approval_date` date,
	`assessor_name` varchar(255),
	`assessor_license_number` varchar(100),
	`assessor_estimate` decimal(12,2),
	`repair_shop_name` varchar(255),
	`actual_repair_duration` int,
	`customer_satisfaction` int,
	`approval_notes` text,
	`conditions_text` text,
	`data_source` enum('extracted_from_document','manual_entry','system_import') NOT NULL,
	`captured_by_user_id` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `final_approval_records_id` PRIMARY KEY(`id`)
);