CREATE TABLE `historical_claims` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenant_id` varchar(64) NOT NULL,
	`batch_id` int,
	`claim_reference` varchar(100),
	`policy_number` varchar(100),
	`vehicle_make` varchar(100),
	`vehicle_model` varchar(100),
	`vehicle_year` int,
	`vehicle_registration` varchar(50),
	`vehicle_vin` varchar(50),
	`vehicle_color` varchar(50),
	`incident_date` date,
	`incident_location` text,
	`incident_description` text,
	`accident_type` varchar(100),
	`estimated_speed` int,
	`claimant_name` varchar(255),
	`claimant_id_number` varchar(50),
	`claimant_contact` varchar(100),
	`total_panel_beater_quote` decimal(12,2),
	`total_assessor_estimate` decimal(12,2),
	`total_ai_estimate` decimal(12,2),
	`final_approved_cost` decimal(12,2),
	`repair_decision` enum('repair','total_loss','cash_settlement','rejected'),
	`assessor_name` varchar(255),
	`assessor_license_number` varchar(100),
	`pipeline_status` enum('pending','documents_uploaded','classification_complete','extraction_complete','ground_truth_captured','variance_calculated','complete','failed') NOT NULL DEFAULT 'pending',
	`data_quality_score` int,
	`fields_extracted` int,
	`fields_missing` int,
	`manual_corrections` int DEFAULT 0,
	`total_documents` int DEFAULT 0,
	`extraction_log` json,
	`last_error` text,
	`retry_count` int DEFAULT 0,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`replay_mode` tinyint NOT NULL DEFAULT 0,
	`last_replayed_at` timestamp,
	`replay_count` int NOT NULL DEFAULT 0,
	`damage_photos_json` json,
	CONSTRAINT `historical_claims_id` PRIMARY KEY(`id`)
);