CREATE TABLE `insurer_tenants` (
	`id` varchar(64) NOT NULL,
	`name` varchar(255) NOT NULL,
	`display_name` varchar(255) NOT NULL,
	`logo_url` text,
	`primary_color` varchar(7) DEFAULT '#10b981',
	`secondary_color` varchar(7) DEFAULT '#64748b',
	`document_naming_template` text,
	`document_retention_years` int DEFAULT 7,
	`fraud_retention_years` int DEFAULT 10,
	`require_manager_approval_above` decimal(10,2) DEFAULT '10000.00',
	`high_value_threshold` decimal(10,2) DEFAULT '10000.00',
	`auto_approve_below` decimal(10,2) DEFAULT '5000.00',
	`fraud_flag_threshold` decimal(3,2) DEFAULT '0.70',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`primary_currency` varchar(3) DEFAULT 'USD',
	`primary_currency_symbol` varchar(10) DEFAULT '$',
	`secondary_currency` varchar(3),
	`secondary_currency_symbol` varchar(10),
	`exchange_rate` decimal(10,4),
	`pricing_tier` enum('process','protect','prove') NOT NULL DEFAULT 'process',
	`monthly_platform_fee` decimal(10,2) NOT NULL DEFAULT '900.00',
	`per_claim_fee` decimal(8,2) NOT NULL DEFAULT '12.00',
	`tier_feature_flags` text,
	CONSTRAINT `insurer_tenants_id` PRIMARY KEY(`id`)
);