CREATE TABLE `maintenance_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`vehicle_id` int NOT NULL,
	`schedule_id` int,
	`tenant_id` varchar(64),
	`service_date` timestamp NOT NULL,
	`service_mileage` int,
	`service_type` varchar(255) NOT NULL,
	`service_provider` varchar(255),
	`service_location` varchar(255),
	`labor_cost` int,
	`parts_cost` int,
	`total_cost` int,
	`service_items` text,
	`parts_replaced` text,
	`invoice_url` text,
	`service_report_url` text,
	`is_compliant` tinyint DEFAULT 1,
	`was_overdue` tinyint DEFAULT 0,
	`days_overdue` int,
	`performed_by` int,
	`recorded_by` int NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`related_claim_id` int,
	`is_claim_related` tinyint NOT NULL DEFAULT 0,
	CONSTRAINT `maintenance_records_id` PRIMARY KEY(`id`)
);