CREATE TABLE `multi_reference_truth` (
	`id` int AUTO_INCREMENT NOT NULL,
	`historical_claim_id` int NOT NULL,
	`synthesized_value` decimal(10,2) NOT NULL,
	`confidence_interval` decimal(5,2),
	`photo_damage_severity_score` int,
	`panel_beater_quote_cluster_score` int,
	`regional_benchmark_score` int,
	`similar_claims_score` int,
	`fraud_probability_score` int,
	`settlement_amount_score` int,
	`photo_damage_estimate` decimal(10,2),
	`panel_beater_median` decimal(10,2),
	`regional_benchmark` decimal(10,2),
	`similar_claims_average` decimal(10,2),
	`final_settlement` decimal(10,2),
	`assessor_value` decimal(10,2),
	`assessor_deviation` decimal(5,2),
	`deviation_absolute` decimal(10,2),
	`synthesis_method` varchar(50),
	`components_used` int,
	`synthesis_quality` enum('high','medium','low'),
	`synthesized_at` timestamp NOT NULL DEFAULT (now()),
	`synthesized_by` varchar(50),
	`synthesis_explanation` text,
	CONSTRAINT `multi_reference_truth_id` PRIMARY KEY(`id`)
);