CREATE TABLE `physical_measurements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenant_id` varchar(255) NOT NULL,
	`inspection_id` int NOT NULL,
	`measurement_category` enum('vehicle_crush','structural','mechanical','electrical','fire_protection','industrial') NOT NULL,
	`measurement_type` varchar(100) NOT NULL,
	`value` decimal(15,4) NOT NULL,
	`value_min` decimal(15,4),
	`value_max` decimal(15,4),
	`unit` varchar(30) NOT NULL,
	`instrument` varchar(255),
	`measurement_method` enum('manual','laser','ai_assisted','imported','photogrammetric','ultrasonic','thermal','load_cell','other') NOT NULL DEFAULT 'manual',
	`calibration_reference` varchar(255),
	`confidence` decimal(4,3) NOT NULL DEFAULT '0.900',
	`captured_by` int NOT NULL,
	`captured_at` timestamp NOT NULL DEFAULT (now()),
	`source` varchar(50) NOT NULL DEFAULT 'ENGINEER_MEASUREMENT',
	`evidence_document_ids` json,
	`location_reference` varchar(255),
	`location_image_url` text,
	`standards_body` varchar(50),
	`standards_code` varchar(100),
	`standards_clause` varchar(100),
	`standards_description` text,
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `physical_measurements_id` PRIMARY KEY(`id`)
);