CREATE TABLE `pipeline_jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`claim_id` int NOT NULL,
	`run_id` varchar(64) NOT NULL,
	`stage_id` varchar(100) NOT NULL,
	`stage_label` varchar(255) NOT NULL,
	`stage_index` int NOT NULL DEFAULT 0,
	`tenant_id` varchar(255),
	`status` enum('running','completed','failed','skipped','degraded') NOT NULL DEFAULT 'running',
	`is_degraded` tinyint NOT NULL DEFAULT 0,
	`is_timeout` tinyint NOT NULL DEFAULT 0,
	`error_message` text,
	`duration_ms` int,
	`llm_tokens_input` int,
	`llm_tokens_output` int,
	`llm_model` varchar(100),
	`assumption_count` int NOT NULL DEFAULT 0,
	`recovery_action_count` int NOT NULL DEFAULT 0,
	`started_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`completed_at` timestamp,
	`result_json` longtext,
	CONSTRAINT `pipeline_jobs_id` PRIMARY KEY(`id`),
	CONSTRAINT `idx_pj_run_stage` UNIQUE(`run_id`,`stage_id`)
);