CREATE TABLE `quotation_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`request_number` varchar(50) NOT NULL,
	`tenant_id` varchar(255),
	`user_id` int,
	`full_name` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50),
	`id_number` varchar(20),
	`insurance_type` enum('comprehensive','third_party','third_party_fire_theft','fleet','commercial') NOT NULL,
	`vehicle_make` varchar(100) NOT NULL,
	`vehicle_model` varchar(100) NOT NULL,
	`vehicle_year` int NOT NULL,
	`vehicle_registration` varchar(50),
	`vehicle_vin` varchar(50),
	`vehicle_value` int,
	`vehicle_usage` enum('private','business','both') DEFAULT 'private',
	`driver_age` int,
	`driver_license_years` int,
	`claims_history` int DEFAULT 0,
	`excess_amount` int,
	`additional_cover` text,
	`documents` text,
	`quoted_premium` int,
	`quoted_annual_premium` int,
	`quoted_excess` int,
	`quote_valid_until` timestamp,
	`quote_notes` text,
	`status` enum('pending','under_review','quoted','accepted','rejected','expired') NOT NULL DEFAULT 'pending',
	`assigned_agent_id` int,
	`vehicle_forensics_json` longtext,
	`vehicle_risk_score` int,
	`vehicle_forensics_status` enum('pending','processing','complete','failed'),
	`report_gating_status` enum('teaser','full','paid') NOT NULL DEFAULT 'teaser',
	`report_unlocked_at` timestamp,
	`is_standalone_valuation` tinyint NOT NULL DEFAULT 0,
	`payment_intent_id` varchar(255),
	`inspection_required` tinyint NOT NULL DEFAULT 0,
	`inspection_assigned_to` int,
	`fleet_vehicle_count` int,
	`submission_token` varchar(64),
	`contact_verified` tinyint NOT NULL DEFAULT 0,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `quotation_requests_id` PRIMARY KEY(`id`)
);