CREATE TABLE `service_providers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`provider_name` varchar(255) NOT NULL,
	`provider_type` enum('panel_beater','mechanic','dealership','specialist') NOT NULL,
	`contact_person` varchar(255),
	`email` varchar(320),
	`phone` varchar(20),
	`address` text,
	`city` varchar(100),
	`region` varchar(100),
	`specializations` text,
	`certifications` text,
	`average_rating` decimal(3,2),
	`total_jobs_completed` int DEFAULT 0,
	`average_completion_time` decimal(6,2),
	`average_cost_deviation` decimal(5,2),
	`on_time_completion_rate` decimal(5,2),
	`is_active` tinyint DEFAULT 1,
	`is_verified` tinyint DEFAULT 0,
	`verified_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `service_providers_id` PRIMARY KEY(`id`)
);