CREATE TABLE `third_party_vehicles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`claim_id` int NOT NULL,
	`make` varchar(100),
	`model` varchar(100),
	`year` int,
	`registration` varchar(50),
	`vin` varchar(17),
	`color` varchar(50),
	`owner_name` varchar(200),
	`owner_contact` varchar(100),
	`owner_address` text,
	`driver_name` varchar(200),
	`driver_license` varchar(100),
	`insurance_company` varchar(200),
	`policy_number` varchar(100),
	`damage_description` longtext,
	`damage_photos` text,
	`estimated_repair_cost` int,
	`market_value` int,
	`market_value_source` varchar(255),
	`market_value_confidence` enum('low','medium','high'),
	`liability_percentage` int DEFAULT 0,
	`compensation_amount` int,
	`compensation_type` enum('repair','cash','total_loss'),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `third_party_vehicles_id` PRIMARY KEY(`id`)
);