CREATE TABLE `training_data_scores` (
	`id` int AUTO_INCREMENT NOT NULL,
	`historical_claim_id` int NOT NULL,
	`tenant_id` varchar(64),
	`training_confidence_score` decimal(5,2) NOT NULL,
	`training_confidence_category` enum('HIGH','MEDIUM','LOW') NOT NULL,
	`assessor_report_score` decimal(5,2) DEFAULT '0.00',
	`supporting_photos_score` decimal(5,2) DEFAULT '0.00',
	`panel_beater_quotes_score` decimal(5,2) DEFAULT '0.00',
	`evidence_completeness_score` decimal(5,2) DEFAULT '0.00',
	`handwritten_adjustments_score` decimal(5,2) DEFAULT '0.00',
	`fraud_markers_score` decimal(5,2) DEFAULT '0.00',
	`dispute_history_score` decimal(5,2) DEFAULT '0.00',
	`competing_quotes_score` decimal(5,2) DEFAULT '0.00',
	`scoring_algorithm_version` varchar(20),
	`scoring_notes` text,
	`anomaly_detected` tinyint DEFAULT 0,
	`anomaly_reason` text,
	`bias_risk_detected` tinyint DEFAULT 0,
	`bias_risk_reason` text,
	`scored_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `training_data_scores_id` PRIMARY KEY(`id`)
);