/**
 * Physics Analysis Types and Validation
 * 
 * Defines TypeScript interfaces and Zod schemas for quantitative physics analysis data.
 */

import { z } from 'zod';

// ============================================================
// TYPESCRIPT INTERFACES
// ============================================================

/**
 * Normalized impact location coordinates
 * Both x and y must be between 0 and 1 (relative to vehicle dimensions)
 */
export interface ImpactLocationNormalized {
  relativeX: number; // 0 = left edge, 1 = right edge
  relativeY: number; // 0 = front, 1 = rear
}

/**
 * Legacy qualitative physics analysis fields
 * Maintained for backward compatibility
 */
export interface LegacyPhysicsFields {
  primaryImpactZone?: string;
  impactSeverity?: string;
  damageConsistency?: string;
  physicsConsistency?: string;
  speedEstimate?: string;
  impactDirection?: string;
}

/**
 * Quantitative physics analysis structure
 * Generated by extendPhysicsValidationOutput()
 */
export interface QuantitativePhysicsFields {
  /** Impact angle in degrees (0-360°, where 0° = head-on frontal) */
  impactAngleDegrees?: number;
  
  /** Calculated impact force in kilonewtons (kN) */
  calculatedImpactForceKN?: number;
  
  /** Normalized impact location on vehicle */
  impactLocationNormalized?: ImpactLocationNormalized;
  
  /** Crush depth in meters */
  crushDepthMeters?: number;
  
  /** Estimated speed at impact in km/h */
  speedEstimateKmh?: number;
  
  /** Flag indicating quantitative mode is active */
  quantitativeMode?: boolean;
}

/**
 * Complete physics analysis structure
 * Combines legacy qualitative fields with quantitative fields
 */
export interface PhysicsAnalysis extends LegacyPhysicsFields, QuantitativePhysicsFields {}

// ============================================================
// ZOD VALIDATION SCHEMAS
// ============================================================

/**
 * Zod schema for impact location coordinates
 */
export const impactLocationNormalizedSchema = z.object({
  relativeX: z.number()
    .min(0, 'relativeX must be >= 0')
    .max(1, 'relativeX must be <= 1')
    .describe('Normalized X coordinate (0 = left, 1 = right)'),
  relativeY: z.number()
    .min(0, 'relativeY must be >= 0')
    .max(1, 'relativeY must be <= 1')
    .describe('Normalized Y coordinate (0 = front, 1 = rear)'),
});

/**
 * Zod schema for legacy qualitative physics fields
 */
export const legacyPhysicsFieldsSchema = z.object({
  primaryImpactZone: z.string().optional(),
  impactSeverity: z.string().optional(),
  damageConsistency: z.string().optional(),
  physicsConsistency: z.string().optional(),
  speedEstimate: z.string().optional(),
  impactDirection: z.string().optional(),
});

/**
 * Zod schema for quantitative physics fields
 * Enforces strict validation rules to prevent malformed data
 */
export const quantitativePhysicsFieldsSchema = z.object({
  impactAngleDegrees: z.number()
    .min(0, 'impactAngleDegrees must be >= 0')
    .max(360, 'impactAngleDegrees must be <= 360')
    .describe('Impact angle in degrees (0-360°)')
    .optional(),
  
  calculatedImpactForceKN: z.number()
    .positive('calculatedImpactForceKN must be > 0')
    .describe('Calculated impact force in kilonewtons')
    .optional(),
  
  impactLocationNormalized: impactLocationNormalizedSchema
    .describe('Normalized impact location coordinates')
    .optional(),
  
  crushDepthMeters: z.number()
    .nonnegative('crushDepthMeters must be >= 0')
    .describe('Crush depth in meters')
    .optional(),
  
  speedEstimateKmh: z.number()
    .nonnegative('speedEstimateKmh must be >= 0')
    .describe('Estimated speed at impact in km/h')
    .optional(),
  
  quantitativeMode: z.boolean()
    .describe('Flag indicating quantitative mode is active')
    .optional(),
});

/**
 * Complete physics analysis Zod schema
 * Combines legacy and quantitative fields
 */
export const physicsAnalysisSchema = legacyPhysicsFieldsSchema
  .merge(quantitativePhysicsFieldsSchema)
  .describe('Complete physics analysis structure');

// ============================================================
// HELPER FUNCTIONS
// ============================================================

/**
 * Safely parse physics analysis JSON string
 * 
 * @param json - JSON string to parse
 * @returns Parsed and validated PhysicsAnalysis object, or empty object on failure
 */
export function parsePhysicsAnalysis(json: string | null | undefined): PhysicsAnalysis {
  // Handle null/undefined input
  if (!json) {
    return {};
  }
  
  try {
    // Parse JSON string
    const parsed = JSON.parse(json);
    
    // Validate against schema (non-strict mode - allows extra fields)
    const validated = physicsAnalysisSchema.safeParse(parsed);
    
    if (validated.success) {
      return validated.data;
    } else {
      // Log validation warnings but return parsed data anyway (graceful degradation)
      console.warn('[Physics] Validation warnings:', validated.error.issues);
      return parsed as PhysicsAnalysis;
    }
  } catch (error) {
    // JSON parse error - return empty object
    console.error('[Physics] Failed to parse physics analysis JSON:', error);
    return {};
  }
}

/**
 * Validate physics analysis data before database insert
 * 
 * @param data - Physics analysis data to validate
 * @returns Validation result with success flag and error messages
 */
export function validatePhysicsAnalysis(data: unknown): {
  success: boolean;
  data?: PhysicsAnalysis;
  errors?: string[];
} {
  const result = physicsAnalysisSchema.safeParse(data);
  
  if (result.success) {
    return {
      success: true,
      data: result.data,
    };
  } else {
    return {
      success: false,
      errors: result.error.issues.map((err: any) => `${err.path.join('.')}: ${err.message}`),
    };
  }
}

/**
 * Check if physics analysis has quantitative fields populated
 * 
 * @param physics - Physics analysis object to check
 * @returns True if quantitative fields are present
 */
export function hasQuantitativePhysics(physics: PhysicsAnalysis): boolean {
  return !!(
    physics.quantitativeMode === true &&
    (physics.impactAngleDegrees !== undefined ||
     physics.calculatedImpactForceKN !== undefined ||
     physics.impactLocationNormalized !== undefined)
  );
}

/**
 * Get quantitative physics activation rate from array of physics analyses
 * 
 * @param physicsArray - Array of physics analysis objects
 * @returns Percentage (0-100) of analyses with quantitative physics
 */
export function getQuantitativeActivationRate(physicsArray: PhysicsAnalysis[]): number {
  if (physicsArray.length === 0) {
    return 0;
  }
  
  const quantitativeCount = physicsArray.filter(hasQuantitativePhysics).length;
  return (quantitativeCount / physicsArray.length) * 100;
}
