CREATE TABLE `assessor_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`claim_id` int NOT NULL,
	`tenant_id` varchar(255) NOT NULL,
	`assessor_user_id` int NOT NULL,
	`assignment_id` int NOT NULL,
	`parent_report_id` int,
	`version_number` int NOT NULL DEFAULT 1,
	`creation_method` enum('native_upload','kinga_assisted') NOT NULL,
	`status` enum('draft','attested','submitted','under_review','returned','rejected','accepted','superseded') NOT NULL DEFAULT 'draft',
	`title` varchar(255) NOT NULL,
	`source_file_name` varchar(500),
	`source_storage_key` varchar(500),
	`source_file_url` text,
	`source_mime_type` varchar(255),
	`source_file_hash` varchar(128),
	`report_payload` json,
	`kinga_extraction_json` json,
	`attested_by_user_id` int,
	`attested_at` timestamp,
	`submitted_at` timestamp,
	`superseded_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `assessor_reports_id` PRIMARY KEY(`id`),
	CONSTRAINT `uq_assessor_reports_claim_version` UNIQUE(`claim_id`,`version_number`)
);