CREATE TABLE `extracted_document_data` (
	`id` int AUTO_INCREMENT NOT NULL,
	`document_id` int NOT NULL,
	`policy_number` varchar(100),
	`claim_number` varchar(100),
	`insured_name` varchar(255),
	`insured_id_number` varchar(50),
	`insured_phone` varchar(50),
	`insured_email` varchar(320),
	`insured_address` text,
	`incident_date` date,
	`incident_time` time,
	`incident_location` text,
	`incident_description` text,
	`vehicle_make` varchar(100),
	`vehicle_model` varchar(100),
	`vehicle_year` int,
	`vehicle_vin` varchar(50),
	`vehicle_license_plate` varchar(20),
	`vehicle_mass` int,
	`repair_cost_estimate` decimal(10,2),
	`repair_parts_list` json,
	`repair_labor_hours` decimal(6,2),
	`repair_labor_rate` decimal(10,2),
	`assessor_name` varchar(255),
	`assessor_license_number` varchar(100),
	`assessor_observations` text,
	`damage_severity` enum('minor','moderate','severe','total_loss'),
	`extraction_confidence` decimal(5,4),
	`fields_extracted_count` int,
	`fields_missing_count` int,
	`full_text` longtext,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `extracted_document_data_id` PRIMARY KEY(`id`)
);