CREATE TABLE `fraud_indicators` (
	`id` int AUTO_INCREMENT NOT NULL,
	`claim_id` int NOT NULL,
	`overall_fraud_score` int NOT NULL,
	`fraud_risk_level` enum('low','medium','moderate','high','critical','elevated') NOT NULL,
	`delayed_submission_days` int,
	`delayed_submission_score` int,
	`is_non_owner_driver` tinyint DEFAULT 0,
	`non_owner_driver_score` int,
	`is_sole_party_night_accident` tinyint DEFAULT 0,
	`sole_party_night_score` int,
	`policy_age_days` int,
	`new_policy_write_off_score` int,
	`previous_insurer_count` int,
	`insurer_hopping_score` int,
	`claimant_history_score` int,
	`quote_similarity_score` int,
	`has_copy_quotations` tinyint DEFAULT 0,
	`inflated_parts_cost_score` int,
	`inflated_labor_time_score` int,
	`exaggerated_damage_score` int,
	`replacement_vs_repair_ratio` int,
	`replacement_ratio_score` int,
	`damage_scope_creep_score` int,
	`assessor_collusion_score` int,
	`assessor_bias_score` int,
	`rubber_stamping_score` int,
	`photo_metadata_score` int,
	`reused_photo_score` int,
	`document_consistency_score` int,
	`staged_accident_score` int,
	`geographic_risk_score` int,
	`temporal_anomaly_score` int,
	`detected_patterns` text,
	`fraud_evidence` text,
	`requires_investigation` tinyint NOT NULL DEFAULT 0,
	`investigation_priority` enum('low','medium','high','urgent'),
	`investigation_status` enum('pending','in_progress','completed','closed') DEFAULT 'pending',
	`investigation_notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`tenant_id` varchar(255),
	CONSTRAINT `fraud_indicators_id` PRIMARY KEY(`id`)
);