CREATE TABLE `insurer_quote_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`claim_id` int NOT NULL,
	`insurer_tenant_id` varchar(64) NOT NULL,
	`agency_tenant_id` varchar(64) NOT NULL,
	`status` enum('pending','sent','quoted','accepted','rejected','expired') NOT NULL DEFAULT 'pending',
	`quote_amount` decimal(12,2),
	`quote_currency` varchar(10) DEFAULT 'USD',
	`quote_notes` text,
	`quote_valid_until` timestamp,
	`sent_at` timestamp,
	`quoted_at` timestamp,
	`responded_at` timestamp,
	`request_type` enum('standard_claim','fleet_policy') NOT NULL DEFAULT 'standard_claim',
	`claim_source` varchar(50) NOT NULL DEFAULT 'direct',
	`fleet_account_id` int,
	`vehicle_count` int,
	`estimated_total_value` decimal(14,2),
	`claims_history_summary` text,
	`commission_estimate` decimal(12,2),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `insurer_quote_requests_id` PRIMARY KEY(`id`),
	CONSTRAINT `unique_claim_insurer_quote` UNIQUE(`claim_id`,`insurer_tenant_id`)
);