CREATE TABLE `police_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`claim_id` int NOT NULL,
	`report_number` varchar(100) NOT NULL,
	`police_station` varchar(200),
	`officer_name` varchar(200),
	`officer_badge_number` varchar(100),
	`report_date` timestamp,
	`reported_speed` int,
	`reported_weather` varchar(100),
	`reported_road_condition` varchar(100),
	`reported_visibility` varchar(100),
	`accident_location` text,
	`accident_description` text,
	`violations_issued` text,
	`citation_numbers` text,
	`witness_statements` text,
	`witness_count` int DEFAULT 0,
	`police_photos` text,
	`accident_diagram` varchar(500),
	`report_document_url` varchar(500),
	`speed_discrepancy` int,
	`location_mismatch` tinyint DEFAULT 0,
	`weather_mismatch` tinyint DEFAULT 0,
	`description_inconsistent` tinyint DEFAULT 0,
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`road_surface` varchar(100),
	`vehicle1_mass` int,
	`vehicle2_mass` int,
	`skid_mark_length` decimal(10,2),
	`impact_speed` int,
	`road_gradient` decimal(5,2),
	`lighting_condition` varchar(100),
	`traffic_condition` varchar(100),
	`ocr_extracted` tinyint DEFAULT 0,
	`ocr_confidence` int,
	`ocr_notes` text,
	CONSTRAINT `police_reports_id` PRIMARY KEY(`id`)
);