/**
 * Role Assignment Audit Trail Service
 * 
 * Provides immutable audit logging for all role assignment changes with:
 * - Insert-only operations (no update/delete)
 * - Strict tenant isolation
 * - Automatic logging on role changes
 * - Comprehensive audit trail retrieval
 */

import { getDb } from "../db";
import { roleAssignmentAudit, users } from "../../drizzle/schema";
import { eq, and, desc } from "drizzle-orm";

/**
 * Role assignment change data
 */
export interface RoleAssignmentChange {
  tenantId: string;
  userId: number;
  previousRole: "user" | "admin" | "insurer" | "assessor" | "panel_beater" | "claimant" | null;
  newRole: "user" | "admin" | "insurer" | "assessor" | "panel_beater" | "claimant";
  previousInsurerRole?: "claims_processor" | "assessor_internal" | "assessor_external" | "risk_manager" | "claims_manager" | "executive" | "insurer_admin" | null;
  newInsurerRole?: "claims_processor" | "assessor_internal" | "assessor_external" | "risk_manager" | "claims_manager" | "executive" | "insurer_admin" | null;
  changedByUserId: number;
  justification?: string;
}

/**
 * Log a role assignment change to the audit trail
 * 
 * This function enforces:
 * - Insert-only (immutable records)
 * - Tenant isolation verification
 * - Timestamp immutability
 * 
 * @param change - Role assignment change details
 * @returns The created audit entry
 * @throws Error if tenant isolation is violated or database operation fails
 */
export async function logRoleAssignment(change: RoleAssignmentChange) {
  const db = await getDb();
  if (!db) throw new Error("Database not available");

  // Verify tenant isolation: ensure the user being changed belongs to the specified tenant
  const targetUser = await db
    .select({ tenantId: users.tenantId })
    .from(users)
    .where(eq(users.id, change.userId))
    .limit(1);

  if (targetUser.length === 0) {
    throw new Error(`User ${change.userId} not found`);
  }

  if (targetUser[0].tenantId !== change.tenantId) {
    throw new Error(
      `Tenant isolation violation: User ${change.userId} belongs to tenant ${targetUser[0].tenantId}, not ${change.tenantId}`
    );
  }

  // Verify the actor belongs to the same tenant
  const actorUser = await db
    .select({ tenantId: users.tenantId })
    .from(users)
    .where(eq(users.id, change.changedByUserId))
    .limit(1);

  if (actorUser.length === 0) {
    throw new Error(`Actor user ${change.changedByUserId} not found`);
  }

  if (actorUser[0].tenantId !== change.tenantId) {
    throw new Error(
      `Tenant isolation violation: Actor ${change.changedByUserId} belongs to tenant ${actorUser[0].tenantId}, not ${change.tenantId}`
    );
  }

  // Insert audit entry (immutable - no updates allowed)
  const result = await db.insert(roleAssignmentAudit).values({
    tenantId: change.tenantId,
    userId: change.userId,
    previousRole: change.previousRole,
    newRole: change.newRole,
    previousInsurerRole: change.previousInsurerRole ?? null,
    newInsurerRole: change.newInsurerRole ?? null,
    changedByUserId: change.changedByUserId,
    justification: change.justification ?? null,
    // timestamp is auto-generated by database
  });

  // Return the created entry
  const auditId = Number(result[0].insertId);
  const auditEntry = await db
    .select()
    .from(roleAssignmentAudit)
    .where(eq(roleAssignmentAudit.id, auditId))
    .limit(1);

  return auditEntry[0];
}

/**
 * Get audit trail for a specific user with tenant isolation
 * 
 * @param userId - User ID to get audit trail for
 * @param tenantId - Tenant ID for isolation enforcement
 * @returns Array of audit entries for the user
 */
export async function getUserAuditTrail(userId: number, tenantId: string) {
  const db = await getDb();
  if (!db) throw new Error("Database not available");

  // Enforce tenant isolation
  const entries = await db
    .select()
    .from(roleAssignmentAudit)
    .where(
      and(
        eq(roleAssignmentAudit.userId, userId),
        eq(roleAssignmentAudit.tenantId, tenantId)
      )
    )
    .orderBy(desc(roleAssignmentAudit.timestamp));

  return entries;
}

/**
 * Get audit trail for an entire tenant
 * 
 * @param tenantId - Tenant ID to get audit trail for
 * @param limit - Maximum number of entries to return (default: 100)
 * @returns Array of audit entries for the tenant
 */
export async function getTenantAuditTrail(tenantId: string, limit: number = 100) {
  const db = await getDb();
  if (!db) throw new Error("Database not available");

  const entries = await db
    .select()
    .from(roleAssignmentAudit)
    .where(eq(roleAssignmentAudit.tenantId, tenantId))
    .orderBy(desc(roleAssignmentAudit.timestamp))
    .limit(limit);

  return entries;
}

/**
 * Get audit trail for changes made by a specific user
 * 
 * @param changedByUserId - User ID who made the changes
 * @param tenantId - Tenant ID for isolation enforcement
 * @returns Array of audit entries for changes made by the user
 */
export async function getAuditTrailByActor(changedByUserId: number, tenantId: string) {
  const db = await getDb();
  if (!db) throw new Error("Database not available");

  const entries = await db
    .select()
    .from(roleAssignmentAudit)
    .where(
      and(
        eq(roleAssignmentAudit.changedByUserId, changedByUserId),
        eq(roleAssignmentAudit.tenantId, tenantId)
      )
    )
    .orderBy(desc(roleAssignmentAudit.timestamp));

  return entries;
}

/**
 * Verify that audit entries are immutable (no update/delete operations)
 * 
 * This is enforced at the service layer - the database schema allows updates,
 * but this service only provides insert and select operations.
 * 
 * For additional security, database triggers or permissions should be configured
 * to prevent direct UPDATE/DELETE operations on the role_assignment_audit table.
 */
