/**
 * ForensicAuditReport — v7 Server-Rendered Browser View
 *
 * Renders the KINGA Forensic Claim Decision Report by calling the server-side
 * v7 HTML generator via the `reportingEngine.previewHtml` tRPC procedure.
 * The browser view and the PDF download are generated by the same code,
 * ensuring visual and content parity at all times.
 *
 * The old client-side React renderer (v4.2, ~9,500 lines) has been retired.
 * All future report design changes should be made in:
 *   server/reporting/forensicDecisionReport.ts
 */
import React, { useEffect, useRef, useState } from "react";
import { trpc } from "@/lib/trpc";
import { Loader2, AlertTriangle } from "lucide-react";

interface ForensicAuditReportProps {
  claimId?: number | string;
  /** All legacy props are accepted but ignored — kept for call-site compatibility */
  [key: string]: unknown;
}

export function ForensicAuditReport({ claimId }: ForensicAuditReportProps) {
  const numericClaimId = Number(claimId);
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const [iframeHeight, setIframeHeight] = useState(1200);

  const { data, isLoading, error } = trpc.reportingEngine.previewHtml.useQuery(
    { reportKey: "claim.forensic", claimId: numericClaimId },
    {
      enabled: !!numericClaimId && numericClaimId > 0,
      staleTime: 5 * 60 * 1000,
      retry: 1,
    }
  );

  useEffect(() => {
    if (!data?.html || !iframeRef.current) return;
    const doc = iframeRef.current.contentDocument;
    if (!doc) return;
    doc.open();
    doc.write(data.html);
    doc.close();
    const resize = () => {
      try {
        const body = iframeRef.current?.contentDocument?.body;
        if (body) setIframeHeight(Math.max(body.scrollHeight + 40, 1200));
      } catch { /* cross-origin guard */ }
    };
    const t = setTimeout(resize, 400);
    return () => clearTimeout(t);
  }, [data?.html]);

  if (isLoading) {
    return (
      <div className="flex flex-col items-center justify-center py-24 gap-4">
        <Loader2 className="h-8 w-8 animate-spin" style={{ color: "var(--primary)" }} />
        <p className="text-sm" style={{ color: "var(--muted-foreground)" }}>
          Generating Forensic Audit Report…
        </p>
        <p className="text-xs" style={{ color: "var(--muted-foreground)" }}>
          This may take a few seconds
        </p>
      </div>
    );
  }

  if (error || !data?.html) {
    return (
      <div className="flex flex-col items-center justify-center py-24 gap-3">
        <AlertTriangle className="h-8 w-8" style={{ color: "var(--destructive)" }} />
        <p className="text-sm font-medium" style={{ color: "var(--foreground)" }}>
          Unable to generate Forensic Audit Report
        </p>
        <p className="text-xs" style={{ color: "var(--muted-foreground)" }}>
          {error?.message ?? "The report could not be generated. Ensure the KINGA analysis has completed."}
        </p>
      </div>
    );
  }

  return (
    <div style={{ width: "100%", background: "#fff" }}>
      <iframe
        ref={iframeRef}
        title="KINGA Forensic Audit Report"
        style={{
          width: "100%",
          height: `${iframeHeight}px`,
          border: "none",
          display: "block",
          background: "#fff",
        }}
        sandbox="allow-scripts allow-same-origin"
      />
    </div>
  );
}

export default ForensicAuditReport;
