CREATE TABLE `agency_insurance_service_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`request_number` varchar(50) NOT NULL,
	`agency_tenant_id` varchar(64) NOT NULL,
	`agency_client_id` int NOT NULL,
	`vehicle_registry_id` int,
	`cover_type` enum('comprehensive','third_party','third_party_fire_theft','commercial','other') NOT NULL,
	`status` enum('draft','awaiting_client_acknowledgement','ready_for_insurer_review','under_insurer_review','closed','withdrawn') NOT NULL DEFAULT 'draft',
	`client_instruction` text NOT NULL,
	`vehicle_risk_notes` text,
	`vehicle_registration` varchar(50),
	`vehicle_make` varchar(100),
	`vehicle_model` varchar(100),
	`vehicle_year` int,
	`vehicle_vin` varchar(50),
	`vehicle_mileage_km` int,
	`client_proposed_value_cents` int,
	`kinga_market_valuation_cents` int,
	`valuation_date` timestamp,
	`valuation_provenance_json` json,
	`variance_percent` decimal(7,2),
	`client_acknowledgement_json` json,
	`created_by` int NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `agency_insurance_service_requests_id` PRIMARY KEY(`id`),
	CONSTRAINT `uq_agency_insurance_service_request_number` UNIQUE(`request_number`)
);