CREATE TABLE `approval_workflow` (
	`id` int AUTO_INCREMENT NOT NULL,
	`claim_id` int NOT NULL,
	`level` enum('assessor','risk_surveyor','risk_manager') NOT NULL,
	`level_order` int NOT NULL,
	`approver_id` int,
	`approver_name` varchar(200),
	`approver_role` varchar(100),
	`status` enum('pending','approved','rejected','returned') NOT NULL DEFAULT 'pending',
	`approved_amount` int,
	`comments` text,
	`conditions` text,
	`rejection_reason` text,
	`return_reason` text,
	`return_to_level` enum('assessor','risk_surveyor'),
	`submitted_at` timestamp,
	`reviewed_at` timestamp,
	`approval_date` timestamp,
	`is_escalated` tinyint DEFAULT 0,
	`escalation_reason` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `approval_workflow_id` PRIMARY KEY(`id`)
);