CREATE TABLE `claim_comments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`claimId` int NOT NULL,
	`author_user_id` int NOT NULL,
	`author_role` varchar(50) NOT NULL,
	`to_roles` text NOT NULL DEFAULT (JSON_ARRAY()),
	`to_user_ids` text NOT NULL DEFAULT (JSON_ARRAY()),
	`to_emails` text NOT NULL DEFAULT (JSON_ARRAY()),
	`comment_type` enum('clarification','instruction','escalation','approval_note','rejection_note','inspection_request','general') NOT NULL DEFAULT 'general',
	`requires_response` tinyint NOT NULL DEFAULT 0,
	`response_deadline_at` varchar(50),
	`body` text NOT NULL,
	`parent_comment_id` int,
	`is_resolved` tinyint NOT NULL DEFAULT 0,
	`resolved_by_user_id` int,
	`resolved_at` varchar(50),
	`email_sent` tinyint NOT NULL DEFAULT 0,
	`notify_claimant` tinyint NOT NULL DEFAULT 0,
	`claimant_email_sent` tinyint NOT NULL DEFAULT 0,
	`status_update_template` varchar(100),
	`createdAt` text NOT NULL,
	`tenant_id` varchar(255),
	`deletedAt` text,
	`section_key` varchar(100),
	`subsection_key` varchar(100),
	`finding_id` varchar(100),
	`pipeline_run_id` int,
	`severity` varchar(20) NOT NULL DEFAULT 'info',
	`disposition` varchar(30),
	`blocks_approval` tinyint NOT NULL DEFAULT 0,
	CONSTRAINT `claim_comments_id` PRIMARY KEY(`id`)
);