CREATE TABLE `client_vehicle_valuation_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`request_number` varchar(50) NOT NULL,
	`user_id` int,
	`full_name` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50),
	`vehicle_make` varchar(100) NOT NULL,
	`vehicle_model` varchar(100) NOT NULL,
	`vehicle_year` int NOT NULL,
	`vehicle_registration` varchar(50),
	`vehicle_vin` varchar(50),
	`mileage` int,
	`condition` enum('excellent','good','fair','poor') NOT NULL,
	`photo_urls_json` longtext,
	`registration_book_url` text,
	`status` enum('pending','processing','complete','review_required','failed') NOT NULL DEFAULT 'pending',
	`submission_token` varchar(64) NOT NULL,
	`kinga_market_valuation_cents` int,
	`valuation_provenance_json` longtext,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `client_vehicle_valuation_requests_id` PRIMARY KEY(`id`)
);