CREATE TABLE `engineer_observations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenant_id` varchar(255) NOT NULL,
	`inspection_id` int NOT NULL,
	`observation_type` enum('defect','hazard','compliance','maintenance','recommendation','general_note') NOT NULL DEFAULT 'general_note',
	`observation_mode` enum('structured','free_text','voice') NOT NULL DEFAULT 'free_text',
	`component` varchar(255),
	`condition_code` varchar(50),
	`condition_detail` text,
	`observation_text` text,
	`voice_audio_url` text,
	`voice_transcript` text,
	`transcription_language` varchar(10) DEFAULT 'en',
	`severity` enum('info','minor','moderate','major','critical') NOT NULL DEFAULT 'info',
	`recommendation` text,
	`standards_body` varchar(50),
	`standards_code` varchar(100),
	`standards_clause` varchar(100),
	`standards_description` text,
	`linked_measurement_ids` json,
	`linked_evidence_ids` json,
	`ai_draft_used` tinyint NOT NULL DEFAULT 0,
	`ai_draft_approved` tinyint NOT NULL DEFAULT 0,
	`ai_draft_prompt` text,
	`authored_by` int NOT NULL,
	`authored_at` timestamp NOT NULL DEFAULT (now()),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `engineer_observations_id` PRIMARY KEY(`id`)
);