CREATE TABLE `recovery_cases` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenant_id` varchar(64) NOT NULL,
	`claim_id` int NOT NULL,
	`recovery_potential_score` int NOT NULL DEFAULT 0,
	`wronged_party` enum('insured','third_party','shared','unknown') NOT NULL DEFAULT 'unknown',
	`third_party_liability_pct` int DEFAULT 0,
	`third_party_name` varchar(255),
	`third_party_registration` varchar(50),
	`third_party_insurer` varchar(255),
	`third_party_policy_number` varchar(100),
	`third_party_contact_details` text,
	`third_party_insurer_address` text,
	`third_party_insurer_contact` varchar(255),
	`third_party_insurer_policy_ref` varchar(100),
	`third_party_insurer_is_on_kinga` tinyint DEFAULT 0,
	`third_party_address` text,
	`third_party_id_number` varchar(50),
	`third_party_phone` varchar(50),
	`third_party_insurer_phone` varchar(50),
	`police_report_number` varchar(100),
	`police_station` varchar(255),
	`police_report_extracted_at` varchar(50),
	`recovery_target` enum('insurer','individual','unknown') DEFAULT 'unknown',
	`approved_settlement_amount` int,
	`recovered_amount` int,
	`currency_code` varchar(10) DEFAULT 'ZAR',
	`status` enum('pending_review','under_investigation','open','demand_sent','liability_denied','disputed_legal','settled_full','settled_partial','closed_no_recovery','archived') NOT NULL DEFAULT 'pending_review',
	`investigation_reason` text,
	`investigation_expected_resolution_date` varchar(20),
	`recovery_deadline` varchar(20),
	`recovery_deadline_alert_sent_at` varchar(50),
	`demand_letter_sent_at` varchar(50),
	`demand_letter_s3_key` varchar(500),
	`demand_letter_url` varchar(1000),
	`demand_response_due_date` varchar(20),
	`demand_response_received_at` varchar(50),
	`settlement_agreement_date` varchar(20),
	`settlement_notes` text,
	`assigned_officer_user_id` int,
	`assigned_at` varchar(50),
	`officer_notes` text,
	`ai_demand_letter_json` longtext,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`closed_at` varchar(50),
	`is_repeat_offender` tinyint NOT NULL DEFAULT 0,
	`prior_case_count` int NOT NULL DEFAULT 0,
	`prior_case_ids` text,
	CONSTRAINT `recovery_cases_id` PRIMARY KEY(`id`)
);