CREATE TABLE `service_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`vehicle_id` int NOT NULL,
	`fleet_id` int,
	`owner_id` int NOT NULL,
	`tenant_id` varchar(64),
	`request_type` enum('maintenance','repair','inspection','emergency') NOT NULL,
	`service_category` enum('engine','transmission','brakes','suspension','electrical','bodywork','tires','hvac','general') NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text NOT NULL,
	`urgency` enum('low','medium','high','critical') DEFAULT 'medium',
	`current_mileage` int,
	`problem_images` text,
	`diagnostic_codes` text,
	`status` enum('open','quotes_received','quote_accepted','in_progress','completed','cancelled') DEFAULT 'open',
	`quotes_received` int DEFAULT 0,
	`selected_quote_id` int,
	`selected_provider_id` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`completed_at` timestamp,
	`requires_approval` tinyint NOT NULL DEFAULT 1,
	`approval_status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`approved_by` int,
	`approved_at` timestamp,
	`rejection_reason` text,
	`submitted_by` int NOT NULL,
	CONSTRAINT `service_requests_id` PRIMARY KEY(`id`)
);