/**
 * T7: Vehicle Verification Report
 *
 * Renders only tenant-scoped vehicle and operational claim history. The
 * unscoped legacy vehicle_history table is intentionally not read because it
 * has no tenant ownership column. P0-B1 redacts fraud decision material while
 * preserving independently supported vehicle and claim facts.
 */

import mysql from "mysql2/promise";
import { buildKingaHtml, callout, esc, fmtD } from "./templates/kingaDesignSystem";
import { renderP0B1FraudAbstentionMarker } from "./p0FraudPresentation";

const DB_URL = process.env.DATABASE_URL!;
async function getConn() {
  return mysql.createConnection(DB_URL);
}

export async function generateVehicleVerificationReport(
  params: Record<string, unknown>,
  tenantId?: string,
): Promise<string> {
  const registration = String(params.registration ?? "").trim().toUpperCase();
  if (!registration) throw new Error("Vehicle registration is required");
  if (!tenantId?.trim()) throw new Error("Tenant scope is required for vehicle verification reporting");

  const conn = await getConn();
  try {
    const [claimRows] = await conn.execute(
      `SELECT c.id, c.claim_number, c.kinga_ref, c.incident_date, c.incident_type,
              c.status, c.insurer_name, c.vehicle_make, c.vehicle_model,
              c.vehicle_year, c.vehicle_vin, a.estimated_cost
       FROM claims c
       LEFT JOIN ai_assessments a ON a.claim_id = c.id
       WHERE c.vehicle_registration = ? AND c.tenant_id = ?
       ORDER BY c.created_at DESC
       LIMIT 20`,
      [registration, tenantId],
    ) as [Record<string, unknown>[], unknown];

    const claims = claimRows as Record<string, unknown>[];
    const latestClaim = claims[0] ?? null;
    const totalEstimatedCost = claims.reduce(
      (total, claim) => total + Number(claim.estimated_cost ?? 0),
      0,
    );
    const vehicleDescription = latestClaim
      ? `${esc(String(latestClaim.vehicle_year ?? "—"))} ${esc(String(latestClaim.vehicle_make ?? ""))} ${esc(String(latestClaim.vehicle_model ?? ""))}`.trim()
      : `Registration: ${esc(registration)}`;
    const reportDate = new Date().toLocaleDateString("en-ZA", {
      day: "2-digit",
      month: "long",
      year: "numeric",
    });

    const claimRowsHtml = claims.map((claim) => `
      <tr>
        <td>${esc(String(claim.kinga_ref ?? claim.claim_number ?? "—"))}</td>
        <td>${fmtD(claim.incident_date)}</td>
        <td>${esc(String(claim.incident_type ?? "—"))}</td>
        <td>${esc(String(claim.insurer_name ?? "—"))}</td>
        <td>${esc(String(claim.status ?? "—"))}</td>
        <td>${claim.estimated_cost == null ? "—" : `ZAR ${(Number(claim.estimated_cost) / 100).toLocaleString("en-ZA")}`}</td>
      </tr>`).join("");

    const body = `
      <div class="kinga-section">
        <div class="kinga-section-header">Vehicle Identity</div>
        <table class="kinga-table"><tbody>
          <tr><th>Registration</th><td><strong>${esc(registration)}</strong></td>
              <th>Vehicle</th><td>${vehicleDescription}</td></tr>
          <tr><th>VIN</th><td colspan="3">${esc(String(latestClaim?.vehicle_vin ?? "—"))}</td></tr>
        </tbody></table>
      </div>

      <div class="kinga-section">
        <div class="kinga-section-header">Tenant-Scoped Claim History</div>
        <table class="kinga-table"><tbody>
          <tr><th>Total Claims on Record</th><td>${claims.length}</td>
              <th>Total Estimated Repair Cost</th><td>ZAR ${(totalEstimatedCost / 100).toLocaleString("en-ZA")}</td></tr>
          <tr><th>Last Claim Date</th><td>${fmtD(latestClaim?.incident_date)}</td>
              <th>History Scope</th><td>Current authorised tenant only</td></tr>
        </tbody></table>
      </div>

      ${renderP0B1FraudAbstentionMarker()}

      ${claims.length > 0 ? `
      <div class="kinga-section">
        <div class="kinga-section-header">Claim History (${claims.length} record${claims.length === 1 ? "" : "s"})</div>
        <table class="kinga-table">
          <thead><tr><th>KINGA Ref</th><th>Incident Date</th><th>Type</th><th>Insurer</th><th>Status</th><th>Estimated Repair Cost</th></tr></thead>
          <tbody>${claimRowsHtml}</tbody>
        </table>
      </div>` : callout("No authorised tenant-scoped claims are available for this vehicle registration.", "green")}
    `;

    const reportTitle = `Vehicle Verification Report — ${registration}`;
    const headerHtml = `
      <div class="kinga-header">
        <div class="kinga-header-title">${esc(reportTitle)}</div>
        <div class="kinga-header-meta">Report Date: ${esc(reportDate)} &nbsp;|&nbsp; Generated by KINGA AutoVerify AI</div>
      </div>`;
    return buildKingaHtml(reportTitle, headerHtml + body);
  } finally {
    await conn.end();
  }
}
